const words1_FromBook = [
	{
		firstForm: `be`,
		twiceForm: `was`,
		twiceForm2: `were`,
		thirdForm: `been`,
		translation: `być`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `become`,
		twiceForm: `became`,
		thirdForm: `become`,
		translation: `stawać się`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `begin`,
		twiceForm: `began`,
		thirdForm: `begun`,
		translation: `zaczynać (się)`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `bend`,
		twiceForm: `bent`,
		thirdForm: `bent`,
		translation: `zginać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `bite`,
		twiceForm: `bit`,
		thirdForm: `bitten`,
		translation: `gryźć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `blow`,
		twiceForm: `blew`,
		thirdForm: `blown`,
		translation: `dmuchać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `break`,
		twiceForm: `broke`,
		thirdForm: `broken`,
		translation: `łamać`,
		translation2: `rozbić`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `bring`,
		twiceForm: `brought`,
		thirdForm: `brought`,
		translation: `przynosić`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `build`,
		twiceForm: `built`,
		thirdForm: `built`,
		translation: `budować`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `burn`,
		twiceForm: `burned`,
		twiceForm2: `burnt`,
		thirdForm: `burned`,
		thirdForm2: `burnt`,
		translation: `palić (się)`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `buy`,
		twiceForm: `bought`,
		thirdForm: `bought`,
		translation: `kupować`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `can`,
		twiceForm: `could`,
		thirdForm: `been able to`,
		translation: `móc`,
		translation2: `potrafić`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `catch`,
		twiceForm: `caught`,
		thirdForm: `caught`,
		translation: `łapać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `choose`,
		twiceForm: `chose`,
		thirdForm: `chosen`,
		translation: `wybierać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `come`,
		twiceForm: `came`,
		thirdForm: `come`,
		translation: `przychodzić`,
		translation2: `przybywać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `cost`,
		twiceForm: `cost`,
		thirdForm: `cost`,
		translation: `kosztować`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `cut`,
		twiceForm: `cut`,
		thirdForm: `cut`,
		translation: `ciąć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `do`,
		twiceForm: `did`,
		thirdForm: `done`,
		translation: `robić`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `draw`,
		twiceForm: `drew`,
		thirdForm: `drawn`,
		translation: `rysować`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `drink`,
		twiceForm: `drank`,
		thirdForm: `drunk`,
		translation: `pić`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `drive`,
		twiceForm: `drove`,
		thirdForm: `driven`,
		translation: `jechać`,
		translation2: `prowadzić samochód`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `eat`,
		twiceForm: `ate`,
		thirdForm: `eaten`,
		translation: `jeść`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `fall`,
		twiceForm: `fell`,
		thirdForm: `fallen`,
		translation: `upadać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `feel`,
		twiceForm: `felt`,
		thirdForm: `felt`,
		translation: `czuć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `fight`,
		twiceForm: `fought`,
		thirdForm: `fought`,
		translation: `walczyć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `find`,
		twiceForm: `found`,
		thirdForm: `found`,
		translation: `znaleźć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `fly`,
		twiceForm: `flew`,
		thirdForm: `flown`,
		translation: `latać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `forget`,
		twiceForm: `forgot`,
		thirdForm: `forgotten`,
		translation: `zapomnieć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `get`,
		twiceForm: `got`,
		thirdForm: `got`,
		translation: `dostawać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `go`,
		twiceForm: `went`,
		thirdForm: `gone`,
		translation: `iść`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `grow`,
		twiceForm: `grew`,
		thirdForm: `grown`,
		translation: `rosnąć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `hang`,
		twiceForm: `hung`,
		thirdForm: `hung`,
		translation: `wieszać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `have`,
		twiceForm: `had`,
		thirdForm: `had`,
		translation: `mieć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `hear`,
		twiceForm: `heard`,
		thirdForm: `heard`,
		translation: `słyszeć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `hide`,
		twiceForm: `hid`,
		thirdForm: `hidden`,
		translation: `ukrywać (się)`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `hit`,
		twiceForm: `hit`,
		thirdForm: `hit`,
		translation: `uderzać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `keep`,
		twiceForm: `kept`,
		thirdForm: `kept`,
		translation: `trzymać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `know`,
		twiceForm: `knew`,
		thirdForm: `known`,
		translation: `wiedzieć`,
		translation2: `znać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `lay`,
		twiceForm: `laid`,
		thirdForm: `laid`,
		translation: `kłaść`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `lead`,
		twiceForm: `led`,
		thirdForm: `led`,
		translation: `prowadzić`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `learn`,
		twiceForm: `learned`,
		twiceForm2: `learnt`,
		thirdForm: `learned`,
		thirdForm2: `learnt`,
		translation: `uczyć się`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `leave`,
		twiceForm: `left;`,
		thirdForm: `left;`,
		translation: `opuszczać`,
		translation2: `wyjeżdżać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
        firstForm: `lend`,
        twiceForm: `lent`,
        thirdForm: `lent`,
        translation: `pożyczyć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `lose`,
        twiceForm: `lost`,
        thirdForm: `lost`,
        translation: `gubić`,
        translation2: `zgubić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `make`,
        twiceForm: `made`,
        thirdForm: `made`,
        translation: `robić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `mean`,
        twiceForm: `meant`,
        thirdForm: `meant`,
        translation: `znaczyć`,
        translation2: `mieć na myśli`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `meet`,
        twiceForm: `met`,
        thirdForm: `met`,
        translation: `spotykać`,
        translation2: `poznawać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `overcome`,
        twiceForm: `overcame`,
        thirdForm: `overcome`,
        translation: `przezwyciężać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `pay`,
        twiceForm: `paid`,
        thirdForm: `paid`,
        translation: `płacić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `put`,
        twiceForm: `put`,
        thirdForm: `put`,
        translation: `kłaść`,
        translation2: `położyć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `read`,
        twiceForm: `read`,
        thirdForm: `read`,
        translation: `czytać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `ride`,
        twiceForm: `rode`,
        thirdForm: `ridden`,
        translation: `jeździć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `ring`,
        twiceForm: `rang`,
        thirdForm: `rung`,
        translation: `dzwonić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `run`,
        twiceForm: `ran`,
        thirdForm: `run`,
        translation: `biec`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `say`,
        twiceForm: `said`,
        thirdForm: `said`,
        translation: `mówić`,
        translation2: `powiedzieć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `see`,
        twiceForm: `saw`,
        thirdForm: `seen`,
        translation: `widzieć`,
        translation2: `zobaczyć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `sell`,
        twiceForm: `sold`,
        thirdForm: `sold`,
        translation: `sprzedać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `send`,
        twiceForm: `sent`,
        thirdForm: `sent`,
        translation: `wysyłać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `set`,
        twiceForm: `set`,
        thirdForm: `set`,
        translation: `umieszczać`,
        translation2: `zachodzić (coś)`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `shake`,
        twiceForm: `shook`,
        thirdForm: `shook`,
        translation: `potrząsnąć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `shine`,
        twiceForm: `shone`,
        thirdForm: `shone`,
        translation: `świecić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `shoot`,
        twiceForm: `shot`,
        thirdForm: `shot`,
        translation: `strzelać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `show`,
        twiceForm: `showed`,
        thirdForm: `shown`,
        translation: `pokazać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `shut`,
        twiceForm: `shut`,
        thirdForm: `shut`,
        translation: `zamykać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `sing`,
        twiceForm: `sang`,
        thirdForm: `sung`,
        translation: `śpiewać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `sink`,
        twiceForm: `sank`,
        thirdForm: `sunk`,
        translation: `tonąć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `sit`,
        twiceForm: `sat`,
        thirdForm: `sat`,
        translation: `siedzieć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `sleep`,
        twiceForm: `slept`,
        thirdForm: `slept`,
        translation: `spać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `smell`,
        twiceForm: `smelled`,
        twiceForm2: `smelt`,
        thirdForm: `smelled`,
        thirdForm2: `smelt`,
        translation: `wąchać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `speak`,
        twiceForm: `spoke`,
        thirdForm: `spoken`,
        translation: `mówić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `spell`,
        twiceForm: `spelled`,
        twiceForm2: `spelt`,
        thirdForm: `spelled`,
        thirdForm2: `spelt`,
        translation: `literować`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `spend`,
        twiceForm: `spent`,
        thirdForm: `spent`,
        translation: `spędzać`,
        translation2: `wydawać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `spill`,
        twiceForm: `spilled`,
        twiceForm2: `spilt`,
        thirdForm: `spilled`,
        thirdForm2: `spilt`,
        translation: `rozlewać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `stand`,
        twiceForm: `stood`,
        thirdForm: `stood`,
        translation: `stać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `steal`,
        twiceForm: `stole`,
        thirdForm: `stolen`,
        translation: `kraść`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `swim`,
        twiceForm: `swam`,
        thirdForm: `swum`,
        translation: `pływać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `take`,
        twiceForm: `took`,
        thirdForm: `taken`,
        translation: `brać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `teach`,
        twiceForm: `taught`,
        thirdForm: `taught`,
        translation: `uczyć (kogoś)`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `tell`,
        twiceForm: `told`,
        thirdForm: `told`,
        translation: `powiedzieć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `think`,
        twiceForm: `thought`,
        thirdForm: `thought`,
        translation: `sądzić`,
        translation2: `myśleć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `throw`,
        twiceForm: `threw`,
        thirdForm: `thrown`,
        translation: `rzucać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `understand`,
        twiceForm: `understood`,
        thirdForm: `understood`,
        translation: `rozumieć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `wake`,
        twiceForm: `woke`,
        thirdForm: `woken`,
        translation: `budzić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `wear`,
        twiceForm: `wore`,
        thirdForm: `worn`,
        translation: `nosić (na sobie)`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `win`,
        twiceForm: `won`,
        thirdForm: `won`,
        translation: `wygrywać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `write`,
        twiceForm: `wrote`,
        thirdForm: `written`,
        translation: `pisać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    }
	{
        firstForm: `test`,
        twiceForm: `test2`,
        thirdForm: `test3`,
        translation: `tłumaczenie`,
	level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    }
]

export default words1_FromBook
