const words2_DescribingProducts = [
 {
  word1: `cheap and cheerful`,
  translation1: `tani, ale dobrej jakości`,
  level: `basic`,
  type: `opisywanie towarów`,
  image: `url`,
 },
 {
  word1: `cost a fortune`,
  translation1: `kosztować majątek`,
  level: `basic`,
  type: `opisywanie towarów`,
  image: `url`,
 },
 {
  word1: `costly`,
  translation1: `kosztowny`,
  level: `basic`,
  type: `opisywanie towarów`,
  image: `url`,
 },
 {
  word1: `cut-prize`,
  translation1: `przeceniony`,
  level: `basic`,
  type: `opisywanie towarów`,
  image: `url`,
 },
 {
  word1: `end of line`,
  translation1: `końcówka kolekcji`,
  level: `basic`,
  type: `opisywanie towarów`,
  image: `url`,
 },
 {
  word1: `fair price`,
  translation1: `uczciwa cena`,
  level: `basic`,
  type: `opisywanie towarów`,
  image: `url`,
 },
 {
  word1: `half-price`,
  translation1: `za połowę ceny`,
  level: `basic`,
  type: `opisywanie towarów`,
  image: `url`,
 },
 {
  word1: `high-priced`,
  translation1: `drogi`,
  level: `basic`,
  type: `opisywanie towarów`,
  image: `url`,
 },
 {
  word1: `inexpensive`,
  translation1: `niedrogi`,
  level: `basic`,
  type: `opisywanie towarów`,
  image: `url`,
 },
 {
  word1: `low prize`,
  translation1: `niska cena`,
  level: `basic`,
  type: `opisywanie towarów`,
  image: `url`,
 },
 {
  word1: `low-cost`,
  translation1: `tani`,
  level: `basic`,
  type: `opisywanie towarów`,
  image: `url`,
 },
 {
  word1: `overpriced`,
  translation1: `zbyt drogi`,
  level: `basic`,
  type: `opisywanie towarów`,
  image: `url`,
 },
 {
  word1: `pocket-sized`,
  translation1: `miniaturowy (kieszonkowy)`,
  level: `basic`,
  type: `ubezpieczenie`,
  image: `url`,
 },
 {
  word1: `second-hand`,
  translation1: `używany`,
  level: `basic`,
  type: `ubezpieczenie`,
  image: `url`,
 },
 {
  word1: `top quality`,
  translation1: `najwyższej jakości`,
  level: `basic`,
  type: `ubezpieczenie`,
  image: `url`,
 },
 {
  word1: `value for money`,
  translation1: `towar wart swojej ceny`,
  level: `basic`,
  type: `ubezpieczenie`,
  image: `url`,
 },
 {
  word1: `worth`,
  translation1: `wart`,
  level: `basic`,
  type: `ubezpieczenie`,
  image: `url`,
 },
];

export default words2_DescribingProducts