const words5_Advertising = [
 {
  word1: `advertise`,
  translation1: `reklamować`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `advertisement (advert)`,
  translation1: `reklama`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `banner`,
  translation1: `baner reklamowy`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `billboard`,
  translation1: `billboard`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `brand name`,
  translation1: `marka (nazwa firmowa)`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `brochure`,
  translation1: `prospekt (broszura reklamowa)`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `commercial`,
  translation1: `reklama radiowa lub telewizyjna`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `consumer`,
  translation1: `konsument`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `flier`,
  translation1: `ulotka`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `free gift`,
  translation1: `gratis (darmowy dodatek)`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `logo`,
  translation1: `logo`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `personal ad`,
  translation1: `ogłoszenie towarzyskie`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `poster`,
  translation1: `plakat`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `slogan`,
  translation1: `slogan`,
  level: `basic`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `celebrity endorsement`,
  translation1: `udział znanej osoby w reklamie`,
  level: `extended`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `cold calling`,
  translation1: `akwizycja przez telefon`,
  level: `extended`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `marketing campaign`,
  translation1: `kampania marketingowa`,
  level: `extended`,
  type: `extended`,
  image: `url`,
 },
 {
  word1: `product placement`,
  translation1: `lokowanie produktu`,
  level: `extended`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `sports sponsorship`,
  translation1: `sponsorowanie imprez sportowych`,
  level: `extended`,
  type: `reklama`,
  image: `url`,
 },
 {
  word1: `viral advertising`,
  translation1: `reklama wirusowa`,
  level: `extended`,
  type: `reklama`,
  image: `url`,
 },
];

export default words5_Advertising