const words7_MeansOfPayment = [
 {
  word1: `by card`,
  translation1: `kartą`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `by cheque`,
  translation1: `czekiem`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `chip and pin device`,
  translation1: `terminal (do kart płatniczych czipem)`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `coins`,
  translation1: `money`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `contactless`,
  translation1: `bezdotykowy`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `credit card`,
  translation1: `karta kredytowa`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `debit card`,
  translation1: `karta debetowa`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `deduct`,
  translation1: `potrącać`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `go through`,
  translation1: `przejść (transakcję kartą)`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `in cash`,
  translation1: `gotówką`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `insert a card`,
  translation1: `włożyć kartę`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `internet fraud`,
  translation1: `oszustwo internetowe`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `key in`,
  translation1: `wprowadzać`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `lose a card`,
  translation1: `zgubić kartę`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `notes`,
  translation1: `banknoty`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `pin number`,
  translation1: `numer pin`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
 {
  word1: `small change`,
  translation1: `drobne`,
  level: `basic`,
  type: `środki płatnicze`,
  image: `url`,
 },
];

export default words7_MeansOfPayment