const words8_Banks = [
 {
  word1: `account number`,
  translation1: `numer konta`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `bank loan`,
  translation1: `kredyt w banku`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `borrow (lend)`,
  translation1: `pożyczać od kogoś (komuś)`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `cash`,
  translation1: `gotówka`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `cashpoint`,
  translation1: `bankomat`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `check the balance`,
  translation1: `sprawdzić stan konta`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `check your account`,
  translation1: `sprawdzić konto`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `invest`,
  translation1: `zainwestować`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `online banking`,
  translation1: `bankowość internetowa`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `open an account`,
  translation1: `otworzyć konto`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `put in money`,
  translation1: `wpłacać pieniądze`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `take out money`,
  translation1: `wypłacać pieniądze`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `savings account`,
  translation1: `konto oszczędnościowe`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `statement`,
  translation1: `wyciąg (z konta)`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `accept credit cards`,
  translation1: `akceptować karty kredytowe`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `transfer money`,
  translation1: `przelać pieniądze`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `currency`,
  translation1: `waluta`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `current account`,
  translation1: `konto bieżące`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `deposit`,
  translation1: `wpłata (lokata)`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `deposit account`,
  translation1: `rachunek depozytowy`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `earn interest on`,
  translation1: `otrzymywać zysk z oprocentowania (czegoś)`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `exchange rate`,
  translation1: `kurs wymiany walut`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `in the red`,
  translation1: `na minusie`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `interest rates`,
  translation1: `oprocentowanie`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `investment bond`,
  translation1: `obligacja inwestycyjna`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `overdraft`,
  translation1: `debet`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `overdraft`,
  translation1: `debet`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `pay interest on`,
  translation1: `płacić odsetki od`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `windfall`,
  translation1: `nieoczekiwany przypływ gotówki`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
 {
  word1: `withdraw`,
  translation1: `wypłacić (pieniądze z banku)`,
  level: `basic`,
  type: `banki`,
  image: `url`,
 },
];

export default words8_Banks