const words10_Other = [
 {
  word1: `avoid`,
  translation1: `unikać`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `be reasonable with money`,
  translation1: `rozsądnie gospodarować pieniędzmi`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `brilliant`,
  translation1: `wspaniały`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `deafening`,
  translation1: `ogłuszający`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `do a favour`,
  translation1: `wyświadczyć przysługę`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `exciting`,
  translation1: `ekscytujący`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `insist on`,
  translation1: `nalegać na`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `feel about`,
  translation1: `czuć`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `go ahead`,
  translation1: `ruszyć z czymś`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `keen on`,
  translation1: `lubić`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `keep an eye on`,
  translation1: `mieć coś na oku`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `meet up`,
  translation1: `spotkać się`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `on your own`,
  translation1: `samodzielnie`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `prove`,
  translation1: `udowodnić`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `spend on`,
  translation1: `wydawać na`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
 {
  word1: `totally independent`,
  translation1: `całkowicie niezależny`,
  level: `basic`,
  type: `inne`,
  image: `url`,
 },
];

export default words10_Other