const words1_TypesOfShops = [
 {
  word1: `auction site`,
  translation1: `portal aukcyjny`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `baker's`,
  translation1: `piekarnia`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `bookshop`,
  translation1: `księgarnia`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `butcher's`,
  translation1: `sklep mięsny`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `car boot sale`,
  translation1: `giełda rzeczy używanych (sprzedawanych prosto z bagażnika samochodu)`,
  translation2: `w byyprzedaż bagażników`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `chain store`,
  translation1: `sklep należący do sieci handlowej`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `charity shop`,
  translation1: `sklep, z którego dochód przeznaczony jest na cele dobroczynne`,
  translation2: `sklep charytatywny`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `chemist's`,
  translation1: `apteka`,
  translation2: `drogeria`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `clothes shop`,
  translation1: `sklep odzieżowy`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `department store`,
  translation1: `dom towarowy`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `furniture shop`,
  translation1: `sklep meblowy`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `garden centre`,
  translation1: `centrum ogrodnicze`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `gift shop`,
  translation1: `sklep z upominkami`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `greengrocer's`,
  translation1: `warzywniak`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `grocer's`,
  translation1: `sklep spożywczy`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `jeweller's`,
  translation1: `jubiler`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `kiosk`,
  translation1: `kiosk`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `local shop`,
  translation1: `sklep osiedlowy`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `market`,
  translation1: `targ`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `music shop`,
  translation1: `sklep muzyczny`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `newsagent's`,
  translation1: `kiosk z gazetami`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `pet shop`,
  translation1: `sklep zoologiczny`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `pharmacy`,
  translation1: `apteka`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `pound store`,
  translation1: `sklep "wszystko za funta"`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `shoe shop`,
  translation1: `sklep obuwniczy`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `shopping centre`,
  word2: `mall`,
  translation1: `centrum handlowe`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `sports shop`,
  translation1: `sklep sportowy`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `toy shop`,
  translation1: `sklep z zabawkami`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `vending machine`,
  translation1: `automat (z napojami lub przekąskami)`,
  level: `basic`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `boutique`,
  translation1: `butik`,
  level: `extended`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `DIY store`,
  translation1: `sklep z artykułami do majsterkowania`,
  level: `extended`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `duty-free`,
  translation1: `sklep wolnocłowy`,
  level: `extended`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `florist's`,
  translation1: `kwiaciarnia`,
  level: `extended`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `go window-shopping`,
  translation1: `oglądać wystawy sklepowe`,
  level: `extended`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `laundrette`,
  translation1: `pralnia samoobsługowa`,
  level: `extended`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `off-licence`,
  translation1: `sklep monopolowy`,
  level: `extended`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `retail outlet`,
  translation1: `punkt sprzedaży detalicznej`,
  level: `extended`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
 {
  word1: `stationery shop`,
  translation1: `sklep papierniczy`,
  level: `extended`,
  type: `rodzaje sklepów`,
  image: `url`,
 },
];

export default words1_TypesOfShops