const words3_SellingAndBuying = [
     {
      word1: `afford`,
      translation1: `pozwolić sobie na coś`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `assistant`,
      translation1: `sprzedawca`,
      female: `1-zyni`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `bargain`,
      translation1: `okazja cenowa`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `branch`,
      translation1: `oddział`,
      translation2: `filia`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `carrier bag`,
      translation1: `torba na zakupy`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `cash`,
      translation1: `gotówką`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `cashier`,
      translation1: `kasjer`,
      female: `0-ka`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `charge`,
      translation1: `pobierać (opłatę)`,
      translation2: `liczyć sobie (za coś)`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `checkout`,
      translation1: `kasa (w sklepie lub supermarkecie)`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `competitive prices`,
      translation1: `konkurencyjne ceny`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `convenient`,
      translation1: `wygodny`,
      translation2: `dogodny`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `cost`,
      translation1: `kosztować`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `customer`,
      translation1: `klient`,
      female: `0-ka`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `discount`,
      translation1: `zniżka`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `display`,
      translation1: `wystawa sklepowa`,
      translation2: `prezentować`,
      translation3: `wystawiać`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `fitting room`,
      translation1: `przymierzalnia`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `for sale`,
      translation1: `na sprzedaż`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `good deal`,
      translation1: `dobry interes`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `bad deal`,
      translation1: `zły interes`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `in a sale`,
      word2: `the sale`,
      translation1: `na wyprzedaży`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `off`,
      translation1: `taniej (np. £30 off - o 30 funtów taniej)`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `on special offer`,
      translation1: `w promocji`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `online shopping`,
      translation1: `zakupy w internecie`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `order online`,
      translation1: `zamówić w internecie`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `pay`,
      translation1: `płacić`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `purchase`,
      translation1: `kupić`,
      translation2: `nabyć`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `put up the prize`,
      translation1: `podwyższyć cenę`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `queue`,
      translation1: `kolejka`,
      translation2: `stać w kolejce`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `receipt`,
      translation1: `paragon`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `reduce from (... to ...)`,
      translation1: `przecenić z (... na ...)`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `(massive) reductions`,
      translation1: `(ogromne) obniżki`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `sell out`,
      translation1: `wyprzedać`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `special offer`,
      translation1: `oferta specjalna`,
      translation2: `promocja`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `take back`,
      translation1: `zwrócić`,
      translation2: `oddać (do sklepu)`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `trolley`,
      translation1: `wózek sklepowy`,
      level: `basic`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `aisle`,
      translation1: `alejka (w supermarkecie)`,
      level: `extended`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `automatic checkout`,
      translation1: `kasa samoobsługowa`,
      level: `extended`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `buy a bulk`,
      translation1: `kupować hurtowo`,
      level: `extended`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `buy on impulse`,
      translation1: `kupować pod wpływem impulsu`,
      level: `extended`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `get cash out`,
      translation1: `wypłacić pieniądze`,
      level: `extended`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `give a discount`,
      translation1: `udzielać rabatu`,
      level: `extended`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
     {
      word1: `give a refund`,
      translation1: `zwrócić pieniądze (za towar)`,
      level: `extended`,
      type: `sprzedawanie i kupowanie`,
      image: `url`,
     },
    ];
    
    export default words3_SellingAndBuying
    