const words4_Complaining = [
 {
  word1: `bring`,
  translation1: `zwrócić coś (do sklepu)`,
  level: `basic`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `exchange something`,
  translation1: `wymienić coś`,
  level: `basic`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `get money back`,
  translation1: `otrzymać zwrot pieniędzy`,
  level: `basic`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `not fit`,
  translation1: `nie pasować`,
  level: `basic`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `refund`,
  translation1: `zwrot pieniędzy`,
  level: `basic`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `broken`,
  translation1: `zepsuty`,
  level: `extendend`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `damaged`,
  translation1: `uszkodzony`,
  level: `extended`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `dissatisfaction`,
  translation1: `niezadowolenie`,
  level: `extended`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `faded`,
  translation1: `spłowiały`,
  level: `extended`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `faulty`,
  translation1: `wadliwy`,
  level: `extended`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `missing`,
  translation1: `brakujący`,
  level: `extended`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `out of order`,
  translation1: `zepsuty`,
  level: `extended`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `replacement`,
  translation1: `towar na wymianę`,
  level: `extended`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `scratched`,
  translation1: `zarysowany`,
  level: `extended`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `shrink`,
  translation1: `skurczyć się`,
  level: `extended`,
  type: `reklamacje`,
  image: `url`,
 },
 {
  word1: `unsatisfactory`,
  translation1: `niezadowalający`,
  level: `extended`,
  type: `reklamacje`,
  image: `url`,
 },
];

export default words4_Complaining