const words6_Services = [
 {
  word1: `bank`,
  translation1: `bank`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `beauty salon`,
  translation1: `salon piękności`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `car wash`,
  translation1: `myjnia samochodowa`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `deliver`,
  translation1: `dostarczać`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `doctor's surgery`,
  translation1: `gabinet lekarski`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `driving school`,
  translation1: `szkoła jazdy`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `electrician`,
  translation1: `elektryk`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `gardener`,
  translation1: `ogrodnik`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `hairdresser's`,
  translation1: `zakład fryzjerski`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `petrol station`,
  translation1: `stacja benzynowa`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `plumber`,
  translation1: `hydraulik`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `police station`,
  translation1: `komisariat`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `post office`,
  translation1: `poczta`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `real estate agency`,
  translation1: `agencja nieruchomości`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `service station`,
  translation1: `stacja obsługi pojazdów`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `travel agency`,
  translation1: `biuro podróży`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `caterer`,
  translation1: `osoba zajmująca się kateringiem`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `chiropractor`,
  translation1: `kręgarz`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `council`,
  translation1: `rada (np. rada miejska)`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `courier`,
  translation1: `kurier`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `dry cleaner's`,
  translation1: `pralnia chemiczna`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `optician`,
  translation1: `optyk`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `solicitor`,
  translation1: `adwokat (radca prawny)`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
 {
  word1: `undertaker`,
  translation1: `zakład (przedsiębiorca) pogrzebowy`,
  level: `basic`,
  type: `korzystanie z usług`,
  image: `url`,
 },
];

export default words6_Services