const words9_Insurance = [
     {
      word1: `check comparison sites`,
      translation1: `sprawdzać porównywarki cen`,
      level: `basic`,
      type: `ubezpieczenie`,
      image: `url`,
     },
     {
      word1: `cover`,
      translation1: `pokrywać`,
      level: `basic`,
      type: `ubezpieczenie`,
      image: `url`,
     },
     {
      word1: `get a quote`,
      translation1: `dostać wycenę`,
      level: `basic`,
      type: `ubezpieczenie`,
      image: `url`,
     },
     {
      word1: `get insured`,
      translation1: `ubezpieczyć się`,
      level: `basic`,
      type: `ubezpieczenie`,
      image: `url`,
     },
     {
      word1: `pay monthly instalments`,
      translation1: `płacić raty miesięczne`,
      level: `basic`,
      type: `ubezpieczenie`,
      image: `url`,
     },
     {
      word1: `take out insurance`,
      translation1: `wykupić ubezpieczenie`,
      level: `basic`,
      type: `ubezpieczenie`,
      image: `url`,
     },
     {
      word1: `fraudulent claim`,
      translation1: `fałszywe roszczenie`,
      level: `basic`,
      type: `ubezpieczenie`,
      image: `url`,
     },
     {
      word1: `make a claim`,
      translation1: `wystąpić o odszkodowanie`,
      level: `basic`,
      type: `ubezpieczenie`,
      image: `url`,
     },
     {
      word1: `pay up`,
      translation1: `wypłacić pieniądze (pokryć zobowiązanie)`,
      level: `basic`,
      type: `ubezpieczenie`,
      image: `url`,
     },
     {
      word1: `premium`,
      translation1: `składka ubezpieczeniowa`,
      level: `basic`,
      type: `ubezpieczenie`,
      image: `url`,
     },
     {
      word1: `read the small print`,
      translation1: `czytać drobny druk`,
      level: `basic`,
      type: `ubezpieczenie`,
      image: `url`,
     },
     {
      word1: `renew your insurance`,
      translation1: `przedłużyć ubezpieczenie`,
      level: `basic`,
      type: `ubezpieczenie`,
      image: `url`,
     },
    ];
    
    export default words9_Insurance