const words1_JobsAndResponsibilities = [
	{
		word1: `accountant`,
		translation1: `księgowy`,
		translation2: `księgowa`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `actor`,
		translation1: `aktor`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `architect`,
		translation1: `architekt`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `beautician`,
		translation1: `kosmetyczka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `boss`,
		translation1: `szef`,
		translation2: `szefowa`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `bus driver`,
		translation1: `kierowca autobusu`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `cashier`,
		translation1: `kasjer w banku`,
		translation2: `kasjerka w banku`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `chef`,
		translation1: `szef kuchni`,
		translation2: `szefowa kuchni`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `computer programmer`,
		translation1: `programista`,
		translation2: `programistka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `dentist`,
		translation1: `dentysta`,
		translation2: `dentystka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `doctor`,
		translation1: `lekarz`,
		translation2: `lekarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `economist`,
		translation1: `ekonomista`,
		translation2: `ekonomistka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `electrician`,
		translation1: `elektryk`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `farmer`,
		translation1: `rolnik`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `fashion designer`,
		translation1: `projektant mody`,
		translation2: `projektantka mody`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `film director`,
		translation1: `reżyser`,
		translation2: `reżyserka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `firefighter`,
		translation1: `strażak`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `flight attendant`,
		translation1: `steward`,
		translation2: `stewardessa`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `hairdresser`,
		translation1: `fryzjer`,
		translation2: `fryzjerka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `instructor`,
		translation1: `instruktor`,
		translation2: `instruktorka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `journalist`,
		translation1: `dziennikarz`,
		translation2: `dziennikarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `judge`,
		translation1: `sędzia`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `lawyer`,
		translation1: `prawnik`,
		translation2: `prawniczka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `lecturer`,
		translation1: `wykładowca`,
		translation2: `wykładowczyni`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `librarian`,
		translation1: `bibliotekarz`,
		translation2: `bibliotekarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `manager`,
		translation1: `kierownik`,
		translation2: `kierowniczka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `mechanic`,
		translation1: `mechanik`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `miner`,
		translation1: `górnik`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `model`,
		translation1: `model`,
		translation2: `modelka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `musician`,
		translation1: `muzyk`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `nurse`,
		translation1: `pielęgniarz`,
		translation2: `pielęgniarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `office assistant`,
		translation1: `asystent biura`,
		translation2: `asystentka biura`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `painter`,
		translation1: `malarz`,
		translation2: `malarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `paramedic`,
		translation1: `ratownik medyczny`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `pharmacist`,
		translation1: `aptekarz`,
		translation2: `aptekarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `photographer`,
		translation1: `fotograf`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `pilot`,
		translation1: `pilot`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `plumber`,
		translation1: `hudraulik`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `police officer`,
		translation1: `policjant`,
		translation2: `policjantka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `politician`,
		translation1: `polityk`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `postman`,
		translation1: `listonosz`,
		translation2: `listonoszka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `receptionist`,
		translation1: `recepcjonista`,
		translation2: `recepcjonistka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `sales assistant`,
		translation1: `sprzedawca`,
		translation2: `sprzedawczyni`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `sales representative`,
		translation1: `reprezentant handlowy`,
		translation2: `reprezentantka handlowa`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `scientist`,
		translation1: `naukowiec`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `secretary`,
		translation1: `sekretarz`,
		translation2: `sekretarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `shop assistant`,
		translation1: `sprzedawca`,
		translation2: `sprzedawczyni`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `solider`,
		translation1: `żołnież`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `surgeon`,
		translation1: `chirurg`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `teacher`,
		translation1: `nauczyciel`,
		translation2: `nauczycielka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `travel agent`,
		translation1: `pracownik biura podróży`,
		translation2: `pracownica biura podróży`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `TV presenter`,
		translation1: `prezenter telewizyjny`,
		translation2: `prezenterka telewizyjna`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `vet`,
		translation1: `lekarz weterynarii`,
		translation2: `lekarka weterynarii`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `waiter`,
		translation1: `kelner`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `waitress`,
		translation1: `kelnerka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `writer`,
		translation1: `pisarz`,
		translation2: `pisarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	// // // -extended
	{
		word1: `carpenter`,
		translation1: `stolarz`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `chief executive`,
		translation1: `dyrektor generalny`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `comedian`,
		translation1: `komik`,
		translation2: `aktor komediowy`,
		translation3: `aktorka komediowa`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `counsellor`,
		translation1: `doradca`,
		translation2: `doradczyni`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `doorman`,
		translation1: `portier`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `editor`,
		translation1: `redaktor`,
		translation2: `redaktorka`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `graphic designer`,
		translation1: `grafik`,
		translation2: `graficzka`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `handyman`,
		translation1: `majster`,
		translation2: `złota rączka`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `nutritionist`,
		translation1: `dietetyk`,
		translation2: `dietetyczka`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word1: `psychiatrist`,
		translation1: `psychiatra`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	// // // // // -job expressions
	{
		word1: `at work`,
		translation1: `w pracy`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `be in charge of`,
		translation1: `zarządzać`,
		translation2: `odpowiadać za`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `do something for a living`,
		translation1: `utrzymywać się z czegoś`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `look for`,
		translation1: `szukać`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `profession`,
		translation1: `zawód (wymagający klasyfikacji i doświadczenia)`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `take responsibility for`,
		translation1: `wziąć odpowiedzialność za`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `work`,
		translation1: `praca (fizyczna lub umysłowa)`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `work as`,
		translation1: `pracować jako`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `work for a company`,
		translation1: `pracowac w firmie`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `work in (a hospital)`,
		translation1: `pracować w (szpitalu)`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `work in an office`,
		translation1: `pracować w biurze`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `work in sales`,
		translation1: `pracować w dziale sprzedaży`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `work in a team`,
		translation1: `pracować w zespole`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `work on`,
		translation1: `pracować nad (czymś)`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `work under pressure`,
		translation1: `pracować pod presją`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word1: `work with`,
		translation1: `pracować z (kimś)`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	// // // // // -job adjectives
	{
		word1: `dangerous`,
		translation1: `niebezpieczny`,
		level: `basic`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word1: `manual`,
		translation1: `fizyczny`,
		level: `basic`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word1: `satisfying`,
		translation1: `satycfakcjonujący`,
		level: `basic`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word1: `skilled`,
		translation1: `wymagający kwalifikacji`,
		level: `basic`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word1: `stressful`,
		translation1: `stresujący`,
		level: `basic`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word1: `tiring`,
		translation1: `męczący`,
		level: `basic`,
		type: `job adjectives`,
		image: `url`,
	},
	// // // -extended
	{
		word1: `challenging`,
		translation1: `ambitny`,
		translation2: `stanowiący wyzwanie`,
		level: `extended`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word1: `dead-end`,
		translation1: `bez perspektyw`,
		level: `extended`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word1: `monotonous`,
		translation1: `monotonny`,
		level: `extended`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word1: `motivating`,
		translation1: `motywujący`,
		level: `extended`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word1: `rewarding`,
		translation1: `satysfakcjonujący`,
		level: `extended`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word1: `undemanding`,
		translation1: `niewymagający`,
		translation2: `łatwy`,
		level: `extended`,
		type: `job adjectives`,
		image: `url`,
	}
]

export default words1_JobsAndResponsibilities