const words3_TemporaryWork = [
	{
		word1: `babysitter`,
		word2: `au pair`,
		translation1: `opiekun do dzieci`,
		female: `0-ka`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `charity worker`,
		translation1: `wolontariusz`,
		female: `0-ka`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `checkout assistant`,
		translation1: `kasjer w supermarkecie`,
		female: `0-ka first t1`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `delivery boy`,
		translation1: `roznosiciel gazet`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `delivery girl`,
		translation1: `roznosicielka gazet`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `friut picking`,
		translation1: `zbieranie owoców`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `holiday job`,
		translation1: `praca wakacyjna`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `lifeguard`,
		translation1: `ratownik`,
		female: `1-czka`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `seasonal work`,
		translation1: `praca sezonowa`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `summer camp supervisor`,
		translation1: `opiekun na obozie`,
		female: `0-ka first t1`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `summer job`,
		translation1: `praca na lato`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `tour guide`,
		translation1: `przewodnik`,
		female: `1-czka`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `voluntary work`,
		translation1: `wolontariat`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `wages`,
		translation1: `płaca`,
		translation2: `dniówka`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word1: `weekend job`,
		translation1: `praca weekendowa`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	}
]

export default words3_TemporaryWork