const words4_JobMarket = [
	{
		word1: `advertise`,
		translation1: `ogłaszać`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `applicant`,
		translation1: `kandydat (do pracy)`,
		translation2: `kandydatka (do pracy)`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `application form`,
		translation1: `formularz aplikacyjny`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `apply for a job`,
		translation1: `ubiegać się o pracę`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `be fired`,
		translation1: `zostać zwolnionym`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `be made redundant`,
		translation1: `zostać zwolnionym w ramach rekrucji etatów`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `become employed`,
		translation1: `zostać zatrudnionym`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `candidate`,
		translation1: `kandydat`,
		translation2: `kandydatka`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `covering letter`,
		translation1: `list motywacyjny`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `deadline`,
		translation1: `termin wykonania pracy`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `do well`,
		translation1: `dobrze sobie poradzić`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `employee`,
		translation1: `pracownik`,
		translation2: `pracownica`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `employer`,
		translation1: `pracodawca`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `enclose`,
		translation1: `załączyć`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `entrepreneur`,
		translation1: `przedsiębiorca`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `fill in`,
		translation1: `wypełnić`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `find work`,
		translation1: `znaleźć pracę`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `get careers edvice`,
		translation1: `skorzystać z doradztwa zawodowego`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `go bankrupt`,
		translation1: `zbankrutować`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `go freelance`,
		word2: `go freelancer`,
		translation1: `zacząć pracować na własny rachunek`,
		translation2: `wolny strzelec`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `have an interview`,
		translation1: `odbyć rozmowę kwalifikacyjną`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `have experience`,
		translation1: `mieć doświadczenie`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `hire`,
		translation1: `zatrudniać`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `human resources`,
		translation1: `dział personalny`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `job offer`,
		translation1: `oferta pracy`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `job satisfaction`,
		translation1: `zadowolenie z wykonywanej pracy`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `Jobcentre`,
		translation1: `biuro pośrednictwa pracy`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `keep a record`,
		translation1: `prowadzić rejestr`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `lack of (experience)`,
		translation1: `brak (doświadczenia)`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `lose your job`,
		translation1: `stracić pracę`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `offer a job`,
		translation1: `zaproponować pracę`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `out of work`,
		translation1: `bez pracy`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `position`,
		translation1: `praca`,
		translation2: `stanowisko`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `post`,
		translation1: `stanowisko`,
		translation2: `posada`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `qualifications`,
		translation1: `kwalifikacje`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `recruitment`,
		translation1: `rekrutacja`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `reference`,
		translation1: `referencje`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `reject`,
		translation1: `odrzucić`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `resign`,
		translation1: `złożyć rezygnację`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `run your own business`,
		translation1: `prowadzić własną firmę`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `self-employed`,
		translation1: `samozatrudniony`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `short list`,
		translation1: `lista najpoważniejszych kandydatów`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `situations vacant`,
		translation1: `oferty pracy (rubryka w gazecie)`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `staff`,
		translation1: `personel`,
		translation2: `kadra`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `take up a job`,
		translation1: `podjąć pracę`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `unemployed`,
		translation1: `bezrobotny`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `up-to-date`,
		translation1: `aktualny`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `vacancy`,
		translation1: `wakat`,
		translation2: `wolne stanowisko`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `work from home`,
		translation1: `pracować w domu`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	// // // -extended
	{
		word1: `attach a CV`,
		translation1: `załączyć CV`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `check out a company`,
		translation1: `sprawdzić informacje o firmie`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `get in-house training`,
		translation1: `przejść wewnętrzne szkolenie`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `get sacked`,
		translation1: `zostać zwolnionym z pracy`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `go on strike`,
		translation1: `strajkować`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `hand in your notice`,
		translation1: `wręczyć wymówienie`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `hand over information`,
		translation1: `przekazać informacje`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `have a complaints procedure`,
		translation1: `mieć procedurę składania reklamacji`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `join a union`,
		translation1: `zapisać się do związku zawodowego`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `sing on (the dole)`,
		translation1: `zarejestrować się (jako bezrobotny)`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `start up a business`,
		translation1: `założyć firmę`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `take on`,
		translation1: `przyjąć`,
		translation2: `zatrudnić`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `take over from someone`,
		translation1: `przejąć od kogoś obowiązki`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `take time off`,
		translation1: `wziąć wolne`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `take up a position`,
		translation1: `objąć stanowisko`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `take up a reference`,
		translation1: `sprawdzić referencje kandydata`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word1: `work flextime`,
		translation1: `mieć elastyczne godziny pracy`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	}
]

export default words4_JobMarket