const testWords = [
    {
      word1: 'one',
      word2: 'one2',
      translation1: 'jeden',
      level: 'basic',
      type: 'clothes',
      image: 'https://c.pxhere.com/photos/21/97/number_ad_yellow_color_asphalt_road_digit_numbering-1334880.jpg!d',
    },
    {
      word1: 'two',
      translation1: 'dwa',
      level: 'basic',
      type: 'clothes',
      image: 'https://c.pxhere.com/photos/d5/b3/number_ad_yellow_color_asphalt_road_digit_numbering-938197.jpg!d',
    },
    {
      word1: 'three',
      translation1: 'trzy',
      level: 'basic',
      type: 'clothes',
      image: 'https://c.pxhere.com/photos/29/93/number_ad_yellow_color_asphalt_road_digit_numbering-938175.jpg!d',
    },
    {
      word1: 'live on one\'s own',
      word2: 'live on one\'s own2',
      word3: 'live on one\'s own3',
      translation1: 'mieszkać samemu',
      level: 'basic',
      type: 'clothes',
      image: 'https://c.pxhere.com/photos/29/93/number_ad_yellow_color_asphalt_road_digit_numbering-938175.jpg!d',
    },
    {
      word1: 'from 1 to 2',
      translation1: 'jeden (12)',
      translation2: 'dwa (12)',
      level: 'basic',
      type: 'clothes',
      image: 'https://c.pxhere.com/photos/77/8b/inches_imperial_measure_inch_foot_measurement_length_equipment-690975.jpg!d',
    },
    {
      word1: 'from 1 to 3',
      translation1: 'jeden (123)',
      translation2: 'dwa (123)',
      translation3: 'trzy (123)',
      level: 'basic',
      type: 'clothes',
      image: 'https://c.pxhere.com/photos/4b/1d/pi_mathematics_love_locks_hohenzollern_bridge_cologne_bridge_railway_bridge_gold-738305.jpg!d',
    },
];