const testWords = [
	{
		word1: `lined`,
		translation1: `ocieplany`,
		translation2: `na podszewce`,
		female: `t1`,
		level: `extended`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/dc/f8/winter_jacket_scarf_wool_scarf_woman_girl_modern_young_woman_female-1186579.jpg!s`,
	}
		// {
		// 	word1: `clever`,
		// 	translation1: `mądry`,
		// 	female: `yes`,
		// 	level: `basic`,
		// 	type: `test`,
		// 	subtype: `y => a`,
		// 	image: `url`,
		// },
		// {
		// 	word1: `confident`,
		// 	translation1: `pewny siebie dziewczyna`,
		// 	translation2: `2pewny siebie`,
		// 	translation3: `3pewny siebie`,
		// 	female: `second in t1`,
		// 	level: `basic`,
		// 	type: `test`,
		// 	image: `url`,
		// },
		// {
		// 	word1: `overconfident`,
		// 	translation1: `zbyt pewny siebie dziewczyna`,
		// 	translation2: `2zbyt pewny siebie dziewczyna`,
		// 	translation3: `3zbyt pewny siebie dziewczyna`,
		// 	female: `second in t1+t2`,
		// 	level: `basic`,
		// 	type: `test`,
		// 	image: `url`,
		// },
		// {
		// 	word1: `drama queen`,
		// 	translation1: `panikarz`,
		// 	translation2: `osoba nadmiernie dramatyzująza`,
		// 	female: `t1`,
		// 	level: `basic`,
		// 	type: `test`,
		// 	image: `url`,
		// },
		// {
		// 	word1: `extrovert`,
		// 	translation1: `ekstrawertyk`,
		// 	female: `1-czka`,
		// 	level: `basic`,
		// 	type: `test`,
		// 	image: `url`,
		// },
		// {
		// 	word1: `babysitter`,
		// 	word2: `au pair`,
		// 	translation1: `super opiekun do dzieci`,
		// 	translation2: `super 2opiekun do dzieci`,
		// 	translation3: `super 3opiekun do dzieci`,
		// 	female: `0-ka second in t1+t2+t3`,
		// 	level: `basic`,
		// 	type: `test`,
		// 	image: `url`,
		// }
];

export default testWords