const words2_GradesAndCourseRequirements = [
	{
		word1: `cheat`,
		translation1: `oszukiwać`,
		translation2: `ściągać`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `copy`,
		translation1: `przepisać`,
		translation2: `skopiować`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `cram`,
		translation1: `wkuwać`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `diploma`,
		translation1: `dyplom`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `end-of-term exam`,
		translation1: `egzamin semestralny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `end-of-year exam`,
		translation1: `egzamin na koniec roku`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `exam paper`,
		translation1: `arkusz egzaminacyjny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `examination`,
		translation1: `egzamin`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `extra lessons`,
		translation1: `dodatkowe lekcje`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `take an exam`,
		translation1: `podejść do egzaminu`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `fail`,
		translation1: `oblać`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `final exam`,
		translation1: `egzamin końcowy`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `get caught`,
		translation1: `zostać złapanym`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `get results`,
		translation1: `otrzymywać wyniki`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `give marks`,
		translation1: `wystawiać oceny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `go towards`,
		translation1: `składać się na`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `grade`,
		word2: `mark`,
		translation1: `ocena`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `memorise`,
		translation1: `uczyć się na pamięć`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `mock exam`,
		word2: `practise exam`,
		translation1: `egzamin próbny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `oral exam`,
		translation1: `egzamin ustny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `pass`,
		translation1: `zdać`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `past paper`,
		translation1: `arkusz egzaminacyjny z poprzednich lat`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `practical`,
		translation1: `praktyczny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `retake`,
		translation1: `zdawać ponownie`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `revise for`,
		translation1: `powtarzać do`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `school-leaving exam`,
		translation1: `egzamin kończący naukę w szkole`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `send out`,
		translation1: `wysyłać`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `take a test`,
		translation1: `podejść do testu`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `test`,
		translation1: `test`,
		translation2: `klasówka`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `written`,
		translation1: `pisemny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `A levels`,
		translation1: `brytyjski odpowiednik matury`,
		translation2: `egzamin dojrzałości`, 
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `academic results`,
		translation1: `wyniki w nauce`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `award`,
		translation1: `nagroda`,
		translation2: `nagrodzić`, 
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `BA`,
		word2: `Bachelor of Arts`,
		translation1: `licencjat na kierunku humanistycznym`,
		translation2: `licencjat sztuk pieknych`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `MA`,
		word2: `Masters of Arts`,
		translation1: `magister nauk humanistycznych`, 
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `BSc`,
		word2: `Bachelor of Science`,
		translation1: `licencjat w dziedzinie nauk ścisłych lub przyrodniczych`,
		translation2: `licencjat nauk ścisłych`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `certificate`,
		translation1: `świadectwo`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `distinction`,
		translation1: `wyróżnienie`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `GCSEs`,
		translation1: `egzamin gimnazjalny`,
		translation2: `brytyjski odpowiednik egzaminu gimnazjalnego`, 
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `get a degree`,
		translation1: `otrzymać stopień naukowy`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `graduate`,
		translation1: `absolwent`,
		translation2: `zmęczony`, 
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `graduate from`,
		translation1: `ukończyć (studia wyższe)`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `International Baccalaureate`,
		translation1: `matura międzynarodowa`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `pass with flying colours`,
		translation1: `zdać celująco`,
		translation2: `zdać śpiewająco`, 
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `scrape through`,
		translation1: `z trudem przebrnąć (np. przez egzamin)`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word1: `win a scholarship`,
		translation1: `zdobyć stypendium`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	}
]

export default words2_GradesAndCourseRequirements