const words3_SchoolLive = [
	{
		word1:  `absent`,
		translation1: `nieobecny`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `bell`,
		translation1: `dzwonek`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `break`,
		translation1: `przerwa`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `bully`,
		translation1: `dręczyć`,
		translation2: `prześladować`, 
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `check your work`,
		translation1: `sprawdzić swoją pracę`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `concentrate`,
		translation1: `skupić się`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `coursebook`,
		translation1: `podręcznik`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `coursework`,
		translation1: `praca okresowa`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `curriculum`,
		translation1: `program nauczania`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `deadline`,
		translation1: `termin do wykonania pracy`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `dictation`,
		translation1: `dyktando`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `do your homework`,
		translation1: `odrabiać lekcje`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `do research`,
		translation1: `poszukiwać informacji`,
		translation2: `prowadzić badania`, 
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `do an assignment`,
		translation1: `wykonać zadaną pracę`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `write an assignment`,
		translation1: `napisać zadaną pracę`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `do an essay`,
		word2: `write an essay`,
		translation1: `napisać wypracowanie`,
		translation2: `napisać esej`, 
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `get suspended`,
		translation1: `zostać zawieszonym`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `give a presentation`,
		translation1: `przedstawiać prezentację`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `give a talk on`,
		translation1: `wygłosić referat na temat`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `hand in homework`,
		translation1: `oddać pracę domową`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `lunch break`,
		translation1: `przerwa na lunch`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `learning style`,
		translation1: `styl uczenia się`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `make mistakes`,
		translation1: `robić błędy`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `miss lessons`,
		translation1: `opuszczać lekcje`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `motivate`,
		translation1: `motywować`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `motivating`,
		translation1: `motywujący`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `notebook`,
		translation1: `zeszyt`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `packed lunch`,
		translation1: `drugie śniadanie`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `PE kit`,
		translation1: `strój sportowy`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `play truant`,
		translation1: `wagarować`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `present`,
		translation1: `prezentować`,
		translation2: `obecny`, 
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `project work`,
		translation1: `peas projektowa`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `report someone`,
		translation1: `zgłosić kogoś`,
		translation2: `donieść na kogoś`, 
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `set homework`,
		translation1: `zadawać pracę`,
		translation2: `zadawać pracę domową`, 
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `sick note`,
		translation1: `zwolnienie z powodu choroby (np. z WF-u)`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `school bus`,
		translation1: `autobus szkolny`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `school year`,
		translation1: `rok szkolny`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `take a gap year`,
		translation1: `zrobić sobie rok przerwy między szkołą średnią a studiami`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `take notes`,
		translation1: `robić notatki`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `term`,
		translation1: `semestr`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `timetable`,
		translation1: `plan zajęć`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `work on a project`,
		translation1: `pracować nad projektem`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `work in pairs`,
		translation1: `pracować w parach`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	// // //
	{
		word1:  `absentee`,
		translation1: `osoba nieobecna`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `absenteeism`,
		translation1: `absencja`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `assembly`,
		translation1: `zgromadzenie`,
		translation2: `apel`, 
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `attendance`,
		translation1: `obecność na zajęciach`,
		translation2: `frekwencja`, 
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `compulsory`,
		translation1: `obowiązkowy`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `concentration span`,
		translation1: `czas skupienia uwagi`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `cut classes`,
		translation1: `urwać się z lekcji`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `detention`,
		translation1: `kara polegająca na zatrzymywaniu ucznia w szkole po lekcjach`,
		translation2: `aresztowanie`, 
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `forge`,
		translation1: `podrabiać`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `free period`,
		translation1: `wolna lekcja`,
		translation2: `okienko`, 
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `obligatory`,
		translation1: `obowiązkowy`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `old student`,
		translation1: `były uczeń`,
		translation2: `była uczennica`, 
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `optional`,
		translation1: `opcjonalny`,
		translation2: `dobrowolny`, 
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `prize-giving`,
		translation1: `rozdanie nagród`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `punctuality`,
		translation1: `punktualność`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `take the register`,
		translation1: `sprawdzać`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `take time off`,
		translation1: `wziąć wolne`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word1:  `tutorial`,
		translation1: `konsultacje`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	// // // // // -people
	{
		word1:  `caretaker`,
		translation1: `woźny`,
		translation2: `woźna`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word1:  `classmate`,
		translation1: `kolega z klasy`,
		translation2: `koleżanka z klasy`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word1:  `classroom assistant`,
		translation1: `asystent nauczyciela`,
		translation2: `asystentka nauczyciela`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word1:  `form tutor`,
		translation1: `wychowawca`,
		translation2: `wychowawczyni`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word1:  `head teacher`,
		translation1: `dyrektor szkoły`,
		translation2: `dyrektorka szkoły`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word1:  `pupil`,
		translation1: `uczeń`,
		translation2: `uczennica`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word1:  `staff`,
		translation1: `grono pedagogiczne`,
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word1:  `student`,
		translation1: `uczeń`,
		translation2: `uczennica`,
		translation3: `student`,
		translation4: `studentka`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word1:  `teacher`,
		translation1: `nauczyciel`,
		translation2: `nauczycielka`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	// // // -e people
	{
		word1:  `careers adviser`,
		translation1: `doradca zawodowy`,
		level: `extended`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word1:  `deputy head`,
		translation1: `wicedyrektor`,
		translation2: `wicedyrektorka`, 
		level: `extended`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word1:  `head girl`,
		word2: `head boy`, 
		translation1: `przewodnicząca samorządu szkolnego`,
		translation2: `przewodniczący samorządu szkolnego`, 
		level: `extended`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word1:  `lecturer`,
		translation1: `wykładowca`,
		level: `extended`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word1:  `perfect`,
		translation1: `gospodarz`,
		translation2: `przewodniczący klasy`, 
		level: `extended`,
		type: `ludzie`,
		image: `url`,
	},
	// // // // // -miejsca w szkole
	{
		word1:  `canteen`,
		translation1: `stołówka`,
		translation2: `bufet`, 
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word1:  `classroom`,
		translation1: `sala lekcyjna`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word1:  `common room`,
		translation1: `świetlica`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word1:  `corridor`,
		translation1: `korytarz`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word1:  `gymnasium`,
		translation1: `sala gimnastyczna`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word1:  `head teacher's office`,
		translation1: `gabinet dyrektora szkoły`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word1:  `laboratory`,
		translation1: `pracownia (fizyczna lub chemiczna)`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word1:  `library`,
		translation1: `biblioteka`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word1:  `playground`,
		translation1: `boisko`,
		translation2: `plac zabaw`, 
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word1:  `sports field`,
		translation1: `boisko`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word1:  `staffroom`,
		translation1: `pokój nauczycielski`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word1:  `lecture theatre`,
		translation1: `aula`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	}
]

export default words3_SchoolLive