const words6_Orther = [
	{
		word1: `concerned`,
		translation1: `zaniepokojony`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `confused`,
		translation1: `zdezorientowany`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `disappointed`,
		translation1: `rozczarowany`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `elicit`,
		translation1: `wydobyć`,
		translation2: `uzyskać`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `emphasise`,
		translation1: `podkreślić`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `enforce`,
		translation1: `narzucić`,
		translation2: `wymusić`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `ensure`,
		translation1: `zapewnić`,
		translation2: `upewnić się`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `fimiliar`,
		translation1: `znajomy`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `frightened`,
		translation1: `przerażony`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `impressed`,
		translation1: `pod wrażeniem`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `in favour of`,
		translation1: `na korzyść (czegoś)`,
		translation2: `za (czymś)`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `let loose`,
		translation1: `uwolnić`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `live up to expectations`,
		translation1: `spełnić oczekiwania`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `lose count of`,
		translation1: `stracić rachubę (czegoś)`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `maniac`,
		translation1: `szaleniec`,
		translation2: `maniak`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `put a plain into action`,
		translation1: `wprowadzić plan w życie`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `rates`,
		translation1: `ceny`,
		translation2: `stawki`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `stuffy`,
		translation1: `duszny`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `the far end`,
		translation1: `przeciwległy koniec`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `way too`,
		translation1: `o wiele za`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `work surface`,
		translation1: `powierzchnia robocza`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	// // // -e orther
	{
		word1: `be in two mins (about)`,
		translation1: `nie móc się zdecydować`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `cater for`,
		translation1: `zaspokajać`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `crave`,
		translation1: `pragnąć`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `deserted`,
		translation1: `opustoszały`,
		translation2: `bezludny`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `draw up`,
		translation1: `podjechać`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `end up`,
		translation1: `skoczyć (jesteś, jako ktoś)`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `face-to-face communication`,
		translation1: `bezpośrednia komunikacja (twarzą w twarz)`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `in anticipation of`,
		translation1: `oczekując (na coś)`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `maintain`,
		translation1: `utrzymywać`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `memory aid`,
		translation1: `technika ułatwiająca zapamiętywanie`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `motivational speech`,
		translation1: `przemówienie mające na celu zmotywowanie kadry zawodników do większego wysiłku`,
		translation2: `mowa motywacjna`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `opt for`,
		translation1: `optować  za`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `outperform`,
		translation1: `prześcignąć`,
		translation2: `pozostawić w tyle`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `panel`,
		translation1: `zespół`,
		translation2: `ława`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `struggle`,
		translation1: `wysilać się`,
		translation2: `usiłować`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `subdivide`,
		translation1: `dzielić się na mniejsze grupy`,
		translation2: `grupować się`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `treasured`,
		translation1: `cenny`,
		translation2: `ceniony`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `vote with your feet`,
		translation1: `wyrazić niezadowolenie poprzez ostentacyjnie wyjście lub odejście / wystąpienie (np. z kina teatru, organizacji)`,
		translation2: `"głosować nogami"`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	}
]

export default words6_Orther