const words1_TravellingAndMeansOfTransport = [
 {
  word1: `airport terminal`,
  translation1: `terminal pasażerski na lotnisku`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `bicycle`,
  translation1: `rower`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `board the plane`,
  translation1: `wejść na pokład samolotu`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `boarding pass`,
  translation1: `karta pokładowa`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `boat`,
  translation1: `łódź`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `bus`,
  translation1: `autobus`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `bus stop`,
  translation1: `przystanek autobusowy`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `buy a ticket`,
  translation1: `kupić bilet`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `cancelled`,
  translation1: `odwołany`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `car`,
  translation1: `samochód`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `carriage`,
  translation1: `wagon`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `catch a bus`,
  translation1: `złapać autobus`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `change trains`,
  translation1: `przesiąść się do innego pociągu`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `check in your luggage`,
  translation1: `odprawić bagaż`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `check-in`,
  translation1: `odprawa biletowo-bagażowa`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `coach`,
  translation1: `autobus (autokar)`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `coach station`,
  translation1: `dworzec autobusowy`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `compartment`,
  translation1: `przedział`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `delayed`,
  translation1: `opóźniony`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `departure lounge`,
  translation1: `hala odlotów`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `economy`,
  translation1: `ekonomiczna (klasa)`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `fare`,
  translation1: `opłata za przejazd`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `ferry`,
  translation1: `prom`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `ferry terminal`,
  translation1: `terminal promowy`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `first class`,
  translation1: `pierwsza klasa`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `gate`,
  translation1: `wyjście (do samolotu)`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `get on a train`,
  translation1: `wsiąść do pociągu`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `give someone a lift`,
  translation1: `podwieźć kogoś`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `go through customs`,
  translation1: `przejść odprawę celną`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `helicopter`,
  translation1: `helikopter`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `land`,
  translation1: `wylądować`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `line`,
  translation1: `linia`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `lorry`,
  translation1: `ciężarówka`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `luggage rack`,
  translation1: `półka na bagaż`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `miss a bus`,
  translation1: `spóźnić się na autobus`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `motorbike`,
  translation1: `motocykl`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `motorway`,
  translation1: `autostrada`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `passenger`,
  translation1: `pasażer`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `passport control`,
  translation1: `kontrola paszportowa`,
  level: `basic`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `pedestrian`,
  translation1: `pieszy`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `plane`,
  translation1: `samolot`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `platform`,
  translation1: `peron`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `print out a ticket`,
  translation1: `wydrukować bilet`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `public transport`,
  translation1: `transport publiczny`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `railway`,
  translation1: `kolej`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `railway station`,
  translation1: `stacja kolejowa`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `return`,
  translation1: `powrotny (bilet)`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `scooter`,
  translation1: `hulajnoga`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `ship`,
  translation1: `statek`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `single`,
  translation1: `w jedną stronę (bilet)`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `take a bus`,
  translation1: `pojechać autobusem`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `taxi rank`,
  translation1: `postój taksówek`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `taxi (cab)`,
  translation1: `taksówka`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `ticket`,
  translation1: `bilet`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `ticket office`,
  translation1: `kasa biletowa`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `traffic jam`,
  translation1: `korek uliczny`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `traffic lights`,
  translation1: `sygnalizacja świetlna`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `train`,
  translation1: `pociąg`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `tram`,
  translation1: `tramwaj`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `truck`,
  translation1: `wagon towarowy`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `underground`,
  translation1: `metro`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `underground station`,
  translation1: `stacja metra`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `van`,
  translation1: `furgonetka`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `waiting room`,
  translation1: `poczekalnia`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `yacht`,
  translation1: `jacht`,
  level: `basic`,
  type: `type`,
  image: `url`,
 },
 {
  word1: `articulated lorry`,
  translation1: `ciężarówka naczepowa`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `ask for directions`,
  translation1: `spytać o drogę`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `baggage reclaim`,
  translation1: `punkt odbioru bagażu`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `cable car`,
  translation1: `kolejka linowa`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `cancel a booking`,
  translation1: `odwołać rezerwację`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `crossing`,
  translation1: `przeprawa`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `cruise liner`,
  translation1: `statek wycieczkowy`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `deck`,
  translation1: `pokład`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `double-decker`,
  translation1: `autobus piętrowy`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `fill up`,
  translation1: `zatankować do pełna`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `four-by-four`,
  translation1: `samochód z napędem na cztery koła`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `get a speeding ticket`,
  translation1: `dostać mandat za przekroczenie prędkości`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `get an upgrade`,
  translation1: `otrzymać usługę o wyższym standardzie`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `get lost`,
  translation1: `zgubić się`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `get stuck in`,
  translation1: `utknąć w`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `harbour`,
  translation1: `port`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `have a puncture`,
  translation1: `złapać gumę`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `hitchhiking`,
  translation1: `podróżować autostopem`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `keep to the speed limit`,
  translation1: `przestrzegać ograniczenia prędkości`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `lane`,
  translation1: `pas ruchu`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `level crossing`,
  translation1: `przejazd kolejowy`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `narrow boat`,
  translation1: `barka`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `overhead locker`,
  translation1: `schowek na bagaż podręczny (w samolocie )`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `roundabout`,
  translation1: `rondo`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `runway`,
  translation1: `pas startowy`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `rush hour`,
  translation1: `godziny szczytu`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `sailing boat`,
  translation1: `żaglówka`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `season ticket`,
  translation1: `bilet okresowy`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `signal failure`,
  translation1: `awaria semafora`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `ski lift`,
  translation1: `wyciąg narciarski`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `speedboat`,
  translation1: `motorówka wyścigowa`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `speed camera`,
  translation1: `fotoradar`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `sports car`,
  translation1: `samochód sportowy`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `take pills`,
  translation1: `brać tabletki`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `track`,
  translation1: `tor kolejowy`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `travel sickness`,
  translation1: `choroba lokomocyjna`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `tunnel`,
  translation1: `tunel`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `upgrade to first class`,
  translation1: `podnieść standard do pierwszej klasy`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
 {
  word1: `wear a seat belt`,
  translation1: `zapinać pas bezpieczeństwa`,
  level: `extended`,
  type: `podróżowanie i środki transportu`,
  image: `url`,
 },
];

export default words1_TravellingAndMeansOfTransport