const words1_StagesOfLife = [
	{
		word1: `adolescence`,
		translation1: `wiek dojrzewania`,
		level: `basic`,
		type: `etapy życia`,
		image: `url`,
	},
	{
		word: `adolescent`,
		translation: `dorastający (chłopak lub dziewczyna)`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `adult`,
		translation: `dorosły`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `adulthood`,
		translation: `wiek dorosły`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `birth`,
		translation: `narodziny`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `be born`,
		translation: `urodzić się`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `bring up`,
		translation: `wychować`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `childhood`,
		translation: `dzieciństwo`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `death`,
		translation: `śmierć`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `elderly`,
		translation: `starszy`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `engagement`,
		translation: `zaręczyny`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `generation`,
		translation: `pokolenie`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `get engaged`,
		translation: `zaręczyć się`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `go to school / uniwersity`,
		translation: `pójść do szkoły`,
		translation2: `pójść do uniwersytetu`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `have a baby`,
		translation: `mieć dziecko`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `kid`,
		translation: `dziecko`,
		translation2: `dzieciak`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `leave home`,
		translation: `wyprowadzić się z domu`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `middle-aged`,
		translation: `w średnim wieku`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `middle-age`,
		translation: `wiek średni`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `old-age`,
		translation: `starość`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	{
		word: `pemsioner`,
		translation: `emeryt`,
		translation2: `emerytka`,
		level: `basic`,
		type: `type`,
		image: `url`,
	},
	
]

export default words1_StagesOfLife