const words1_PersonalData = [
    {
        word1: `address`,
        translation1: `adres`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/9e/f5/haiku_18270mm-440868.jpg!s`,
    },
    {
        word1: `age`,
        translation1: `wiek`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/85/35/smartphone_face_man_old_baby_young_child_youth-356039.jpg!s`,
    },
    {
        word1: `date od birth`,
        translation1: `data urodzenia`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/35/db/birth_baby_stork-855019.jpg!s`,
    },
    {
        word1: `divorced`,
        translation1: `rozwiedziony`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/60/8d/hand_finger_people_ring_marriage_divorce_decisions_background-1250784.jpg!s`,
    },
    {
        word1: `female`,
        translation1: `kobieta`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/b4/81/girl_with_flowers_photoshoot_hair_style_model_emotions_fashion_female-628722.jpg!s`,
    },
    {
        word1: `first name`,
        translation1: `imię`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/images/99/ae/43b2764860e162557187df0ac2ba-1444615.jpg!s`,
    },
    {
        word1: `gender`,
        translation1: `płeć`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/fa/c0/women's_power_specialist_businesswoman_woman_female_woman_sign_gender_executive-934569.jpg!s`,
    },
    {
        word1: `male`,
        translation1: `mężczyzna`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/images/04/dc/acef9e725fcec44960ae74501ddc-1424069.jpg!s`,
    },
    {
        word1: `marital status`,
        translation1: `stan cywilny`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/images/05/4f/cd9cc55daa249e2fa5960f7c7443-1450317.jpg!s`,
    },
    {
        word1: `married`,
        translation1: `żonaty`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/35/e0/beach_wedding_bride_groom_ocean_sea_romantic_romance_sand-911700.jpg!s`,
    },
    {
        word1: `nationality`,
        translation1: `narodowość`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/4b/c0/polish_flag_independence_independence_day_nationality_flag_public_holiday_flag_flutters_white_and_red_flag-1173680.jpg!s`,
    },
    {
        word1: `occupation`,
        translation1: `zawód`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/images/b7/d7/26672096c3b791dc4c45e7a7dabb-1446035.jpg!s`,
    },
    {
        word1: `single`,
        translation1: `stanu wolnego`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/c9/5b/seaside_man_sitting_relax_wait_wall_waiting_lifestyle-959036.jpg!s`,
    },
    {
        word1: `surname`,
        translation1: `nazwisko`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/images/50/bb/b66ced3b0f6c8130875ec570a3c4-1588499.jpg!s`,
    },
    {
        word1: `widowed`,
        translation1: `owdowiały`,
        level: `basic`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/bf/b6/solo_reader_old_park_old_sitting_in_the_park_forest_nature_landscape-1188022.jpg!s`,
    },
    {
        word1: `country of residence`,
        translation1: `kraj zamieszkania`,
        level: `advanced`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/ea/58/european_union_europe_travel_poland_map_country_borders_focus_poland-1223913.jpg!s`,
    },
    {
        word1: `distinguishing features`,
        translation1: `znaki szczególne`,
        level: `advanced`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/18/d9/photo-1404118.jpg!s`,
    },
    {
        word1: `ethnic origin`,
        translation1: `pochodzenie etniczne`,
        level: `advanced`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/56/c1/talented_people_asia_bam_the_bath_cambodia_waterfall_cool_culture-1028448.jpg!s`,
    },
    {
        word1: `next of kin`,
        translation1: `najbliższy krewny`,
        level: `advanced`,
        type: `dane osobowe`,
        image: `https://c.pxhere.com/photos/5b/ff/child_children_girl_happy_people_group_female_cute-715391.jpg!s`,
    },
];

export default words1_PersonalData