const words1_PersonalData = [
    {
        word: `address`,
        translation: `adres`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `age`,
        translation: `wiek`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `date od birth`,
        translation: `data urodzenia`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `divorced`,
        translation: `rozwiedziony`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `female`,
        translation: `kobieta`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `first name`,
        translation: `imię`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `gender`,
        translation: `płeć`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `male`,
        translation: `mężczyzna`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `marital status`,
        translation: `stan cywilny`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `married`,
        translation: `żonaty`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `nationality`,
        translation: `narodowość`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `occupation`,
        translation: `zawód`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `single`,
        translation: `stanu wolnego`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `surname`,
        translation: `nazwisko`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `widowed`,
        translation: `owdowiały`,
        level: `basic`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `country od residence`,
        translation: `kraj zamieszkania`,
        level: `advanced`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `distinguishing features`,
        translation: `znaki szczególne`,
        level: `advanced`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `ethnic origin`,
        translation: `pochodzenie etniczne`,
        level: `advanced`,
        type: `personal data`,
        image: `url`,
    },
    {
        word: `next of kin`,
        translation: `najbliższy krewny`,
        level: `advanced`,
        type: `personal data`,
        image: `url`,
    },
];

export default words1_PersonalData