const words2_Apperance = [
	{
		word: `attractive`,
		translation: `atrakcyjny`, 
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `url`,
	},
	{
		word: `unattractive`,
		translation: `nieatrakcyjny`, 
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `url`,
	},
	{
		word: `beautiful`,
		translation: `piękny`, 
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `url`,
	},
	{
		word: `fit`,
		translation: `sprawny`,
		translation2: `w dobrej formie`, 
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `url`,
	},
	{
		word: `good-looking`,
		translation: `przystojny`,
		translation2: `ładny`,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `url`,
	},
	{
		word: `handsome`,
		translation: `przystojny`,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `url`,
	},
	{
		word: `plain`,
		translation: `pospoliny`,
		translation2: `nieatrakcyjny`,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `url`,
	},
	{
		word: `pretty`,
		translation: `ładny`,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `url`,
	},
	{
		word: `ugly`,
		translation: `brzydki`,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `url`,
	},
	// // // // // -zwroty związane z wygladem
	{
		word: `cut down on`,
		translation: `ograniczać (ilość czegoś)`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `url`,
	},
	{
		word: `go for (darker colours)`,
		translation: `wybierać`,
		translation2: `sięgać po (ciemniejsze kolory)`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `url`,
	},
	{
		word: `paint your nails`,
		translation: `malować paznokcie`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `url`,
	},
	{
		word: `put on weight`,
		translation: `przybierać na wadze`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `url`,
	},
	{
		word: `lose weight`,
		translation: `tracić na wadze`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `url`,
	},
	{
		word: `straighten`,
		translation: `prostować (włosy)`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `url`,
	},
	{
		word: `take up a hobby`,
		translation: `zacząć uprawiać hobby`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `url`,
	},
	{
		word: `take up a sport`,
		translation: `zacząć uprawiać sport`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `url`,
	},
	// // // // // -budowa ciała
	{
		word: `fat`,
		translation: `gruby`,
		level: `basic`,
		type: `budowa ciała`,
		image: `url`,
	},
	{
		word: `muscular`,
		translation: `umięśniony`,
		level: `basic`,
		type: `budowa ciała`,
		image: `url`,
	},
	{
		word: `obese`,
		translation: `otyły`,
		level: `basic`,
		type: `budowa ciała`,
		image: `url`,
	},
	{
		word: `overweight`,
		translation: `z nadwagą`,
		level: `basic`,
		type: `budowa ciała`,
		image: `url`,
	},
	{
		word: `underweight`,
		translation: `z niedowagą`,
		level: `basic`,
		type: `budowa ciała`,
		image: `url`,
	},
	{
		word: `słplump`,
		translation: `puszysty`,
		translation2: `pulchny`,
		level: `basic`,
		type: `budowa ciała`,
		image: `url`,
	},
	{
		word: `skinny`,
		translation: `chudy`,
		level: `basic`,
		type: `budowa ciała`,
		image: `url`,
	},
	{
		word: `slim`,
		translation: `szczupły`,
		level: `basic`,
		type: `budowa ciała`,
		image: `url`,
	},
	{
		word: `well-built`,
		translation: `dobrze zbudowany`,
		level: `basic`,
		type: `budowa ciała`,
		image: `url`,
	},
	// // // -extended
	{
		word: `lanky`,
		translation: `tyczkowaty`,
		translation2: `wysoki i chudy`,
		level: `extended`,
		type: `budowa ciała`,
		image: `url`,
	},
	{
		word: `stocky`,
		translation: `krępy`,
		level: `extended`,
		type: `budowa ciała`,
		image: `url`,
	},
	// // // // // -włosy
	{
		word: `bald`,
		translation: `łysy`,
		level: `basic`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `blond`,
		translation: `blond`,
		level: `basic`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `curly`,
		translation: `kręcone`,
		level: `basic`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `dark`,
		translation: `ciemne`,
		level: `basic`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `dyed`,
		translation: `farbowane`,
		level: `basic`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `red`,
		translation: `rude`,
		level: `basic`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `shoulder-length`,
		translation: `do ramion`,
		level: `basic`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `straight`,
		translation: `proste`,
		level: `basic`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `wavy`,
		translation: `falujące`,
		level: `basic`,
		type: `włosy`,
		image: `url`,
	},
	// // // -extended
	{
		word: `auburn`,
		translation: `kasztanowe`,
		level: `extended`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `fine`,
		translation: `cienkie`,
		translation2: `rzadkie`,
		level: `extended`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `thick`,
		translation: `gęste`,
		level: `extended`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `fringe`,
		translation: `grzywka`,
		level: `extended`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `have a centre parting`,
		translation: `mieć przedziałek na środku`,
		level: `extended`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `have a side parting`,
		translation: `mieć przedziałek z boku`,
		level: `extended`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `ponytail`,
		translation: `kitka`,
		translation2: `koński ogon`,
		level: `extended`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `receding włosyline`,
		translation: `włosy rzednące na skroniach`,
		level: `extended`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `wear your hair loose`,
		translation: `nosić rozpuszczone włosy`,
		level: `extended`,
		type: `włosy`,
		image: `url`,
	},
	{
		word: `wear your hair up`,
		translation: `nosić spięte włosy`,
		level: `extended`,
		type: `włosy`,
		image: `url`,
	},
	// // // // // -cechy szczególne
	{
		word: `słówko`,
		translation: `tłumaczenie`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `beard`,
		translation: `broda`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `freckles`,
		translation: `piegi`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `moustache`,
		translation: `wąsy`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `pale complexion`,
		translation: `blada cera`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `tanned complexion`,
		translation: `opalona cera`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `dark complexion`,
		translation: `ciemna cera`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `pierced ears`,
		translation: `przekute uszy`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `scar`,
		translation: `blizna`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `spotty`,
		translation: `pryszczaty`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `tattoo`,
		translation: `tatuaż`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `wrinkles`,
		translation: `zmarszczki`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `url`,
	},
	// // // -extended
	{
		word: `birthmark`,
		translation: `znamię`,
		level: `extended`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `clean-shaven`,
		translation: `gładko ogolony`,
		level: `extended`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `clear skin`,
		translation: `gładka skóra`,
		level: `extended`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `double chin`,
		translation: `podwójny podbródek`,
		level: `extended`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `high cheekbones`,
		translation: `wystające kości policzkowe`,
		level: `extended`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `high forehead`,
		translation: `wysokie czoło`,
		level: `extended`,
		type: `cechy szczególne`,
		image: `url`,
	},
	{
		word: `piercing blue eyes`,
		translation: `przenikliwe niebieskie oczy`,
		level: `extended`,
		type: `cechy szczególne`,
		image: `url`,
	}
]

export default words2_Apperance