const words2_Apperance = [
	{
		word: `attractive`,
		translation: `atrakcyjny`,
		female: true,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `https://c.pxhere.com/photos/66/ad/beautiful_girl_smiling_female_young_woman_portrait_face-642855.jpg!s`,
	},
	{
		word: `unattractive`,
		translation: `nieatrakcyjny`,
		female: true,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `https://c.pxhere.com/photos/68/39/hat_fashion_style_happy_man_hipster_adult_vintage-764418.jpg!s`,
	},
	{
		word: `beautiful`,
		translation: `piękny`,
		female: true,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `https://c.pxhere.com/images/b1/a7/8132b4967bd5d00a45c33e9faa2f-1428703.jpg!s`,
	},
	{
		word: `fit`,
		translation: `sprawny`,
		translation2: `w dobrej formie`,
		female: true,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `https://c.pxhere.com/photos/63/3e/blur_person_lifestyle_summer_male_urban_gym_gymnastics-1375404.jpg!s`,
	},
	{
		word: `good-looking`,
		translation: `przystojny`,
		translation2: `ładny`,
		female: true,
		t1: false,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `https://c.pxhere.com/photos/21/b1/man_handsome_male_young_model_attractive_guy_fashion-703056.jpg!s`,
	},
	{
		word: `handsome`,
		translation: `przystojny`,
		female: true,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `https://c.pxhere.com/photos/3c/61/nature_sky_man_portrait_look_for_sun_lighy_beard_young-478741.jpg!s`,
	},
	{
		word: `plain`,
		translation: `pospolity`,
		translation2: `nieatrakcyjny`,
		female: true,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `https://c.pxhere.com/photos/43/dd/selfportrait_me_sony_smooth_selfie_strobes_2470mm_a700-327253.jpg!s`,
	},
	{
		word: `pretty`,
		translation: `ładny`,
		female: true,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `https://c.pxhere.com/images/aa/c1/424a8dd500465950614ce58fbaa9-1448331.jpg!s`,
	},
	{
		word: `ugly`,
		translation: `brzydki`,
		female: true,
		level: `basic`,
		type: `wygląd zewnętrzny`,
		image: `https://c.pxhere.com/photos/e1/3d/vulture_scavengers_bird_of_prey_plumage_animal_animal_world_nature_spring-757813.jpg!s`,
	},
	// // // // // -zwroty związane z wygladem
	{
		word: `cut down on`,
		translation: `ograniczać (ilość czegoś)`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `https://c.pxhere.com/photos/73/99/diet_food_healthy_nutrition_health_dieting_lifestyle_eating-951025.jpg!s`,
	},
	{
		word: `go for (darker colours)`,
		translation: `wybierać`,
		translation2: `sięgać po (ciemniejsze kolory)`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `https://c.pxhere.com/photos/a2/97/the_strategy_win_champion_the_championship_the_winner_of_the_prevx_chess_game-1056749.jpg!s`,
	},
	{
		word: `paint your nails`,
		translation: `malować paznokcie`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `https://c.pxhere.com/photos/72/36/gel_nails_nail_art_model_manicure_young_woman_hand_beauty-1266846.jpg!s`,
	},
	{
		word: `put on weight`,
		translation: `przybierać na wadze`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `https://c.pxhere.com/photos/32/d8/belly_body_calories_diet_exercise_fat_female_fit-1159455.jpg!s`,
	},
	{
		word: `lose weight`,
		translation: `tracić na wadze`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `https://c.pxhere.com/photos/05/08/belly_body_clothes_diet_female_figure_fit_fitness-1159337.jpg!s`,
	},
	{
		word: `straighten (hair)`,
		translation: `prostować (włosy)`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `https://c.pxhere.com/images/4b/e0/98d5c7499bc0b17ae17ab22e866d-1436311.jpg!d`,
	},
	{
		word: `take up a hobby`,
		translation: `zacząć uprawiać hobby`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `https://c.pxhere.com/photos/da/9f/adult_amusement_blur_close_up_computer_connection_distraction_entertainment-1510193.jpg!s`,
	},
	{
		word: `take up a sport`,
		translation: `zacząć uprawiać sport`,
		level: `basic`,
		type: `zwroty związane z wygladem`,
		image: `https://c.pxhere.com/photos/8f/74/men_trail_running_trail_run_fitness_nature_runner_sport-552598.jpg!d`,
	},
	// // // // // -budowa ciała
	{
		word: `fat`,
		translation: `gruby`,
		female: true,
		level: `basic`,
		type: `budowa ciała`,
		image: `https://c.pxhere.com/photos/23/6b/confrontation_fat_fight_men_emotion-1226898.jpg!s`,
	},
	{
		word: `muscular`,
		translation: `umięśniony`,
		female: true,
		level: `basic`,
		type: `budowa ciała`,
		image: `https://c.pxhere.com/photos/af/d1/bodybuilder_weight_training_stress_muscular_athlete_gym_man-755456.jpg!s`,
	},
	{
		word: `obese`,
		translation: `otyły`,
		female: true,
		level: `basic`,
		type: `budowa ciała`,
		image: `https://c.pxhere.com/photos/c3/e0/obesity_fat_nutritionist_city_people_metropolis_steps-682829.jpg!d`,
	},
	{
		word: `overweight`,
		translation: `z nadwagą`,
		level: `basic`,
		type: `budowa ciała`,
		image: `https://c.pxhere.com/photos/a8/e4/diet_fat_health_weight_healthy_loss_nutrition_dieting-950856.jpg!s`,
	},
	{
		word: `underweight`,
		translation: `z niedowagą`,
		level: `basic`,
		type: `budowa ciała`,
		image: `https://c.pxhere.com/photos/dc/11/ruler_medicine_diet_centimeter_healthcare_health_measure_measurement-1265111.jpg!s`,
	},
	{
		word: `plump`,
		translation: `puszysty`,
		translation2: `pulchny`,
		female: true,
		level: `basic`,
		type: `budowa ciała`,
		image: `https://c.pxhere.com/photos/e9/ef/angel_ballet_ladies_plump_funny_sale_chubby_sexy-729346.jpg!s`,
	},
	{
		word: `skinny`,
		translation: `chudy`,
		female: true,
		level: `basic`,
		type: `budowa ciała`,
		image: `https://c.pxhere.com/photos/37/7f/girl_woman_beautiful_long_hair_brown_wavy_posing-810135.jpg!s`,
	},
	{
		word: `slim`,
		translation: `szczupły`,
		female: true,
		level: `basic`,
		type: `budowa ciała`,
		image: `https://c.pxhere.com/photos/ee/4a/girl_woman_beautiful_long_hair_brown_blonde_wavy-810118.jpg!s`,
	},
	{
		word: `well-built`,
		translation: `dobrze zbudowany`,
		female: true,
		level: `basic`,
		type: `budowa ciała`,
		image: `https://c.pxhere.com/photos/a3/91/naked_upper_body_fit_lifestyle_athlete_person_men's_model-1173326.jpg!s`,
	},
	// // // -extended
	{
		word: `lanky`,
		translation: `tyczkowaty`,
		translation2: `wysoki i chudy`,
		female: true,
		level: `extended`,
		type: `budowa ciała`,
		image: `https://c.pxhere.com/images/21/0d/61990cebd2aff5c2b9ddab9b484e-1418434.jpg!s`,
	},
	{
		word: `stocky`,
		translation: `krępy`,
		female: true,
		level: `extended`,
		type: `budowa ciała`,
		image: `https://c.pxhere.com/photos/ea/ba/hulk_marvel_superhero_figure_one_power_strongly-768956.jpg!s`,
	},
	// // // // // -włosy
	{
		word: `bald`,
		translation: `łysy`,
		female: true,
		level: `basic`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/6c/a0/adult_bald_beard_corporate_designer_suit_facial_expression_fashion_laughing-1169779.jpg!s`,
	},
	{
		word: `blond`,
		translation: `blond`,
		level: `basic`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/35/e8/beauty_barbie_pretty_doll_charming_children_toys_girl_face-645142.jpg!s`,
	},
	{
		word: `curly`,
		translation: `kręcone`,
		level: `basic`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/f8/aa/beauty_outdoor_woman_face_portrait_young_curly_hair_smile-1293204.jpg!s`,
	},
	{
		word: `dark`,
		translation: `ciemne`,
		level: `basic`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/9c/2b/girl_woman_female_lady_attractive_beautiful_dark_hair_brown_hair-722593.jpg!s`,
	},
	{
		word: `dyed`,
		translation: `farbowane`,
		level: `basic`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/02/4d/wig_hair_anime_cosplay_teen-1388315.jpg!s`,
	},
	{
		word: `red`,
		translation: `rude`,
		level: `basic`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/5a/00/woman_trick_curly_hair_face_hair_portrait_blue_hair_make_up-816448.jpg!s`,
	},
	{
		word: `shoulder-length`,
		translation: `do ramion`,
		level: `basic`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/c0/7c/cloth_scarf_colors_clothing_dress_poor_bangles_hair_lipstick-626143.jpg!s`,
	},
	{
		word: `straight`,
		translation: `proste`,
		level: `basic`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/12/90/blur_casual_close_up_earrings_elegant_eyes_fashion_focus-986494.jpg!s`,
	},
	{
		word: `wavy`,
		translation: `falujące`,
		level: `basic`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/35/4d/sitting_stairs_girl_woman_smile_happy_scarf_jeans-639774.jpg!s`,
	},
	// // // -extended
	{
		word: `auburn`,
		translation: `kasztanowe`,
		level: `extended`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/18/3e/chestnut_autumn_spur_open_open_chestnut_shell_brown_plant-485043.jpg!s`,
	},
	{
		word: `fine`,
		translation: `cienkie`,
		translation2: `rzadkie`,
		level: `extended`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/15/87/man_male_adult_person_caucasian_portrait_businessman_people-599421.jpg!s`,
	},
	{
		word: `thick`,
		translation: `gęste`,
		level: `extended`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/c6/e8/beard_black_boy_brown_bush_bushy_caveman_chin-819357.jpg!s`,
	},
	{
		word: `fringe`,
		translation: `grzywka`,
		level: `extended`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/97/cb/hair_style_layers_woman_female_fashion_young_face-1234336.jpg!s`,
	},
	{
		word: `have a centre parting`,
		translation: `mieć przedziałek na środku`,
		level: `extended`,
		type: `włosy`,
		image: `https://c.pxhere.com/images/d8/8c/e73b861fceac6f735b45461a85ce-1432763.jpg!s`,
	},
	{
		word: `have a side parting`,
		translation: `mieć przedziałek z boku`,
		level: `extended`,
		type: `włosy`,
		image: `https://c.pxhere.com/images/a3/51/2d0c446c3f063c360d91511a7943-1436307.jpg!s`,
	},
	{
		word: `ponytail`,
		translation: `kitka`,
		translation2: `koński ogon`,
		level: `extended`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/d7/49/horse_eye_bai_color_horse_head_ponytail_relationship_animal_man-1135867.jpg!s`,
	},
	{
		word: `receding line`,
		translation: `włosy rzednące na skroniach`,
		level: `extended`,
		type: `włosy`,
		image: `https://c.pxhere.com/photos/a2/a4/adult_businesman_business_confidence_daylight_facial_expression_fine_looking_leadership-965066.jpg!s`,
	},
	{
		word: `wear your hair loose`,
		translation: `nosić rozpuszczone włosy`,
		level: `extended`,
		type: `włosy`,
		image: `https://c.pxhere.com/images/38/fe/762e69512e53d94f4b4711f60d0e-1419055.png!s`,
	},
	{
		word: `wear your hair up`,
		translation: `nosić spięte włosy`,
		level: `extended`,
		type: `włosy`,
		image: `https://c.pxhere.com/images/f8/65/c06a8c1c150f5c184f16c82c0724-1454581.jpg!s`,
	},
	// // // // // -cechy szczególne
	{
		word: `beard`,
		translation: `broda`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/photos/d0/64/beard_man_hair_male_eye-41432.jpg!s`,
	},
	{
		word: `freckles`,
		translation: `piegi`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/photos/ad/f3/brother_sister_red_hair_freckles_kiss_love_pair_smile-815309.jpg!s`,
	},
	{
		word: `moustache`,
		translation: `wąsy`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/photos/ba/89/cigar_smoking_cigar_cigarette_smoking_man_male_black_and_white_funny-1101377.jpg!s`,
	},
	{
		word: `pale complexion`,
		translation: `blada cera`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/images/7a/0f/166894325cded9f98991a5cc5996-1432789.jpg!s`,
	},
	{
		word: `tanned complexion`,
		translation: `opalona cera`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/photos/62/8c/butt_po_tanning_women_tanned_sexy_hot_attractive-947551.jpg!s`,
	},
	{
		word: `dark complexion`,
		translation: `ciemna cera`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/photos/b5/1d/children_togo_black_negro_african_infants_faces_smile-1103846.jpg!s`,
	},
	{
		word: `pierced ears`,
		translation: `przekute uszy`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/photos/e1/bc/head_unusual_girl_people_side_view_ear_lobe_pierced-1261353.jpg!s`,
	},
	{
		word: `scar`,
		translation: `blizna`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/photos/58/76/scar_wound_arm_shoulder_skin_human_person-1145411.jpg!s`,
	},
	{
		word: `spotty`,
		translation: `pryszczaty`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/photos/21/86/dalmatians_dog_animal_head_animal_portrait_dog_breed_black_and_white_dog_head-730892.jpg!s`,
	},
	{
		word: `tattoo`,
		translation: `tatuaż`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/photos/c8/0e/tattoo_foot_skin_black_and_white_stars_black_white_symbol-1332780.jpg!s`,
	},
	{
		word: `wrinkles`,
		translation: `zmarszczki`,
		level: `basic`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/photos/69/4a/elephant_trunk_skin_care_big_african_endangered_huge_gray-571528.jpg!s`,
	},
	// // // -extended
	{
		word: `birthmark`,
		translation: `znamię`,
		level: `extended`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/images/68/73/06e8c782ede61a1580c0327d581e-1460827.jpg!s`,
	},
	{
		word: `clean-shaven`,
		translation: `gładko ogolony`,
		female: true,
		level: `extended`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/images/03/00/b0bbe11318981c71b8ec66b7f4f5-1437155.jpg!s`,
	},
	{
		word: `clear skin`,
		translation: `gładka skóra`,
		level: `extended`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/images/d7/dc/835f6427b9d22ee030874eb5b64e-1445991.jpg!s`,
	},
	{
		word: `double chin`,
		translation: `podwójny podbródek`,
		level: `extended`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/images/ae/e5/f11b97db5eff215e63992f27732c-1418418.jpg!s`,
	},
	{
		word: `high cheekbones`,
		translation: `wystające kości policzkowe`,
		level: `extended`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/photos/d0/21/pentax645z_645z_priolite_portrait_beautifulwoman_beautifulblackwoman_blackandwhite_beauty-367845.jpg!s`,
	},
	{
		word: `high forehead`,
		translation: `wysokie czoło`,
		level: `extended`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/photos/a2/97/man_face_hand_keep_forehead_headache_high_blood_pressure_red_face-910351.jpg!s`,
	},
	{
		word: `piercing blue eyes`,
		translation: `przenikliwe niebieskie oczy`,
		level: `extended`,
		type: `cechy szczególne`,
		image: `https://c.pxhere.com/photos/35/23/girl_blue_eyes_seductive_flowers_blonde_beauty_princess-1043857.jpg!s`,
	}
]

export default words2_Apperance