const words3_Clothes = [
	{
		word: `blouse`,
		translation: `bluzka`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `boots`,
		translation: `wysokie buty`, 
		translation2: `kozaki`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `bra`,
		translation: `biustonosz`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `casual`,
		translation: `codzienny`, 
		translation2: `swobodny`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `coat`,
		translation: `płaszcz`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `dress`,
		translation: `sukienka`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `fashionable`,
		word2: `trendy`,
		translation: `modny`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `fleece`,
		translation: `bluza polarowa`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `gloves`,
		translation: `rękawiczki`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `hat`,
		translation: `kapelusz`, 
		translation2: `czapka`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `jacket`,
		translation: `kurtka`, 
		translation2: `marynarka`, 
		translation3: `żakiet`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `jumper`,
		translation: `sweter`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `old-fashioned`,
		translation: `staromodny`, 
		translation2: `staroświecki`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `pyjamas`,
		translation: `piżama`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `sandals`,
		translation: `sandały`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `shirt`,
		translation: `koszula`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `shoes`,
		translation: `buty`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `shorts`,
		translation: `szorty`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `skirt`,
		translation: `spódnica`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `smart`,
		translation: `elegancki`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `socks`,
		translation: `skarpety`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `suit`,
		translation: `garnitur`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `sweatshirt`,
		translation: `bluza sportowa`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `tracksuit`,
		translation: `dres`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `trainers`,
		translation: `obuwie sportowe`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `throusers`,
		translation: `spodnie`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `underwear`,
		translation: `bielizna`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `waistcoat`,
		translation: `kamizelka`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `wear`,
		translation: `nosić`, 
		translation2: `mieć na sobie`, 
		level: `basic`,
		type: `ubrania`,
		image: `url`,
	},
	// // // -extended
	{
		word: `ballgown`,
		translation: `suknia balowa`, 
		level: `extended`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `boat-necked`,
		translation: `z szerokim dekoltem (bluzka, sweter)`, 
		level: `extended`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `cardigan`,
		translation: `rozpinany sweter`, 
		level: `extended`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `colaar`,
		translation: `kołnieżyk`, 
		level: `extended`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `cuffs`,
		translation: `mankiety`, 
		level: `extended`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `dressing gown`,
		translation: `szlafrok`, 
		level: `extended`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `hight heels`,
		translation: `wysokie obcasy`, 
		level: `extended`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `hoodie`,
		translation: `bluza z kapturem`, 
		level: `extended`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `long-sleeved`,
		translation: `z długim rękawem (koszula)`, 
		level: `extended`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `short-sleeved`,
		translation: `z krótkim rękawem (koszula)`, 
		level: `extended`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `strapless top`,
		translation: `bluzka bez ramiączek`, 
		level: `extended`,
		type: `ubrania`,
		image: `url`,
	},
	{
		word: `V-neck`,
		translation: `dekolt w szpic`, 
		level: `extended`,
		type: `ubrania`,
		image: `url`,
	},
	// // // // // -dodatki
	{
		word: `belt`,
		translation: `pasek`, 
		level: `basic`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `button`,
		translation: `guzik`, 
		level: `basic`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `cap`,
		translation: `czapka z daszkiem`, 
		level: `basic`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `earrings`,
		translation: `kolczyki`, 
		level: `basic`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `glasses`,
		translation: `okulary`, 
		level: `basic`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `handbag`,
		word2: `bag`,
		translation: `torebka`, 
		level: `basic`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `jewellery`,
		translation: `biżuteria`, 
		level: `basic`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `necklace`,
		translation: `naszyjnik`, 
		level: `basic`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `ring`,
		translation: `pierścionek`, 
		level: `basic`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `scarf`,
		translation: `szalik`, 
		level: `basic`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `tie`,
		translation: `krawat`, 
		level: `basic`,
		type: `dodatki`,
		image: `url`,
	},
	// // // -extended
	{
		word: `bracelet`,
		translation: `bransoletka`, 
		level: `extended`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `brooch`,
		translation: `broszka`, 
		level: `extended`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `shoe laces`,
		translation: `sznurówki`, 
		level: `extended`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `slippers`,
		translation: `kapcie`, 
		level: `extended`,
		type: `dodatki`,
		image: `url`,
	},
	{
		word: `zip-up`,
		translation: `na zamek`, 
		level: `extended`,
		type: `dodatki`,
		image: `url`,
	},
	// // // // // -wzory i materiały
	{
		word: `checked`,
		translation: `w kratę`, 
		level: `basic`,
		type: `wzory i materiały`,
		image: `url`,
	},
	{
		word: `cotton`,
		translation: `bawełna`, 
		level: `basic`,
		type: `wzory i materiały`,
		image: `url`,
	},
	{
		word: `gold`,
		translation: `złoto`, 
		level: `basic`,
		type: `wzory i materiały`,
		image: `url`,
	},
	{
		word: `leather`,
		translation: `skóra`, 
		translation2: `skórzany`, 
		level: `basic`,
		type: `wzory i materiały`,
		image: `url`,
	},
	{
		word: `plain`,
		translation: `gładki`, 
		level: `basic`,
		type: `wzory i materiały`,
		image: `url`,
	},
	{
		word: `silk`,
		translation: `jedwab`, 
		level: `basic`,
		type: `wzory i materiały`,
		image: `url`,
	},
	{
		word: `silver`,
		translation: `srebro`, 
		translation2: `srebrny`, 
		level: `basic`,
		type: `wzory i materiały`,
		image: `url`,
	},
	{
		word: `spotted`,
		translation: `w kropki`, 
		level: `basic`,
		type: `wzory i materiały`,
		image: `url`,
	},
	{
		word: `striped`,
		translation: `w paski`, 
		level: `basic`,
		type: `wzory i materiały`,
		image: `url`,
	},
	{
		word: `tartan`,
		translation: `w szkodzką kratę`, 
		level: `basic`,
		type: `wzory i materiały`,
		image: `url`,
	},
	{
		word: `wool`,
		translation: `wełna`, 
		level: `basic`,
		type: `wzory i materiały`,
		image: `url`,
	},
	// // // -extended
	{
		word: `elactic`,
		translation: `elastyczny`, 
		level: `extended`,
		type: `wzory i materiały`,
		image: `url`,
	},
	{
		word: `fur`,
		translation: `futro`, 
		translation2: `futrzany`, 
		level: `extended`,
		type: `wzory i materiały`,
		image: `url`,
	},
	{
		word: `lacy`,
		translation: `koronkowy`, 
		level: `extended`,
		type: `wzory i materiały`,
		image: `url`,
	},
	{
		word: `lined`,
		translation: `na podszewce`, 
		translation2: `ocieplany`, 
		level: `extended`,
		type: `wzory i materiały`,
		image: `url`,
	}
]

export default words3_Clothes