const words4_FeaturesOfCharacters = [
	{
		word: `aggressive`,
		translation: `agresywny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `ambitious`,
		translation: `ambitny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `bad-tempered`,
		translation: `wybuchowy`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `big-headed`,
		translation: `zarozumiały`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `brave`,
		translation: `odważny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `careful`,
		translation: `ostrożny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `careless`,
		translation: `nieostrożny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `caring`,
		translation: `troskliwy`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `cheerful`,
		translation: `radosny`, 
		translation2: `pogodny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `clever`,
		translation: `mądry`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `confident`,
		translation: `pewny siebie`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `overconfident`,
		translation: `zbyt pewny siebie`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `drama queen`,
		translation: `panikarz`, 
		translation2: `osoba nadmiernie dramatyzująca`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `easygoing`,
		translation: `wyluzowany`, 
		translation2: `opanowany`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `energetic`,
		translation: `energiczny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `extrovert`,
		translation: `ekstrawertyk`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `friendly`,
		translation: `przyjacielski`, 
		translation2: `miły`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `fun-loving`,
		translation: `lubiacy dobrą zabawę`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `generous`,
		translation: `szczodry`, 
		translation2: `hojny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `gentle`,
		translation: `delikatny`, 
		translation2: `łagodny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `hard-working`,
		translation: `pracowity`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `helpful`,
		translation: `uczynny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `unhelpful`,
		translation: `nieskory do pomocy`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `honest`,
		translation: `uczciwy`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `dishonest`,
		translation: `nieuczciwy`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `imaginative`,
		translation: `pomysłowy`, 
		translation2: `kreatywny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `unimaginative`,
		translation: `bez wyobraźni`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `independent`,
		translation: `niezależny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `intelligent`,
		translation: `inteligentny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `introvert`,
		translation: `introwertyk`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `lazy`,
		translation: `leniwy`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `mean`,
		translation: `skąpy`, 
		translation2: `złośliwy`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `messy`,
		translation: `bałaganiarski`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `nasty`,
		translation: `złośliwy`, 
		translation2: `wstrętny`, 
		translation3: `nieprzyjemny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `nice`,
		translation: `miły`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `open`,
		translation: `otwarty`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `optimistic`,
		translation: `optymistyczny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `pessimistic`,
		translation: `pesymistyczny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `outgoing`,
		translation: `otwarty`, 
		translation2: `towarzyski`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `patient`,
		translation: `cierpliwy`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `impatient`,
		translation: `niecierpliwy`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `polite`,
		translation: `uprzejmy`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `quiet`,
		translation: `cichy`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `reliable`,
		translation: `solidny`, 
		translation2: `niezawodny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `unreliable`,
		translation: `niesolidny`, 
		translation2: `zawodny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},

	{
		word: `responsible`,
		translation: `odpowiedzialny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `rude`,
		translation: `niegrzeczny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `selfish`,
		translation: `samolubny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `unselfish`,
		translation: `bezinteresowny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `serious`,
		translation: `poważny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `shy`,
		translation: `nieśmiały`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `silly`,
		translation: `niemądry`,
		translation2: `głupkowaty`,
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `sociable`,
		translation: `towarzyski`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `unsociable`,
		translation: `nietowarzyski`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `talkative`,
		translation: `gadatliwy`, 
		translation2: `rozmowny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `tidy`,
		translation: `schludny`, 
		translation2: `porządny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `untidy`,
		translation: `niechlujny`, 
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	// // // -extended
	{
		word: `bossy`,
		translation: `apodyktyczny`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `cowardly`,
		translation: `tchórzliwy`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `eccentric`,
		translation: `ekscentryczny`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `materialistic`,
		translation: `materialistyczny`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `modest`,
		translation: `skromny`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `moody`,
		translation: `kapryśny`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `odd`,
		translation: `dziwny`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `oddball`,
		translation: `dziwak`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `sensitive`,
		translation: `wrażliwy`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `sincere`,
		translation: `szczery`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `sympathetic`,
		translation: `życzliwy`, 
		translation2: `współczujący`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `weird`,
		translation: `dziwny`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `weirdo`,
		translation: `dziwak`,
		translation2: `dziwaczka`,
		translation3: `dziwadło`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `whizzkid`,
		translation: `cudowne dziecko`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `withdrawn`,
		translation: `zamknięty w sobie`, 
		level: `extended`,
		type: `cechy charakteru`,
		image: `url`,
	},
];

export default words4_FeaturesOfCharacters