const words4_FeaturesOfCharacters = [
	{
		word: `aggressive`,
		translation: `agresywny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/2f/d2/dog_attack_aggressive_anger_bite_angry_shepherd_service-863621.jpg!s`,
	},
	{
		word: `ambitious`,
		translation: `ambitny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/db/bf/girl_bagpipes_bag_pipe_effort_exhausting_ambitious_competition_audition-712716.jpg!s`,
	},
	{
		word: `bad-tempered`,
		translation: `wybuchowy`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/13/d4/man_male_angry_face_expression_angry_man_adult_young-698401.jpg!s`,
	},
	{
		word: `big-headed`,
		translation: `zarozumiały`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/72/5a/business_man_beautiful_man_business_business_men_man_young_male_businessman-625568.jpg!s`,
	},
	{
		word: `brave`,
		translation: `odważny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/e6/c8/superman_toy_lego_hero_super_fun_cute_costume-671170.jpg!s`,
	},
	{
		word: `careful`,
		translation: `ostrożny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/e3/27/girl_sea_vacation_young_holiday_fun_leisure_careful-669007.jpg!s`,
	},
	{
		word: `careless`,
		translation: `nieostrożny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/8d/f4/bubble_gum_shoes_glue_dirt_bubblegum_sticky_stick_stuck-1094517.jpg!s`,
	},
	{
		word: `caring`,
		translation: `troskliwy`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/66/db/hospice_caring_nursing_elderly_care_patient_nurse_elder_care-1215734.jpg!s`,
	},
	{
		word: `cheerful`,
		translation: `radosny`,
		translation2: `pogodny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/80/93/girl_smiling_female_woman_young_attractive_portrait_happiness-868153.jpg!s`,
	},
	{
		word: `clever`,
		translation: `mądry`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/1a/1e/the_strategy_win_champion_the_championship_the_winner_of_the_prevx_chess_game-1056740.jpg!s`,
	},
	{
		word: `confident`,
		translation: `pewny siebie`,
		female: `first`,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/33/18/handsome_guy_businessman_guy_business_handsome_male_young_person-704194.jpg!s`,
	},
	{
		word: `overconfident`,
		translation: `zbyt pewny siebie`,
		female: `second`,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/c0/36/man_cigarette_smoke_male_addiction_person_young_adult-784156.jpg!s`,
	},
	{
		word: `drama queen`,
		translation: `panikarz`,
		translation2: `osoba nadmiernie dramatyzująca`,
		female: `without-t1`,
		letters: 2,
		level: `basic`,
		type: `cechy charakteru`,
		image: `url`,
	},
	{
		word: `easygoing`,
		translation: `wyluzowany`,
		translation2: `opanowany`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/09/21/person_young_woman_female_smoking_cigarette_adult_attractive-879294.jpg!s`,
	},
	{
		word: `energetic`,
		translation: `energiczny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/b1/ac/minions_talking_smile_conversation_happy_communication_cute_despicable_me-1100997.jpg!s`,
	},
	{
		word: `extrovert`,
		translation: `ekstrawertyk`,
		letters: `-czka`,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/75/9f/workplace_team_business_meeting_business_people_business_teamwork_office_people-559565.jpg!s`,
	},
	{
		word: `friendly`,
		translation: `przyjacielski`,
		translation2: `miły`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/7e/77/friend_woman_person_man_talking-180040.jpg!s`,
	},
	{
		word: `fun-loving`,
		translation: `lubiacy dobrą zabawę`,
		female: `first`,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/images/f2/5f/514830679e627e44b6490dcca049-1435765.jpg!s`,
	},
	{
		word: `generous`,
		translation: `szczodry`,
		translation2: `hojny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/1f/50/presents_packages_wrapped_bows_ribbons_gifts_surprise_generous-672520.jpg!s`,
	},
	{
		word: `gentle`,
		translation: `delikatny`,
		translation2: `łagodny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/dd/c2/portrait_woman_girl_blond_hair_long_hair_blonde_hair_female-1221096.jpg!s`,
	},
	{
		word: `hard-working`,
		translation: `pracowity`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/c1/ab/bee_flower_yellow_sky_blue_composites_blossom_bloom-1415664.jpg!s`,
	},
	{
		word: `helpful`,
		translation: `uczynny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/84/0c/hospice_caring_for_elder_help_elderly_patient_nurse_caregiver_support-1361992.jpg!s`,
	},
	{
		word: `unhelpful`,
		translation: `nieskory do pomocy`,
		female: `first`,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/7c/1f/child_girl_view_evil_offended_blond_face_nature-895742.jpg!s`,
	},
	{
		word: `honest`,
		translation: `uczciwy`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/images/2f/cd/2835963fc1ada9e6dbfd6809823f-1433391.jpg!s`,
	},
	{
		word: `dishonest`,
		translation: `nieuczciwy`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/a7/71/taxes_tax_evasion_police_handcuffs_scam_tax_consultant_finance_money-1294892.jpg!s`,
	},
	{
		word: `imaginative`,
		translation: `pomysłowy`,
		translation2: `kreatywny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/f5/a0/guitarist_girl_music_artist_band_musician_song_photomontage_digital_art-1286965.jpg!s`,
	},
	{
		word: `unimaginative`,
		translation: `bez wyobraźni`,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/ab/2f/girl_teen_caf_near_the_window_window_smartphone_sorrow_sadness-1172564.jpg!s`,
	},
	{
		word: `independent`,
		translation: `niezależny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/7c/62/entrepreneur_startup_start_up_man_planing_business_office_businessman-764641.jpg!s`,
	},
	{
		word: `intelligent`,
		translation: `inteligentny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/06/07/entrepreneur_startup_start_up_man_planing_business_office_businessman-764654.jpg!s`,
	},
	{
		word: `introvert`,
		translation: `introwertyk`,
		letters: `-czka`,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/f0/41/girl_hipster_sexy_shy_hands_hiding_face-710150.jpg!s`,
	},
	{
		word: `lazy`,
		translation: `leniwy`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/49/e8/lazy_bag_beutifull_girl_red_shoes_jack_daniels_woman_young_female_model-583200.jpg!s`,
	},
	{
		word: `mean`,
		translation: `skąpy`,
		translation2: `złośliwy`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/be/fd/photo-465003.jpg!s`,
	},
	{
		word: `messy`,
		translation: `bałaganiarski`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/b9/45/brush_color_colors_colours_craft_messy_motley_paint-1178990.jpg!s`,
	},
	{
		word: `nasty`,
		translation: `złośliwy`,
		translation2: `wstrętny`,
		translation3: `nieprzyjemny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/f9/75/cry_zoom_effect_stress_angry_hustle_and_bustle-1143408.jpg!s`,
	},
	{
		word: `nice`,
		translation: `miły`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/98/77/pretty_girls_happy_young_smiling_persons_people_nice-1337398.jpg!s`,
	},
	{
		word: `open`,
		translation: `otwarty`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/87/c0/sad_status_nice_picture_beautiful_sister_nice_vietnamese_woman_coffee_shop_drink-485863.jpg!s`,
	},
	{
		word: `optimistic`,
		translation: `optymistyczny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/images/ea/43/0895db470b809cb5f531d8d902e3-1449169.jpg!s`,
	},
	{
		word: `pessimistic`,
		translation: `pesymistyczny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/ac/ab/the_customary_alk_alcohol_alcoholics_alcoholism_alcohol_consumption_patterns_alcohol_abuse_beer-1143512.jpg!s`,
	},
	{
		word: `outgoing`,
		translation: `otwarty`,
		translation2: `towarzyski`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/3f/f9/girl_biking_bike_bicycle_cycle_cycling_cyclist_helmet-796351.jpg!s`,
	},
	{
		word: `patient`,
		translation: `cierpliwy`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/16/e4/meditate_meditation_peaceful_silhouettes_sunset_tranquil_yoga-1175713.jpg!s`,
	},
	{
		word: `impatient`,
		translation: `niecierpliwy`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/0f/a7/work_management_time_management_office_working_deadline_schedule_management_time-700451.jpg!s`,
	},
	{
		word: `polite`,
		translation: `uprzejmy`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/42/9f/paddington_bear_station_statue_likeness_look_after_marmalade-478513.jpg!s`,
	},
	{
		word: `quiet`,
		translation: `cichy`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/51/68/reading_bookworm_man_books_learning_literature_solitude_stacks-541166.jpg!s`,
	},
	{
		word: `reliable`,
		translation: `solidny`,
		translation2: `niezawodny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/c4/7f/rope_fasten_steadfast_fastening_wooden_post_secure_stake-642833.jpg!s`,
	},
	{
		word: `unreliable`,
		translation: `niesolidny`,
		translation2: `zawodny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/96/2b/park_blackandwhite_bw_monochrome_bench_distorted_furniture_seat-399669.jpg!s`,
	},

	{
		word: `responsible`,
		translation: `odpowiedzialny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/16/7d/baby_baby_with_mom_mother_kiss_tenderness_mothers_day_mother's_day-1349439.jpg!s`,
	},
	{
		word: `rude`,
		translation: `niegrzeczny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/14/59/couple_making_out_young_happy_people_woman_man_relationship-885731.jpg!s`,
	},
	{
		word: `selfish`,
		translation: `samolubny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/43/2a/black_hair_brick_wall_bricks_casual_collar_confident_curly_hair_daylight-1550653.jpg!s`,
	},
	{
		word: `unselfish`,
		translation: `bezinteresowny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/images/91/39/f6ed1d9ef36b85aa4e3c87bfaa23-1447823.jpg!s`,
	},
	{
		word: `serious`,
		translation: `poważny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/images/9a/ff/abfff1c49a7a6917c696460aff74-1432559.jpg!s`,
	},
	{
		word: `shy`,
		translation: `nieśmiały`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/58/8d/family_love_father_daughter_peek_young_girl_hug-1328294.jpg!s`,
	},
	{
		word: `silly`,
		translation: `niemądry`,
		translation2: `głupkowaty`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/d9/2a/basketball_man_model_young_male_people_adult_person-876937.jpg!s`,
	},
	{
		word: `sociable`,
		translation: `towarzyski`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/d8/46/frogs_sociable_bank_bench_relaxed_fig_funny_rest-499742.jpg!s`,
	},
	{
		word: `unsociable`,
		translation: `nietowarzyski`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/images/6d/8f/9cbadd7406993e838ff974eddee3-1428699.jpg!s`,
	},
	{
		word: `talkative`,
		translation: `gadatliwy`,
		translation2: `rozmowny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/05/12/kermit_frog_green_doll_figure_laugh_curious_joy-1256697.jpg!s`,
	},
	{
		word: `tidy`,
		translation: `schludny`,
		translation2: `porządny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/0a/7c/clean_work_janitor_interior_man_tidy-869408.jpg!s`,
	},
	{
		word: `untidy`,
		translation: `niechlujny`,
		female: true,
		level: `basic`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/68/e6/running_water_outside_mud_muddy_splash_splashing_race-1355471.jpg!s`,
	},
	// // // -extended
	{
		word: `bossy`,
		translation: `apodyktyczny`,
		translation2: `bezwzględny`,
		female: true,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/images/b0/38/1a9a5fd15491632886ee76f61cd0-1434823.jpg!s`,
	},
	{
		word: `cowardly`,
		translation: `tchórzliwy`,
		female: true,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/17/f0/hummingbird_flying_bird_nature_wing_wildlife_animal_small-888793.jpg!s`,
	},
	{
		word: `eccentric`,
		translation: `ekscentryczny`,
		female: true,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/d2/04/gay_argentina_girl_canon_lesbian_photo_buenosaires_foto-466114.jpg!s`,
	},
	{
		word: `materialistic`,
		translation: `materialistyczny`,
		female: true,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/images/c2/64/3f4b6dd913100daa4a17a407b3f7-1419843.jpg!s`,
	},
	{
		word: `modest`,
		translation: `skromny`,
		female: true,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/61/96/girl_smile_teenager_beautiful_authentic_shy_modest_portrait-535731.jpg!s`,
	},
	{
		word: `moody`,
		translation: `kapryśny`,
		female: true,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/f7/f1/man_stress_male_face_adult_young_person_expression-1327121.jpg!s`,
	},
	{
		word: `odd`,
		translation: `dziwny`,
		female: true,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/e7/8f/pig-204567.jpg!s`,
	},
	{
		word: `oddball`,
		translation: `dziwak`,
		letters: `-czka`,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/4d/ac/man_silly_funny_crazy_weird_odd_peculiar_person-706595.jpg!s`,
	},
	{
		word: `sensitive`,
		translation: `wrażliwy`,
		female: true,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/ef/bb/soap_bubble_burst_dream_sensitive_transient_iridescent_drip_wabbelig-738311.jpg!s`,
	},
	{
		word: `sincere`,
		translation: `szczery`,
		female: true,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/01/f6/joy_frank_natural_beautiful_man-804155.jpg!s`,
	},
	{
		word: `sympathetic`,
		translation: `życzliwy`,
		translation2: `współczujący`,
		translation3: `sympatyczny`,
		female: true,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/2f/26/bath_bow_tie_rays_young_sympathetic_smile-607376.jpg!s`,
	},
	{
		word: `weird`,
		translation: `dziwny`,
		female: true,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/32/76/man_fashion_model_fashion_man_young_male_portrait_attractive-1363292.jpg!s`,
	},
	{
		word: `weirdo`,
		translation: `dziwak`,
		translation2: `dziwadło`,
		female: `without-t2`,
		letters: `-czka`,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/ad/a4/urban_clown_evil_grunge_horror_beach_carnival_characters-584256.jpg!s`,
	},
	{
		word: `whizzkid`,
		translation: `cudowne dziecko`,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/images/15/6a/440d604ab5b15bc91cd97b28046c-1428411.jpg!s`,
	},
	{
		word: `withdrawn`,
		translation: `zamknięty w sobie`,
		translation2: `wycofany`,
		female: `first`,
		level: `extended`,
		type: `cechy charakteru`,
		image: `https://c.pxhere.com/photos/f5/ff/painted_turtle_chrysemys_picta_withdrawn_shell_most_widespread_na_turtle_moneymore_ontario_canada-555887.jpg!s`,
	},
];

export default words4_FeaturesOfCharacters