const words5_FeelingsAndEmotions = [
	{
		word: `angry`,
		translation: `zły`,
		translation2: `rozgniewany`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `annoyed`,
		translation: `zirytowany`, 
		translation2: `rozdrażniony`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `be in a good mood`,
		translation: `być w dobrym humorze`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `be in a bad mood`,
		translation: `być w złym humorze`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `bored`,
		translation: `znudzony`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `cross`,
		translation: `zły`, 
		translation2: `rozgniewany`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `depressed`,
		translation: `załamany`, 
		translation2: `przygnębiony`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `didappointed`,
		translation: `zawstydzony`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `excited`,
		translation: `podekscytowany`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `exhausted`,
		translation: `wyczerpany`, 
		translation2: `zmęczony`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `frightened`,
		translation: `przerażony`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `nervous`,
		translation: `zdenerwowany`, 
		translation2: `spięty`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `pleased`,
		translation: `zadowolony`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `relaxed`,
		translation: `zrelaksowany`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `scared`,
		translation: `wystraszony`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `shocked`,
		translation: `zszokowany`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `stressed`,
		translation: `zestresowany`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `surprised`,
		translation: `zdziwiony`, 
		translation2: `zaskoczony`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `tired`,
		translation: `zmęczony`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `upset`,
		translation: `przygnębiony`, 
		translation2: `zaniepokojony`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `worried`,
		translation: `zmartwiony`, 
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	// // // -extended
	{
		word: `amazed`,
		translation: `zdumiony`, 
		translation2: `zdziwiony`, 
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `delighted`,
		translation: `zachwycony`, 
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `nagging feeling`,
		translation: `dręczące uczucie`, 
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `petrified`,
		translation: `przerażony`, 
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `shattered`,
		translation: `zdruzgotany`, 
		translation2: `wykończony`, 
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `stunned`,
		translation: `oniemiały`, 
		translation2: `osłupiały`, 
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word: `worn out`,
		translation: `wycieńczony`, 
		translation2: `wyczerpany`, 
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
];

export default words5_FeelingsAndEmotions