const words6_Interests = [
	{
		word: `adore`,
		translation: `uwielbiać`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word: `be a fan of sb (somebody)`,
		translation: `być fanem kogoś`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word: `be a fan of sth (something)`,
		translation: `być fanem czegoś`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word: `be hopeless at`,
		translation: `być beznadziejnym w`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word: `be into sth (something)`,
		translation: `zajmować się czyimś`, 
		translation2: `interesować się czymś`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word: `be keen on sth (something)`,
		translation: `interesować się czymś`, 
		translation2: `lubić coś robić`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word: `be mad about sb (somebody)`,
		translation: `szaleć na kimś`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word: `be mad about sth (something)`,
		translation: `szaleć za czymś`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word: `can't stand`,
		translation: `nie znosić`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word: `play games`,
		translation: `grać w gry`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word: `play board games`,
		translation: `grać w gry planszowe`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word: `work out`,
		translation: `trenować`, 
		translation2: `ćwiczyć`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
];

export default words6_Interests