const words7_EthnicalProblems = [
	{
		word: `abortion`,
		translation: `aborcja`, 
		level: `basic`,
		type: `ethnical problems`,
		image: `url`,
	},
	{
		word: `charity`,
		translation: `dobroczynność`, 
		translation2: `ogranizacja charytatywna`, 
		level: `basic`,
		type: `ethnical problems`,
		image: `url`,
	},
	{
		word: `drug abuse`,
		translation: `zażywanie narkotyków`, 
		level: `basic`,
		type: `ethnical problems`,
		image: `url`,
	},
	{
		word: `fair trade`,
		translation: `sprawiedliwy handel`, 
		level: `basic`,
		type: `ethnical problems`,
		image: `url`,
	},
	{
		word: `homelessness`,
		translation: `bezdomność`, 
		level: `basic`,
		type: `ethnical problems`,
		image: `url`,
	},
	{
		word: `unemployment`,
		translation: `bezrobocie`, 
		level: `basic`,
		type: `ethnical problems`,
		image: `url`,
	},
	{
		word: `corruption`,
		translation: `korupcja`, 
		level: `basic`,
		type: `ethnical problems`,
		image: `url`,
	},
	{
		word: `racism`,
		translation: `rasizm`, 
		level: `basic`,
		type: `ethnical problems`,
		image: `url`,
	},
	// // // -extended
	{
		word: `dealth penatly`,
		translation: `kara śmierci`, 
		level: `extended`,
		type: `ethnical problems`,
		image: `url`,
	},
	{
		word: `eutanasia`,
		translation: `eutanazja`, 
		level: `extended`,
		type: `ethnical problems`,
		image: `url`,
	},
	{
		word: `freedom of speech`,
		translation: `wolność słowa`, 
		level: `extended`,
		type: `ethnical problems`,
		image: `url`,
	},
	{
		word: `gambling`,
		translation: `hazard`, 
		level: `extended`,
		type: `ethnical problems`,
		image: `url`,
	},
	{
		word: `genetic engineering`,
		translation: `inżynieria genetyczna`, 
		level: `extended`,
		type: `ethnical problems`,
		image: `url`,
	},
	{
		word: `privacy`,
		translation: `prywatność`, 
		level: `extended`,
		type: `ethnical problems`,
		image: `url`,
	},
];

export default words7_EthnicalProblems