const words8_Orther = [
	{
		word: `brief`,
		translation: `krótki`, 
		translation2: `krótkotrwały`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `come across`,
		translation: `wpaść na`, 
		translation2: `natknąć się na`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `complete`,
		translation: `całkowity`, 
		translation2: `kompletny`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `develop into`,
		translation: `rozwinąć się w`, 
		translation2: `stawać się (kimś)`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `eco-freak`,
		translation: `fanatyk ekologii`, 
		translation2: `fanatyczka ekologii`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `fitness maniac`,
		translation: `fanatyk ćwiczeń fizycznych`, 
		translation2: `fanatyczka ćwiczeń fizycznych`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `focus on`,
		translation: `skupiać się na`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `grow up`,
		translation: `rosnąć`, 
		translation2: `dorastać`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `have a lot in common`,
		translation: `mieć dużo wspólnego`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `have a little in common`,
		translation: `mieć niewiele wspólnego`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `health nut`,
		translation: `osoba mająca obsesję na punkcie zdrowia`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `huge`,
		translation: `ogromny`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `identify`,
		translation: `zidentyfikować`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `look up to`,
		translation: `podziwiać`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `realise`,
		translation: `zdać sobie sprawę`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `recognise`,
		translation: `rozpoznać`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `remember`,
		translation: `pamiętać`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `remind someone to do something`,
		translation: `przypomnieć komuś, by coś zrobił`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `spend money on`,
		translation: `wydawać pieniądze na`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `spot`,
		translation: `dostrzec`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `the complete opposite`,
		translation: `całkowite przeciwieństwo`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `typical of`,
		translation: `typowy dla`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	// // //
	{
		word: `be part of someone's nature`,
		translation: `leżeć w czyjejś naturze`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `befriend`,
		translation: `zaprzyjaźnić się z`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `bizarre`,
		translation: `dziwny`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `can\`t believe your ears`,
		translation: `nie móc uwierzyć własnym uszom`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `common experience`,
		translation: `częste doznanie`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `find common ground`,
		translation: `znaleźć wspólną płaszczyznę`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `have the time of your life`,
		translation: `doskonale się bawić`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `place`,
		translation: `rozpoznać`, 
		translation2: `zidentyfikować`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `pluck up the courage (to do something)`,
		translation: `zdobyć się na odwagę (aby coś zrobić)`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `raise questions`,
		translation: `nasuwać pytania`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `scan`,
		translation: `przeskanować (np. mózg)`, 
		translation2: `przebiec wzrokiem (np. tekst)`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `sophisticated`,
		translation: `skomplikowany`, 
		translation2: `zaawansowany`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `strike up (a conversation)`,
		translation: `nawiązać (rozmowę)`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
];

export default words8_Orther