const words2_DescribingHouses = [
	{
		word1: `attic`,
		word2: `loft`,
		translation1: `strych`,
		translation2: `poddasze`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/96/3d/homes_for_sale_attic_scuttle-1104646.jpg!d`,
	},
	{
		word1: `balcony`,
		translation1: `balkon`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/e6/c1/couple_sunset_balcony_view_island-2405.jpg!d`,
	},
	{
		word1: `basement`,
		word2: `cellar`,
		translation1: `piwnica`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/55/d8/botti_cellar_wine_ancient_tuscany_italy-973228.jpg!d`,
	},
	{
		word1: `bathroom`,
		translation1: `łazienka`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/ef/00/bathroom_luxury_luxury_bathroom_sink_bathtub_contemporary_mirror_bathroom_sink-633131.jpg!d`,
	},
	{
		word1: `bedroom`,
		translation1: `sypialnia`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/97/04/hotel_room_bed_pillows_room_hotel_bedroom_lamp_interior-607447.jpg!d`,
	},
	{
		word1: `carport`,
		translation1: `wiata na samochód`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/bc/05/carport_2009365-359051.jpg!d`,
	},
	{
		word1: `ceiling`,
		translation1: `sufit`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/16/99/book_library_architecture_hall_wall-175684.jpg!d`,
	},
	{
		word1: `chimney`,
		translation1: `komin`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/84/05/chimney_pollution_air_pollution_environment_power_ecological_funnel_cowl-974556.jpg!d`,
	},
	{
		word1: `dining room`,
		translation1: `jadalnia`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/11/9a/diner_table_restaurant_chair_plate-1671.jpg!d`,
	},
	{
		word1: `door`,
		translation1: `drzwi`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/8e/47/house_street_door_window_brick-102975.jpg!d`,
	},
	{
		word1: `downstairs`,
		translation1: `na dole`,
		translation2: `na parterze`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/c8/0b/escalator_down_building_stairs_transport_downstairs_mall_airport-1073385.jpg!d`,
	},
	{
		word1: `drive`,
		translation1: `podjazd`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/90/24/real_estate_garage_doors_home_architecture_driveway_house-958128.jpg!d`,
	},
	{
		word1: `fence`,
		translation1: `ogrodzenie`,
		translation2: `płot`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/90/7f/chainlink_fence_metal_wire_protection_security_safety_barrier-744273.jpg!d`,
	},
	{
		word1: `fireplace`,
		translation1: `kominek`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/e9/00/fire_fireplace_warmth_hearth_coal-100626.jpg!d`,
	},
	{
		word1: `front door`,
		translation1: `drzwi frontowe`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/87/fb/door_handle_keyhole_wooden_metal_decoration_home_entrance-744555.jpg!d`,
	},
	{
		word1: `back door`,
		translation1: `drzwi tylne`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/9c/0f/door_bad_luck_13_thirteen_unlucky_hotel_apartment_closed-548130.jpg!d`,
	},
	{
		word1: `garage`,
		translation1: `garaż`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/f4/da/garage_underground_store_closed_subway_dark_background_wallpaper-878194.jpg!d`,
	},
	{
		word1: `garden`,
		translation1: `ogród`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/images/7c/9b/038375e0ef76f3a0c8611642676f-1456607.jpg!d`,
	},
	{
		word1: `gate`,
		translation1: `brama`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/2c/68/angel_flight_gate_paradise-805680.jpg!d`,
	},
	{
		word1: `ground floor`,
		translation1: `parter`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/25/1a/wooden_floor_house_floor_hardwood_construction_shutters_sofa_design-633136.jpg!d`,
	},
	{
		word1: `hall`,
		translation1: `hol`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/2a/4b/art_exhibition_gallery_museum_paintings_people_public_domain_images-973226.jpg!d`,
	},
	{
		word1: `hedge`,
		translation1: `żywopłot`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/4b/e6/pathway_path_hedge_bush-1291133.jpg!d`,
	},
	{
		word1: `island`,
		translation1: `wyspa kuchenna`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/80/a5/kitchen_residential_home_house_remodel_granite_counters_kitchen_island-1371683.jpg!d`,
	},
	{
		word1: `kithen`,
		translation1: `kuchnia`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/f2/29/kitchen_work_restaurant_cook_chef_professional_food_preparation-1327589.jpg!d`,
	},
	{
		word1: `laundry room`,
		translation1: `domowa pralnia`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/38/8c/black_and_white_clean_housework_launderette_laundromat_laundry_student_washer-1002971.jpg!d`,
	},
	{
		word1: `lift`,
		translation1: `winda`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/2d/a2/elevator_passenger_elevator_elevator_button_floor_button-962351.jpg!d`,
	},
	{
		word1: `living room`,
		word2: `lounge`,
		translation1: `salon`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/05/1b/livingroom_interior_design_furniture_indoors_apartment_decor-678048.jpg!d`,
	},
	{
		word1: `porch`,
		translation1: `ganek`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/ad/5f/swing_porch_cabin_bike_house-132678.jpg!d`,
	},
	{
		word1: `roof`,
		translation1: `dach`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/2c/4b/roof_plate_tiles_brick_black_the_roof_of_the_tile_steel_sheet-989472.jpg!d`,
	},
	{
		word1: `shed`,
		translation1: `szopa`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/6a/96/hut_cabin_shed_building_boathouse-1362569.jpg!d`,
	},
	{
		word1: `sitting room`,
		translation1: `pokój dzienny`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/fc/d9/office_sitting_room_executive_sitting_business_desk_workplace_corporate-735699.jpg!d`,
	},
	{
		word1: `stairs`,
		translation1: `schody`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/df/c1/escalator_metro_stairs_subway_urban_station_staircase_stairway-1076090.jpg!d`,
	},
	{
		word1: `staircase`,
		translation1: `klatka schodowa`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/bd/a9/stair_spiral_staircase_architecture_marble-502620.jpg!d`,
	},
	{
		word1: `steps`,
		translation1: `schodki`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/images/dd/37/b2ed2864228cf69974d02ead7811-1456919.jpg!d`,
	},
	{
		word1: `study`,
		translation1: `gabinet`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/images/72/5e/38ef1fd111f4a34b8a5ba24703f6-1456587.jpg!d`,
	},
	{
		word1: `upstairs`,
		translation1: `na górze`,
		translation2: `na piętrze`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/1b/3d/architectural_design_architecture_building_dark_glass_glass_windows_handrails_interior-1553783.jpg!d`,
	},
	{
		word1: `wall`,
		translation1: `ściana`,
		translation2: `mur`,
		level: `basic`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/e7/08/bricks_wall_stones_structure_stone_wall_texture_background-933392.jpg!d`,
	},
	// // // -extended
	{
		word1: `bulgar alarm`,
		translation1: `alarm antywłamaniowy`,
		level: `extended`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/65/a4/car_burglary_thief_burglar_break_into_screwdriver_car_thief_break_locks-545992.jpg!d`,
	},
	{
		word1: `double-glased`,
		translation1: `z podwójną szybą`,
		level: `extended`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/images/94/47/d9b1f8557679291420bb68cdf104-1445037.jpg!d`,
	},
	{
		word1: `extension`,
		translation1: `przybudówka`,
		level: `extended`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/80/83/outhouse_wood_toilet_old_wooden_rural_rustic_bathroom-572488.jpg!d`,
	},
	{
		word1: `fish pond`,
		translation1: `staw rybny`,
		level: `extended`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/f2/18/carp_koi_fish_water_pond_water_surface_koi_carp_toy-1094320.jpg!d`,
	},
	{
		word1: `floorboards`,
		translation1: `deski podłogowe`,
		level: `extended`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/76/e4/wood_planks_plank_wooden_board_boards_timber_rough-1023445.jpg!d`,
	},
	{
		word1: `flowerbed`,
		translation1: `klomb`,
		level: `extended`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/65/f6/park_person_flowerbed_circle_carriage-1393210.jpg!d`,
	},
	{
		word1: `landing`,
		translation1: `półpiętro`,
		level: `extended`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/24/0b/skylight_centro_cultural_banco_do_brasil_mezzanine_s_o_paulo-994229.jpg!d`,
	},
	{
		word1: `smoke alarm`,
		translation1: `alarm przeciwpożarowy`,
		level: `extended`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/87/99/fire_smoke_risk_fog_roof_brand_fire_fighting_flame-651918.jpg!d`,
	},
	{
		word1: `solar panels`,
		translation1: `panele słoneczne`,
		level: `extended`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/14/24/solar_power_solar_panels_photovoltaics_panels_sun_sky-708107.jpg!d`,
	},
	{
		word1: `stair rail`,
		translation1: `poręcz przy schodach`,
		level: `extended`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/15/49/stair_hand_hold_railings_stairs_rail_staircase_handrail_support_hold-1042551.jpg!d`,
	},
	{
		word1: `utility room`,
		translation1: `pomieszczenie gospodarcze`,
		level: `extended`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/4a/ff/trees_sky_field_clouds_barn_rural_spring_pennsylvania-573389.jpg!d`,
	},
	{
		word1: `windowsill`,
		translation1: `parapet okienny`,
		level: `extended`,
		type: `pomieszczenia i części domu`,
		image: `https://c.pxhere.com/photos/00/f7/cat_feline_window_windowsill_pet_cute_domestic_animal-1329533.jpg!d`,
	},
	// // // // // -opis domu
	{
		word1: `airy`,
		translation1: `przestronny`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/a6/3a/soap_bubbles_green_farbenspiel_tree_colorful_shimmer_float_airy-606745.jpg!d`,
	},
	{
		word1: `brick`,
		translation1: `cegła`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/26/a3/wall_stones_hauswand_structure_building_architecture_pattern_masonry-1092679.jpg!d`,
	},
	{
		word1: `bright`,
		translation1: `jasny`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/images/c3/30/1e4fd4340cb91db0c4f7071619f4-1450567.jpg!d`,
	},
	{
		word1: `clutted`,
		translation1: `zagracony`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/57/ae/girl_woman_typing_writing_blogger_blogging_keyboard_black-723003.jpg!d`,
	},
	{
		word1: `comfortable`,
		translation1: `wygodny`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/da/a4/french_bulldog_dog_puppy_pet_animals_bulldog_mischief_funny-1125668.jpg!d`,
	},
	{
		word1: `convert`,
		translation1: `przerobić`,
		translation2: `przekształcić`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/2c/f7/photo-206606.jpg!d`,
	},
	{
		word1: `cosy`,
		translation1: `przytulny`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/1c/d4/armchair_chairs_wooden_chairs_interior_home_dining_dining_chairs_cosy-838555.jpg!d`,
	},
	{
		word1: `decorated`,
		translation1: `wykończony`,
		translation2: `odnowiony`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/27/a3/wedding_seating_seats_chairs_white_decorated_outdoors-965527.jpg!d`,
	},
	{
		word1: `eco-friendly`,
		translation1: `przyjazny dla środowiska`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/a1/10/environmental_protection_environment_atmosphere_fragile_surreal_tree_nature_nature_conservation-1081335.jpg!d`,
	},
	{
		word1: `furnished`,
		translation1: `umeblowany`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/3e/49/living_room_interior_design_sofa_wood_floor_living_room_interior_residential_lifestyle_decoration-559753.jpg!d`,
	},
	{
		word1: `unfurnished`,
		translation1: `nieumeblowany`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/91/7a/wall_gallery_studio_exhibition_room_hardwood_floor_exhibit-879870.jpg!d`,
	},
	{
		word1: `glass`,
		translation1: `szkło`,
		translation2: `szklany`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/images/db/21/f221660e621593c7a4d440179554-1447481.jpg!d`,
	},
	{
		word1: `homely`,
		translation1: `przytulny`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/2c/89/caravanserai_hostel_oriental_interior_living_room_seating_area_as_rl_k_sel_uklu_han_cappadocia-1252746.jpg!d`,
	},
	{
		word1: `luxurious`,
		translation1: `luksusowy`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/7b/0e/jewelry_gold_precious_shiny_luxury_diamond_necklace_locket-702224.jpg!d`,
	},
	{
		word1: `maintain`,
		translation1: `utrzymywać`,
		translation2: `konserwować`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/f3/25/motorbike_suspension_motorcycle_bike_transportation_metal_technology_machine-618017.jpg!d`,
	},
	{
		word1: `modern`,
		translation1: `nowoczesny`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/images/10/30/8ad04186357ad41c317dd7a4afe7-1446057.jpg!d`,
	},
	{
		word1: `mud`,
		translation1: `błoto`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/6d/ca/soldiers_army_basic_training_mud_crawling_military_exercise_water-1229193.jpg!d`,
	},
	{
		word1: `second-hand`,
		translation1: `używany`,
		translation2: `z drugiej ręki`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/f0/29/flea_market_doll_vintage_market_junk_kitsch_browse_second_hand-931698.jpg!d`,
	},
	{
		word1: `spacious`,
		translation1: `przestronny`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/58/80/sweden_stinsen_arena_building_structure_floor_lights_reflections_ceiling-1137326.jpg!d`,
	},
	{
		word1: `steel`,
		translation1: `stalowy`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/10/b1/chain_link_metal_strong_connect_connected_protection_power-893023.jpg!d`,
	},
	{
		word1: `stone`,
		translation1: `kamienny`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/images/40/98/07c4f92e8582a3620831a7ea1900-1418095.jpg!d`,
	},
	{
		word1: `tidy`,
		translation1: `posprzątany`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/2f/1e/desk_laptop_computer_notebook_office_technology_work_workplace-759689.jpg!d`,
	},
	{
		word1: `untidy`,
		translation1: `nieposprzątany`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/9b/9b/clutter_mess_untidy_garden_shed_workshop_shed_garage_store-961676.jpg!d`,
	},
	{
		word1: `wooden`,
		translation1: `drewniany`,
		level: `basic`,
		type: `opis domu`,
		image: `https://c.pxhere.com/images/82/41/b5ceb16d07e3620610ca02d8ca7b-1448519.jpg!d`,
	},
	// // // -extended
	{
		word1: `badly-decorated`,
		translation1: `źle wykończony`,
		level: `extended`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/68/42/heidelberg_door_window_sweet_cheesy_pink_colorful_girl-482555.jpg!d`,
	},
	{
		word1: `cramped`,
		translation1: `ciasny`,
		level: `extended`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/d6/12/buildings_city_cramped_empty_street_house_residential_area_small_street-1179049.jpg!d`,
	},
	{
		word1: `dingy`,
		translation1: `obskurny`,
		level: `extended`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/1d/12/containers_storage_rusted_rusty_old_forgotten_stacked_dingy-639999.jpg!d`,
	},
	{
		word1: `dusty`,
		translation1: `zakurzony`,
		level: `extended`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/1f/f3/elephants_sun_bath_playing_with_sand_dusty_dust_sri_lanka_pinnawala_ceylon-988803.jpg!d`,
	},
	{
		word1: `oak`,
		translation1: `dębowy`,
		level: `extended`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/75/6a/board_wood_texture_plank_natural_timber_surface_material-1258642.jpg!d`,
	},
	{
		word1: `old-fashioned`,
		translation1: `staromodny`,
		level: `extended`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/6a/ae/movie_reel_projector_film_cinema_entertainment_retro_vintage-1067196.jpg!d`,
	},
	{
		word1: `open-plan`,
		translation1: `bez ścian działowych`,
		level: `extended`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/31/7f/multi_storey_car_park_park_flat_park_level_parking_number_alternate_space_parking_level-925637.jpg!d`,
	},
	{
		word1: `stuffy`,
		translation1: `duszny`,
		level: `extended`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/c4/19/desert_drought_dehydrated_clay_soil_clay_earth_cracked_cracks-983385.jpg!d`,
	},
	{
		word1: `unique-looking`,
		translation1: `o unikalnym wyglądzie`,
		level: `extended`,
		type: `opis domu`,
		image: `https://c.pxhere.com/photos/da/64/reptile_chameleon_yemen_pets_isolated_lizard_green_insectivore-1105604.jpg!d`,
	},
	{
		word1: `well-manitained`,
		translation1: `dobrze utrzymany`,
		translation2: `zadbany`,
		level: `extended`,
		type: `opis domu`,
		image: `https://c.pxhere.com/images/de/e8/5fe5dd7835df1178da430fc2f953-1426985.jpg!d`,
	},
	// // // // // -meble i wyposażenie
	{
		word1: `alarm clock`,
		translation1: `budzik`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/71/cd/alarm_clock_stand_up_time_of_sleep_bed_wake_up_time_indicating_ring_the_bell-655786.jpg!d`,
	},
	{
		word1: `armchair`,
		translation1: `fotel`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/a8/79/room_armchair_lamp_evening_home_chair_interior_furniture-856389.jpg!d`,
	},
	{
		word1: `bath`,
		translation1: `wanna`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/11/e6/bathroom_sink_faucet_restroom_vanity-100720.jpg!d`,
	},
	{
		word1: `bed`,
		translation1: `łóżko`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/05/31/woman_bed_female_attractive_bedroom_girl_people_lifestyle-778445.jpg!d`,
	},
	{
		word1: `bedsite table`,
		translation1: `stolik nocny`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/cc/b4/morning_clock_alarm-837943.jpg!d`,
	},
	{
		word1: `bin`,
		translation1: `kosz`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/cb/e7/garbage_can_waste_waste_bins_recycle_bin_garbage_waste_disposal_environmental_protection_environmental_environmentalism-615751.jpg!d`,
	},
	{
		word1: `blanket`,
		translation1: `koc`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/eb/4e/pug_dog_blanket_puppy_canine-32255.jpg!d`,
	},
	{
		word1: `blinds`,
		translation1: `rolety`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/99/8f/blinds_roller_shutter_open_gap_look_sun_morning_sunlight-1010309.jpg!d`,
	},
	{
		word1: `bookcase`,
		translation1: `biblioteczka`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/fb/7c/book_table_bookshelf_library_interior-56909.jpg!d`,
	},
	{
		word1: `bookshelf`,
		translation1: `półka na książki`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/d7/de/book_read_old_literature_pages_books_bookshelf_old_books-495484.jpg!d`,
	},
	{
		word1: `bookshelves`,
		translation1: `półki na książki`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/fd/2b/books_bookshelves_building_business_commerce_low_angle_shot_shelves_stock-1492475.jpg!d`,
	},
	{
		word1: `carpet`,
		translation1: `dywan`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/23/99/rug_carpet_woven_handmade_textiles-838630.jpg!d`,
	},
	{
		word1: `CD player`,
		translation1: `odtwarzacz płyt CD`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/a8/a9/cd_cd_player_music_system_audio_music_hifi_kenwood_eject-708243.jpg!d`,
	},
	{
		word1: `central heating`,
		translation1: `centralne ogrzewanie`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/f0/1e/smoke_clouds_of_smoke_coal_bake_kindle_grate_warm_temperature-738345.jpg!d`,
	},
	{
		word1: `chair`,
		translation1: `krzesło`,
		translation2: `fotel`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/da/af/desk_white_background_white_room_chair_white-1054672.jpg!d`,
	},
	{
		word1: `chest of drawers`,
		translation1: `komoda`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/1f/f2/interior_design_decoration_decor_vase_vases_white_purple-722575.jpg!d`,
	},
	{
		word1: `cooker`,
		translation1: `kuchenka`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/38/53/gas_burners_cooker_the_flame_blue_oven_cooking_energy_danger-1031382.jpg!d`,
	},
	{
		word1: `cupboard`,
		translation1: `szafka kuchenna`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/74/cd/appliances_cabinets_contemporary_counter_cupboard_design_faucet_furniture-1553097.jpg!d`,
	},
	{
		word1: `curtains`,
		translation1: `zasłony`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/72/8e/woman_standing_window_silhouette_scene_posed_black_and_white_sexy-1324637.jpg!d`,
	},
	{
		word1: `net curtains`,
		translation1: `firanki`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/2f/b6/curtains_colors_metallic_decoration-812875.jpg!d`,
	},
	{
		word1: `cushion`,
		translation1: `poduszka (dekoracyjna)`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/d1/f3/pillows_bedding_comforter_bed_comfortable_comfort_cushion_sleep-1229056.jpg!d`,
	},
	{
		word1: `desk`,
		translation1: `biurko`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/f3/88/desk_laptop_macbook_apple_office-99193.jpg!d`,
	},
	{
		word1: `dishwasher`,
		translation1: `zmywarka`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/89/2c/dishwasher_clean_dishes_appliances_household_cleaning_up-772967.jpg!d`,
	},
	{
		word1: `double bed`,
		translation1: `podwójne łóżko`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/86/d5/bed_room_hotel_double_bed_bedroom_sleep-1063678.jpg!d`,
	},
	{
		word1: `duved`,
		translation1: `kołdra`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/7a/06/pillow_bedroom_dragonfly_quilt-1165826.jpg!d`,
	},
	{
		word1: `equipment`,
		translation1: `wyposażenie`,
		translation2: `sprzęt`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/4a/3c/tools_do_it_yourself_hammer_carpentry_construction_wrench_repair_work-926209.jpg!d`,
	},
	{
		word1: `fireplace`,
		translation1: `kominek`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/e9/00/fire_fireplace_warmth_hearth_coal-100626.jpg!d`,
	},
	{
		word1: `fitted carpet`,
		translation1: `wykładzina dywanowa`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/c3/e2/vacuum_cleaner_vacuuming_cleaning_washing_cleanup_carpet_carpeting-987841.jpg!d`,
	},
	{
		word1: `flowerpot`,
		translation1: `doniczka`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/33/91/plant_food_flower_phone_table-118332.jpg!d`,
	},
	{
		word1: `freezer`,
		translation1: `zamrażarka`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/1b/33/frozen_food_supermarket_frozen_cold_freezer_grocery_healthy_refrigerator-633784.jpg!d`,
	},
	{
		word1: `fridge`,
		translation1: `lodówka`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/2f/03/refrigerator_fridge_cold_storage_kitchen_home_freezer_food_cold-535831.jpg!d`,
	},
	{
		word1: `hoover`,
		translation1: `odkurzacz`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/d7/eb/vacuum_cleaner_carpet_cleaner_housework_housekeeping_appliance_electrical_chores_domestic-750490.jpg!d`,
	},
	{
		word1: `lamp`,
		translation1: `lampa`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/images/e2/aa/517995fbbef8198dc4f1781e1bd2-1418953.jpg!d`,
	},
	{
		word1: `light`,
		translation1: `światło`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/c0/4d/kumamoto_japan_aso_cloud_somma_sea_of_clouds_light_sun-771016.jpg!d`,
	},
	{
		word1: `lighting`,
		translation1: `oświetlenie`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/images/7e/a6/47b069a28d3a715f454a87cb263b-1420050.jpg!d`,
	},
	{
		word1: `microwave`,
		translation1: `kuchenka mikrofalowa`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/ad/f7/chrome_kitchen_microwave_household_appliances_eat_gloss_cook_modern-1331600.jpg!d`,
	},
	{
		word1: `mirror`,
		translation1: `lustro`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/images/9f/dd/b0d318c3aaee85de1dab4cc99a2a-1419056.jpg!d`,
	},
	{
		word1: `oven`,
		translation1: `piekarnik`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/f8/2e/heat_kitchen_oven_stove_hot_fireplace_old_cook-995025.jpg!d`,
	},
	{
		word1: `picture`,
		translation1: `obrazek`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/90/c8/booklet_book_digital_girl_woman_catalog_photobook_picture-942180.jpg!d`,
	},
	{
		word1: `pillow`,
		translation1: `poduszka`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/a2/93/pillow_bed_bedroom_hotel_space-115188.jpg!d`,
	},
	{
		word1: `poster`,
		translation1: `plakat`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/55/19/bollywood_posters_poster_bollywood_india_movies_wall_advertising_flyer-847664.jpg!d`,
	},
	{
		word1: `radiator`,
		translation1: `kaloryfer`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/9e/88/heating_heat_energy_heating_costs_radiator_thermostat_heating_system-858524.jpg!d`,
	},
	{
		word1: `rug`,
		translation1: `dywanik`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/d5/99/sofa_couch_living_room_home_interior_carpet_modern_room-1014680.jpg!d`,
	},
	{
		word1: `sheet`,
		translation1: `prześcieradło`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/73/a8/bed_bedroom_lamp_headboard_bedding_pillow_house_home-670103.jpg!d`,
	},
	{
		word1: `shelf`,
		translation1: `półka`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/53/b3/book_shelf_books_furniture_bird's_nest_decoration_reading_studying_old-964771.jpg!d`,
	},
	{
		word1: `shower`,
		translation1: `prysznic`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/ff/23/shower_shower_head_water_drop_of_water_trays_swim_hygiene_wash-592308.jpg!d`,
	},
	{
		word1: `single bed`,
		translation1: `pojedyncze łóżko`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/4e/8c/bath_house_row_bathhouse_hot_springs_national_park_hot_springs_arkansas_1870_1920s_history_vintage-547056.jpg!d`,
	},
	{
		word1: `sink`,
		translation1: `zlew`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/1b/35/tap_black_faucet_kitchen_sink_interior_design_modern-723004.jpg!d`,
	},
	{
		word1: `sofa`,
		translation1: `kanapa`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/c0/3e/interior_design_sofa_couch_living_room_furniture_interior_living_home-1103565.jpg!d`,
	},
	{
		word1: `table`,
		translation1: `stół`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/images/56/c1/5a2bcf566535f0e28d906d34ebe3-1430899.jpg!d`,
	},
	{
		word1: `toaster`,
		translation1: `toster`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/8b/2d/toast_toaster_food_white_bread_slices_of_toast_eat_breakfast_discs-670056.jpg!d`,
	},
	{
		word1: `toiled`,
		translation1: `toaleta`,
		translation2: `sedes`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/49/d2/wc_toilet_purely_public_toilet_bathroom_shadow_light_cabins-989173.jpg!d`,
	},
	{
		word1: `TV set`,
		translation1: `telewizor`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/6c/66/tv_television_plant_media_center_indoor-45791.jpg!d`,
	},
	{
		word1: `wallpaper`,
		translation1: `tapeta`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/01/1c/paper_colorful_color_loose_green_yellow_red_office-1086762.jpg!d`,
	},
	{
		word1: `wardrobe`,
		translation1: `szafa`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/7a/13/blazer_close_up_closet_clothes_dress_shirt_hangers_hanging_suit-1563117.jpg!d`,
	},
	{
		word1: `washbasin`,
		translation1: `umywalka`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/3c/e7/bathroom_washbasin_pia-718496.jpg!d`,
	},
	{
		word1: `washing machine`,
		translation1: `pralka`,
		level: `basic`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/30/11/switch_knob_washing_machine_control_panel_display_detail_wash_laundry-1059256.jpg!d`,
	},
	// // // -extended
	{
		word1: `antique`,
		translation1: `zabytkowy`,
		translation2: `staroświecki`,
		level: `extended`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/images/40/3c/cb724fde2ed3367231e96a74c10f-1434451.jpg!d`,
	},
	{
		word1: `fruit bowl`,
		translation1: `miska na owoce`,
		level: `extended`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/4d/00/fruit_bowl_citrus_banana_bowl_food_fruit_healthy_oranges-1087260.jpg!d`,
	},
	{
		word1: `hand (of a clock)`,
		translation1: `wskazówka (zegara)`,
		level: `extended`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/bc/8c/clock_time_time_of_time_indicating_pointer_watches_hour_wrist_watch-757871.jpg!d`,
	},
	{
		word1: `kettle`,
		translation1: `czajnik`,
		level: `extended`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/8c/56/kettle_copper_steam_boiling_boil_water_ready-751496.jpg!d`,
	},
	{
		word1: `kitchen appliances`,
		translation1: `sprzęty kuchenne`,
		level: `extended`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/78/d2/food_mixer_hand_held_electric_whisks_kitchen_appliances-946626.jpg!d`,
	},
	{
		word1: `kitchen utensils`,
		translation1: `przybory kuchenne`,
		level: `extended`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/10/4d/wooden_spoon_knife_kitchen_utensils_cook_kitchen_tableware_budget_preparation-1295412.jpg!d`,
	},
	{
		word1: `mantelpiece`,
		translation1: `półka nad kominkiem`,
		level: `extended`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/7d/83/fireplace_mantle_fire_interior_home_warm_room_house-747798.jpg!d`,
	},
	{
		word1: `ornamet`,
		translation1: `ozdoba`,
		level: `extended`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/images/8d/50/5b51af5be0b666b5c7ac132a4ece-1446849.jpg!d`,
	},
	{
		word1: `potted plant`,
		translation1: `roślina doniczkowa`,
		level: `extended`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/ea/62/window_curtain_plant_pot_potted_plant-73797.jpg!d`,
	},
	{
		word1: `rack`,
		translation1: `półka`,
		translation2: `stojak`,
		level: `extended`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/7b/5c/wine_rack_shelf_wine_beverages_bottles_wine_bottles_alcohol_rack-1094503.jpg!d`,
	},
	{
		word1: `shutters`,
		translation1: `okiennice`,
		level: `extended`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/70/5e/window_old_old_window_shutters_wood_wooden_windows_wall_hauswand-499809.jpg!d`,
	},
	{
		word1: `silver frame`,
		translation1: `srebrna ramka`,
		level: `extended`,
		type: `meble i wyposażenie`,
		image: `https://c.pxhere.com/photos/80/26/portrait_frames_picture_gold_decor-698604.jpg!d`,
	},
];

export default words2_DescribingHouses