const words3_HouseholdAndGardenJobs = [
	{
		word: `change the sheets`,
		translation: `zmienić pościel`,
		level: `basic`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/d8/75/girl_bed_hair_bedroom_girl_in_bed_relax_person_indoors-559566.jpg!d`,
	},
	{
		word: `do the gardening`,
		translation: `pracować w ogrodzie`,
		level: `basic`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/b2/12/plant_isolated_human_strawberry_soil_bud_natural_grow-1349598.jpg!d`,
	},
	{
		word: `do the housework`,
		translation: `zajmować się domem`,
		level: `basic`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/da/a2/clothes_peg_dry_clothes_in_the_sun_wash_maid_housework-487273.jpg!d`,
	},
	{
		word: `empty the dishwasher`,
		translation: `opróżniać zmywarkę`,
		level: `basic`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/f6/14/tableware_dishwasher_kitchen_current_power_consumption_budget-918717.jpg!d`,
	},
	{
		word: `have green fingers`,
		translation: `mieć dobrą rękę do roślin`,
		level: `basic`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/images/d5/73/ca560654c95c4d30d94a2ec34386-1441089.jpg!d`,
	},
	{
		word: `hoover the carpet`,
		translation: `odkurzać dywan`,
		level: `basic`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/0c/2f/vacuum_cleaner_vacuuming_cleaning_washing_cleanup-987858.jpg!d`,
	},
	{
		word: `iron the clothes`,
		translation: `prasować ubrania`,
		level: `basic`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/5b/3e/ironing_iron_press_clothing_clothes_housework_laundry_chores-1096580.jpg!d`,
	},
	{
		word: `make the bed`,
		translation: `ścielić łóżko`,
		level: `basic`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/d8/cc/bed_bedroom_pillows_comforter_room_bedding_home_interior-864961.jpg!d`,
	},
	{
		word: `mow the lawn`,
		translation: `kosić trawnik`,
		level: `basic`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/31/68/grass_metal_mechanical_cut_lawn_picasa_gas_illusion-392968.jpg!d`,
	},
	{
		word: `sweep the floor`,
		translation: `zamiatac podłogę`,
		level: `basic`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/dd/d1/lego_legomaennchen_males_workers_work_return_periodic_week_clean-1330400.jpg!d`,
	},
	{
		word: `tidy the desk`,
		translation: `porządkować biurko`,
		level: `basic`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/6a/0b/notebook_desk_working_writing_laptop-103165.jpg!d`,
	},
	// // // -extended
	{
		word: `broom`,
		translation: `miotła`,
		level: `extended`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/70/07/witch_broom_witch_hat_doll_toy_toy_witch_female_witch_forest-540461.jpg!d`,
	},
	{
		word: `brush`,
		translation: `szczotka`,
		level: `extended`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/09/72/clothes_brush_brush_dresses_clean-1152735.jpg!d`,
	},
	{
		word: `duster`,
		translation: `ściereczka do kurzu`,
		level: `extended`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/d7/c2/macro_duster_green_textiles_detail_structure_texture_simplicity-835112.jpg!d`,
	},
	{
		word: `lawnmower`,
		translation: `kosiarka`,
		level: `extended`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/16/56/film_kodak_cut_lawn_engine_machine_testing_gas-281930.jpg!d`,
	},
	{
		word: `rake`,
		translation: `grable`,
		level: `extended`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/d0/10/cat_cats_kitten_kittens_dressed_clothed_cute_vintage-1341062.jpg!d`,
	},
	{
		word: `rubber gloves`,
		translation: `gumowe rękawiczki`,
		level: `extended`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/58/92/gloves_rubber_black_hygiene_glove_housework_clean_latex-976180.jpg!d`,
	},
	{
		word: `spade`,
		translation: `szpadel`,
		level: `extended`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/2a/b6/gardening_gardener_nursery_landscape_gardener_spade_ground_breaking_ceremony_work_tool-1103633.jpg!d`,
	},
	{
		word: `trowel`,
		translation: `rydel`,
		level: `extended`,
		type: `household and garden jobs`,
		image: `https://c.pxhere.com/photos/a6/b7/kitchen_garden_garden_gardening_bloom_plants_shovel_sand_growing-855333.jpg!d`,
	},
];

export default words3_HouseholdAndGardenJobs