const words5_Orther = [
	{
		word1: `affordable`,
		translation1: `w przystępnej cenie`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/d4/c0/wallet_cash_credit_card_pocket_money_purse_leather_male-1295415.jpg!d`,
	},
	{
		word1: `beyond`,
		translation1: `poza`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/c5/74/beyond_death_life_after_death_life_eternal_mystical_transcendence_end_believe-881864.jpg!d`,
	},
	{
		word1: `complain`,
		translation1: `skarżyć się`,
		translation2: `narzekać`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/images/e7/2e/1d78b2335eb7f703b18461141619-1582697.jpg!d`,
	},
	{
		word1: `embellish`,
		translation1: `upiększyć`,
		translation2: `podkolorować`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/14/92/lipstick_lipgloss_lip_gloss_lips_red_woman_young_girl-723119.jpg!d`,
	},
	{
		word1: `fully furnished`,
		translation1: `w pełni umeblowany`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/9b/39/nyc_newyorkcity_ny_newyork_library_nypl_newyorkpubliclibrary_fifthavenue-423826.jpg!d`,
	},
	{
		word1: `keep your eyes on`,
		translation1: `nie spuszczać z oczu (kogoś / czegoś)`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/images/7b/4f/fb39e93920f4317639d424c3975c-1454579.jpg!d`,
	},
	{
		word1: `miss`,
		translation1: `tęsknić za`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/82/28/danbo_figure_separated_miss_disc_sad_longing_cute-1209026.jpg!d`,
	},
	{
		word1: `nearby`,
		translation1: `w pobliżu`,
		translation2: `pobliski`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/d3/d1/interior_wc_rendering_visualization_architecture_visualization_3d_architectural_visualization_landscape-1059685.jpg!d`,
	},
	{
		word1: `rough`,
		translation1: `niebezpieczny`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/ee/e0/elephant_trunk_skin_care_big_african_endangered_huge_gray-571527.jpg!d`,
	},
	{
		word1: `sharp`,
		translation1: `ostry`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/ed/b5/sword_victory_triumph_weapon_war_warrior_knight_courage-1074836.jpg!d`,
	},
	{
		word1: `sigh`,
		translation1: `wzdychać`,
		translation2: `westchnienie`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/09/cd/girl_headache_pain_sadness_concentration_thinking_stressed_despair-778587.jpg!d`,
	},
	{
		word1: `stare at`,
		translation1: `wpatrywać się w`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/a5/94/man_eyes_portrait_face_male_beautiful_model_nose-962011.jpg!d`,
	},
	{
		word1: `sulk`,
		translation1: `dąsać się`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/3a/67/family_lover_adult_bedroom_jealousy_unhappy_sex_asia-1271257.jpg!d`,
	},
	{
		word1: `tiny`,
		translation1: `maleńki`,
		translation2: `niewielki`,
		level: `basic`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/cf/17/chick_bird_tiny_baby_hatchling-68549.jpg!d`,
	},
	// // // -extended
	{
		word1: `be off your head`,
		translation1: `być szalonym`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/5a/30/football_soccer_fans_football_craze_orange-693467.jpg!d`,
	},
	{
		word1: `blurry`,
		translation1: `nieostry`,
		translation2: `zamazany`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/03/75/bokeh_pattern_photoshop_blur_focus_wet_rain_glass-648001.jpg!d`,
	},
	{
		word1: `bump into`,
		translation1: `wpaść na kogoś`,
		translation2: `spotkać kogoś przypadkiem`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/17/5b/odyssey-221673.jpg!d`,
	},
	{
		word1: `get into`,
		translation1: `wsiąść`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/16/c1/waiting_taxi_cab_yellow_girl_woman_people_standing-698780.jpg!d`,
	},
	{
		word1: `kick up a fuss`,
		translation1: `zrobić awanturę`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/bb/ce/suit_business_man_business_man_male_person_white_adult-894428.jpg!d`,
	},
	{
		word1: `rambling`,
		translation1: `pełen zakamarków`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/24/52/hiker_walker_rambler_lego_walk_explore_trek_hiking-1281059.jpg!d`,
	},
	{
		word1: `run-down`,
		translation1: `zniszczony`,
		translation2: `podupadły`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/2f/b6/monster_devil_fear_mask_horror_terrible_anxiety_the_cruel-915379.jpg!d`,
	},
	{
		word1: `snug`,
		translation1: `przytulny`,
		translation2: `zaciszny`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/76/cf/speakeasy_snug_chair_coffee_table_interior-47187.jpg!d`,
	},
	{
		word1: `solitude`,
		translation1: `samotność`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/images/09/aa/f7a1eee82aebe4c7e28fa80e247a-1435531.jpg!d`,
	},
	{
		word1: `squashed`,
		translation1: `wciśnięty`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/73/1c/hand_button_monitor_finger_touch_computer_web_design_contact-1209692.jpg!d`,
	},
	{
		word1: `stain`,
		translation1: `plama`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/09/de/hunger_hungry_eating_cookie_biscuit_cracker_people_snack-946992.jpg!d`,
	},
	{
		word1: `stream in`,
		translation1: `wlewać się`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/images/d8/8d/966289b688c11694aa0bdbf2ff87-1576673.jpg!d`,
	},
	{
		word1: `stumble upon`,
		translation1: `natknąć się na`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/a4/92/boys_outdoor_thailand_baby_agriculture_mammal_the_lawn_nationals_of_indonesia-1025984.jpg!d`,
	},
	{
		word1: `turn into`,
		translation1: `zmienić się w`,
		translation2: `przeobrazić się w`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/a5/72/kiss_the_frog_prince_fairy_tales_kiss_frog_funny_figure-826609.jpg!d`,
	},
	{
		word1: `turn up for`,
		translation1: `pojawić się na`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/9d/2d/sony_textures_snowdrops_flowery_a700_2013_nosignofspring-327072.jpg!d`,
	},
	{
		word1: `wrapped up in`,
		translation1: `pochłonięty czymś`,
		level: `extended`,
		type: `inne`,
		image: `https://c.pxhere.com/photos/1d/84/whiteboard_man_presentation_write_display_explain_strategy_diagram-871994.jpg!d`,
	},
];

export default words5_Orther