const words5_ZjawiskaPogodowe = [
    {
        word: `атмосфе́рное давле́ние`,
        translation: `ciśnienie atmosferyczne`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/6d/de/c694444bd5d098009e7cbdb8b8db-1424205.jpg!s`,
    },
    {
        word: `ве́тер`,
        translation: `wiatr`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/7a/6c/644e34cce0ccb1ec6798106c0da6-1574345.jpg!s`,
    },
    {
        word: `поры́вистый`,
        translation: `porywisty`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/74/1c/wave_atlantic_pacific_ocean_huge_large_blue_dark_blue-1162238.jpg!s`,
    },
    {
        word: `спа́вый`,
        translation: `słaby`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/02/b1/air_bag_wind_sock_weather_sky_striped_wind_direction_red_windy-799443.jpg!s`,
    },
    {
        word: `си́льный`,
        translation: `silny`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/27/cc/c61370c2a8fd2057f8d72bdc4c7c-1418477.jpg!s`,
    },
    {
        word: `ю́жный`,
        translation: `południowy`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/27/cc/c61370c2a8fd2057f8d72bdc4c7c-1418477.jpg!s`,
    },
    {
        word: `вла́жность`,
        translation: `wilgotność`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/f1/9a/water_drop_splash_h2o_rain_dew_medical_pure-1105711.jpg!s`,
    },
    {
        word: `гололе́дица`,
        translation: `gołoledź`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/3d/03/2e4e71851301107e0cd0787791c2-1422179.jpg!s`,
    },
    {
        word: `гроза́`,
        word2: `бу́ря`,
        translation: `burza`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/c8/10/thunderstorm_flashes_night_weather_sky_forward_nature_storm-1438107.jpg!s`,
    },
    {
        word: `гром`,
        translation: `grzmot`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/03/94/storm_lightning_cloud_night_dark-9314.jpg!s`,
    },
    {
        word: `греми́т`,
        translation: `grzmi`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/b3/7f/2d29017c074ac4ebf0fd806a4021-1449379.jpg!s`,
    },
    {
        word: `жара́`,
        translation: `upał`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/5d/66/camel_bored_dusty_boredom_desert_head_watching_sand-681666.jpg!s`,
    },
    {
        word: `мо́лния`,
        translation: `błyskawica`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/37/24/lightning_bolt_lightning_power_storm_thunder_flash_weather_vibrant-725473.jpg!s`,
    },
    {
        word: `сверка́ет`,
        translation: `błyska się`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/81/a5/lightning_storm_night_firebird_hortob_gy-968296.jpg!s`,
    },
    {
        word: `моро́з`,
        translation: `mróz`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/d4/da/a234177bb608d230976042b7d803-1586521.jpg!s`,
    },
    {
        word: `о́блачность`,
        translation: `zachmurzenie`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/02/14/gray_clouds_thunderstorm_storm_clouds_rain_clouds_cloud_cover_weather_rain_covered-888724.jpg!s`,
    },
    {
        word: `оса́дки`,
        translation: `opady`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/8e/9e/snowfall_winter_snow_snowflakes_flakes_snowing_cold_white-1010135.jpg!s`,
    },
    {
        word: `град`,
        translation: `grad`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `дождь`,
        translation: `deszcz`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `кратковре́менный`,
        translation: `krótkotrwały`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `морося́щий`,
        translation: `mżawka`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `проливно́й`,
        translation: `ulewny`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `си́льный`,
        translation: `silny`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `сла́вый`,
        translation: `słaby`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `мете́ль`,
        translation: `śnieżyca`,
        translation2: `zamieć`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `снег`,
        translation: `śnieg`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `снегона́д`,
        translation: `opady śniegu`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `тума́н`,
        translation: `mgła`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `пого́да`,
        translation: `pogoda`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `ве́треная`,
        translation: `wietrzna`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `дождли́вая (сне́жная)`,
        translation: `deszczowa (śnieżna)`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `моро́зная`,
        translation: `mroźna`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `о́влачная с проясне́ниями`,
        translation: `pochmurna z przejaśnieniami`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `на́смурная (о́влачная)`,
        translation: `pochmurna`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `пере́менная`,
        translation: `zmienna`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `плоха́я`,
        translation: `zła`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `хоро́шая`,
        translation: `dobra`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `со́лнечная (я́сная)`,
        translation: `słoneczna`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `ра́дуга`,
        translation: `tęcza`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `темрерату́ра`,
        translation: `temperatura`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `ту́ча`,
        translation: `chmura`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
    {
        word: `урага́н`,
        translation: `huragan`,
        type: `zjawiska pogodowe`,
        image: `url`,
    },
]

export default words5_ZjawiskaPogodowe