const words5_ZjawiskaPogodowe = [
    {
        word: `атмосфе́рное давле́ние`,
        translation: `ciśnienie atmosferyczne`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/6d/de/c694444bd5d098009e7cbdb8b8db-1424205.jpg!s`,
    },
    {
        word: `ве́тер`,
        translation: `wiatr`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/7a/6c/644e34cce0ccb1ec6798106c0da6-1574345.jpg!s`,
    },
    {
        word: `поры́вистый`,
        translation: `porywisty`,
        type: `zjawiska pogodowe`,
        subtype: `wiatr`,
        image: `https://c.pxhere.com/photos/74/1c/wave_atlantic_pacific_ocean_huge_large_blue_dark_blue-1162238.jpg!s`,
    },
    {
        word: `спа́вый`,
        translation: `słaby`,
        type: `zjawiska pogodowe`,
        subtype: `wiatr`,
        image: `https://c.pxhere.com/photos/02/b1/air_bag_wind_sock_weather_sky_striped_wind_direction_red_windy-799443.jpg!s`,
    },
    {
        word: `си́льный`,
        translation: `silny`,
        type: `zjawiska pogodowe`,
        subtype: `wiatr`,
        image: `https://c.pxhere.com/images/27/cc/c61370c2a8fd2057f8d72bdc4c7c-1418477.jpg!s`,
    },
    {
        word: `ю́жный`,
        translation: `południowy`,
        type: `zjawiska pogodowe`,
        subtype: `wiatr`,
        image: `https://c.pxhere.com/images/27/cc/c61370c2a8fd2057f8d72bdc4c7c-1418477.jpg!s`,
    },
    {
        word: `вла́жность`,
        translation: `wilgotność`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/f1/9a/water_drop_splash_h2o_rain_dew_medical_pure-1105711.jpg!s`,
    },
    {
        word: `гололе́дица`,
        translation: `gołoledź`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/3d/03/2e4e71851301107e0cd0787791c2-1422179.jpg!s`,
    },
    {
        word: `гроза́`,
        word2: `бу́ря`,
        translation: `burza`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/c8/10/thunderstorm_flashes_night_weather_sky_forward_nature_storm-1438107.jpg!s`,
    },
    {
        word: `гром`,
        translation: `grzmot`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/03/94/storm_lightning_cloud_night_dark-9314.jpg!s`,
    },
    {
        word: `греми́т`,
        translation: `grzmi`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/b3/7f/2d29017c074ac4ebf0fd806a4021-1449379.jpg!s`,
    },
    {
        word: `жара́`,
        translation: `upał`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/5d/66/camel_bored_dusty_boredom_desert_head_watching_sand-681666.jpg!s`,
    },
    {
        word: `мо́лния`,
        translation: `błyskawica`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/37/24/lightning_bolt_lightning_power_storm_thunder_flash_weather_vibrant-725473.jpg!s`,
    },
    {
        word: `сверка́ет`,
        translation: `błyska się`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/81/a5/lightning_storm_night_firebird_hortob_gy-968296.jpg!s`,
    },
    {
        word: `моро́з`,
        translation: `mróz`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/d4/da/a234177bb608d230976042b7d803-1586521.jpg!s`,
    },
    {
        word: `о́блачность`,
        translation: `zachmurzenie`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/02/14/gray_clouds_thunderstorm_storm_clouds_rain_clouds_cloud_cover_weather_rain_covered-888724.jpg!s`,
    },
    {
        word: `оса́дки`,
        translation: `opady`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/8e/9e/snowfall_winter_snow_snowflakes_flakes_snowing_cold_white-1010135.jpg!s`,
    },
    {
        word: `град`,
        translation: `grad`,
        type: `zjawiska pogodowe`,
        subtype: `opady`,
        image: `https://c.pxhere.com/photos/1b/59/hail_hailstones_weather_storm_precipitate_grass_rush-1098519.jpg!s`,
    },
    {
        word: `дождь`,
        translation: `deszcz`,
        type: `zjawiska pogodowe`,
        subtype: `opady`,
        image: `https://c.pxhere.com/photos/27/0f/water_priroda_drops_rain-715716.jpg!s`,
    },
    {
        word: `кратковре́менный`,
        translation: `krótkotrwały`,
        type: `zjawiska pogodowe`,
        subsubtype: `deszcz`,
        image: `https://c.pxhere.com/photos/3c/14/water_rain_drop_droplet_water_drop-92.jpg!s`,
    },
    {
        word: `морося́щий`,
        translation: `mżawka`,
        type: `zjawiska pogodowe`,
        subsubtype: `deszcz`,
        image: `https://c.pxhere.com/photos/95/7c/city_snow_nikon_cityscape_russia_moscow_cityscapes-281214.jpg!d`,
    },
    {
        word: `проливно́й`,
        translation: `ulewny`,
        type: `zjawiska pogodowe`,
        subsubtype: `deszcz`,
        image: `https://c.pxhere.com/photos/b4/f9/rain_background_drop_weather_water_storm_shower_falling-977184.jpg!s`,
    },
    {
        word: `си́льный`,
        translation: `silny`,
        type: `zjawiska pogodowe`,
        subsubtype: `deszcz`,
        image: `https://c.pxhere.com/photos/94/4e/heartbreak_heartbroken_stormy_relationship_sadness_love_sorrow_divorce_breakup-624694.jpg!d`,
    },
    {
        word: `сла́вый`,
        translation: `słaby`,
        type: `zjawiska pogodowe`,
        subsubtype: `deszcz`,
        image: `https://c.pxhere.com/photos/46/76/woman_young_rain_pond_background_pretty_beauty_cambodia-1026036.jpg!s`,
    },
    {
        word: `мете́ль`,
        translation: `śnieżyca`,
        translation2: `zamieć`,
        type: `zjawiska pogodowe`,
        subtype: `opady`,
        image: `https://c.pxhere.com/photos/82/89/blizzard_snow_flurry_snowflakes_snowfall_snow_storms_winter_cold_snow-1247234.jpg!s`,
    },
    {
        word: `снег`,
        translation: `śnieg`,
        type: `zjawiska pogodowe`,
        subtype: `opady`,
        image: `https://c.pxhere.com/images/c4/96/128e514557bad9de3b459cc43e43-1434005.jpg!s`,
    },
    {
        word: `снегона́д`,
        translation: `opady śniegu`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/f7/60/wintry_trees_snow_moon_snowfall_snow_flurry_schneestrum-767545.jpg!s`,
    },
    {
        word: `тума́н`,
        translation: `mgła`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/55/fe/90b7264e402241035856cd169d76-1418846.jpg!s`,
    },
    {
        word: `пого́да`,
        translation: `pogoda`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/c2/f8/ce8d3056dd9c9fbb243d859abe89-1446449.jpg!s`,
    },
    {
        word: `ве́треная`,
        translation: `wietrzna`,
        type: `zjawiska pogodowe`,
        subtype: `pogoda`,
        image: `https://c.pxhere.com/photos/50/e5/water_splash_sea_rock_wave-108960.jpg!s`,
    },
    {
        word: `дождли́вая`,
        translation: `deszczowa`,
        type: `zjawiska pogodowe`,
        subtype: `pogoda`,
        image: `https://c.pxhere.com/photos/e5/97/rain_wet_drops_water_rainy_rainy_day_raindrops_solitude-985071.jpg!s`,
    },
    {
        word: `сне́жная`,
        translation: `śnieżna`,
        type: `zjawiska pogodowe`,
        subtype: `pogoda`,
        image: `https://c.pxhere.com/photos/5e/6d/winter_redhead_female_portrait_cold_girl_outdoor_hair-665561.jpg!s`,
    },
    {
        word: `моро́зная`,
        translation: `mroźna`,
        type: `zjawiska pogodowe`,
        subtype: `pogoda`,
        image: `https://c.pxhere.com/photos/01/d6/blizzard_snow_woman_winter_clothes_winter_scene_winter_cold_weather-554194.jpg!s`,
    },
    {
        word: `о́влачная с проясне́ниями`,
        translation: `pochmurna z przejaśnieniami`,
        type: `zjawiska pogodowe`,
        subtype: `pogoda`,
        image: `https://c.pxhere.com/photos/c0/4d/kumamoto_japan_aso_cloud_somma_sea_of_clouds_light_sun-771016.jpg!s`,
    },
    {
        word: `на́смурная`,
        word2: `о́влачная`,
        translation: `pochmurna`,
        type: `zjawiska pogodowe`,
        subtype: `pogoda`,
        image: `https://c.pxhere.com/photos/02/14/gray_clouds_thunderstorm_storm_clouds_rain_clouds_cloud_cover_weather_rain_covered-888724.jpg!s`,
    },
    {
        word: `пере́менная`,
        translation: `zmienna`,
        type: `zjawiska pogodowe`,
        subtype: `pogoda`,
        image: `https://c.pxhere.com/photos/27/39/thunderstorm_storm_rain_clouds_sky_thunder_weather_weather_phenomenon-962034.jpg!s`,
    },
    {
        word: `плоха́я`,
        translation: `zła`,
        type: `zjawiska pogodowe`,
        subtype: `pogoda`,
        image: `https://c.pxhere.com/photos/e8/6c/cry_bad_weather_rain_drip_smilies_sad-1196493.jpg!s`,
    },
    {
        word: `хоро́шая`,
        translation: `dobra`,
        type: `zjawiska pogodowe`,
        subtype: `pogoda`,
        image: `https://c.pxhere.com/photos/78/cc/leisure_fun_enjoyment_lifestyle_ocean-113103.jpg!s`,
    },
    {
        word: `со́лнечная`,
        word2: `я́сная`,
        translation: `słoneczna`,
        type: `zjawiska pogodowe`,
        subtype: `pogoda`,
        image: `https://c.pxhere.com/images/c6/ef/4a0c48c02b41dd592afa2be35098-1418560.jpg!s`,
    },
    {
        word: `ра́дуга`,
        translation: `tęcza`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/9d/c8/white_young_woman_in_embracing_rainbow-1041508.jpg!s`,
    },
    {
        word: `темрерату́ра`,
        translation: `temperatura`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/photos/fe/4f/thermometer_weather_mercury_temperature-1023822.jpg!s`,
    },
    {
        word: `ту́ча`,
        translation: `chmura`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/c2/98/b9e8f7f29138d420c718f7898229-1446069.jpg!s`,
    },
    {
        word: `урага́н`,
        translation: `huragan`,
        type: `zjawiska pogodowe`,
        image: `https://c.pxhere.com/images/49/4d/80250ebf8537582b3bfc457945c2-1448379.jpg!s`,
    },
]

export default words5_ZjawiskaPogodowe