const words1_SchoolSubjects = [
	{
		word:  `arts subjects`,
		translation: `przedmioty artystyczne`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/images/6b/85/9fd7c1588e3caf3cb4ca190028a2-1435453.jpg!s`,
	},
	{
		word:  `biology`,
		translation: `biologia`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/0f/81/whale_shark_shark_aquarium_water_jaws_scuba_diving_fish-1107871.jpg!s`,
	},
	{
		word:  `chemistry`,
		translation: `chemia`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/4d/a1/science_biology_test_tube_liquid_analysis_treat_treatment_screening-1412043.jpg!s`,
	},
	{
		word:  `double lesson`,
		translation: `podwójna lekcja`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/images/53/6e/112dc83d1c985973b2e639eb7e65-1446487.jpg!s`,
	},
	{
		word:  `foreign languages`,
		translation: `języki obce`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/4c/bd/manuscript_handwriting_old_pen_write_paper_ink_note-1057524.jpg!s`,
	},
	{
		word:  `geography`,
		translation: `geografia`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/9d/32/compass_navigation_map_direction_journey_travel_retro_geography-952741.jpg!s`,
	},
	{
		word:  `history`,
		translation: `historia`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/82/e1/knowledge_book_library_glasses_textbook_information_education_literature-840721.jpg!s`,
	},
	{
		word:  `humanities`,
		translation: `nauki humanistyczne`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/6b/32/odyssey-221938.jpg!s`,
	},
	{
		word:  `IT`,
		word2: `information technology`,
		translation: `informatyka`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/28/15/computer_laptop_technology_keyboard_computing_working_communication_wireless-1230856.jpg!s`,
	},
	{
		word:  `mathematics (maths)`,
		translation: `matematyka (matma)`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/19/26/accountant_accounting_adviser_advisor_arithmetic_assets_banking_bills-819795.jpg!s`,
	},
	{
		word:  `music`,
		translation: `muzyka`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/images/6d/51/5b2abb8d510aefb11d72a8cc3870-1435835.jpg!s`,
	},
	{
		word:  `PE`,
		word2: `psychical education`,
		translation: `WF`,
		translation2: `wychowanie fizyczne`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/bf/fa/frogs_athletes_football_tennis_golf_funny_cute_sport-1049884.jpg!s`,
	},
	{
		word:  `physics`,
		translation: `fizyka`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/d6/d7/star_trails_night_long_exposure_starlight_space_rotation_astronomy_starry-712354.jpg!s`,
	},
	{
		word:  `Polish`,
		translation: `język polski`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/69/a2/cemetery_europa_europe_poland_polska_warsaw_warszawa_cmentarz-461737.jpg!s`,
	},
	{
		word:  `religious education`,
		translation: `religia`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/31/eb/little_girl_praying_people_wishing_pray_religious_wish_worship-1265410.jpg!s`,
	},
	{
		word:  `science subjects`,
		translation: `przedmioty ścisłe`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/f4/cf/laboratory_chemistry_subjects_chemical_bottle_react_compounds_response-1062742.jpg!s`,
	},
	{
		word:  `social sciences`,
		translation: `nauki społeczne`,
		level: `basic`,
		type: `school subjects`,
		image: `https://c.pxhere.com/images/54/4b/be004a66602cbee3f524e9907855-1452889.jpg!s`,
	},
	// // //
	{
		word:  `design and technology`,
		translation: `technika`,
		level: `extended`,
		type: `school subjects`,
		image: `https://c.pxhere.com/images/0b/7f/0bee770c7189df751cca18501290-1575621.jpg!s`,
	},
	{
		word:  `economic education`,
		translation: `ekonomia`,
		level: `extended`,
		type: `school subjects`,
		image: `https://c.pxhere.com/images/11/c1/e02c2d2d734ed7fe0e4d51a575d5-1439121.jpg!s`,
	},
	{
		word:  `environmental science`,
		translation: `nauka o ochronie środowiska`,
		level: `extended`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/f1/a2/india_reuse_resources_woman_woman_looking_in_the_garbage_free_image-766271.jpg!s`,
	},
	{
		word:  `media studies`,
		translation: `medioznawstwo`,
		level: `extended`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/7c/c1/woman_face_head_question_mark_circle_tree_structure_networks-1242888.jpg!s`,
	},
	{
		word:  `sports psychology`,
		translation: `psychologią sportu`,
		level: `extended`,
		type: `school subjects`,
		image: `https://c.pxhere.com/photos/63/14/electrostimulation_sport_bless_you_wellness_beauty_diet_nutrition_physiotherapy-820138.jpg!s`,
	}
]

export default words1_SchoolSubjects