const words2_GradesAndCourseRequirements = [
	{
		word:  `cheat`,
		translation: `oszukiwać`,
		translation2: `ściągać`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `copy`,
		translation: `przepisać`,
		translation2: `skopiować`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `cram`,
		translation: `wkuwać`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `diploma`,
		translation: `dyplom`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `end-of-term exam`,
		translation: `egzamin semestralny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `end-of-year exam`,
		translation: `egzamin na koniec roku`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `exam paper`,
		translation: `arkusz egzaminacyjny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `examination`,
		translation: `egzamin`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `extra lessons`,
		translation: `dodatkowe lekcje`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `take an exam`,
		translation: `podejść do egzaminu`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `fail`,
		translation: `oblać`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `final exam`,
		translation: `egzamin końcowy`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `get caught`,
		translation: `zostać złapanym`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `get results`,
		translation: `otrzymywać wyniki`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `give marks`,
		translation: `wystawiać oceny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `go towards`,
		translation: `składać się na`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `grade`,
		word2: `mark`,
		translation: `ocena`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `memorise`,
		translation: `uczyć się na pamięć`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `mock`,
		word2: `practise exam`,
		translation: `egzamin próbny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `oral`,
		translation: `ustny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `pass`,
		translation: `zdać`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `past paper`,
		translation: `arkusz egzaminacyjny z poprzednich lat`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `practical`,
		translation: `praktyczny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `retake`,
		translation: `zdawać ponownie`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `revise for`,
		translation: `powtarzać do`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `school-leaving exam`,
		translation: `egzamin kończący naukę w szkole`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `send out`,
		translation: `wysyłać`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `take a test`,
		translation: `podejść do testu`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `test`,
		translation: `test`,
		translation2: `klasówka`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `written`,
		translation: `pisemny`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `A levels`,
		translation: `brytyjski odpowiednik matury`,
		translation2: `egzamin dojrzałości`, 
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `academic results`,
		translation: `wyniki w nauce`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `award`,
		translation: `nagroda`,
		translation2: `nagrodzić`, 
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `BA`,
		word2: `Bachelor of Arts`,
		translation: `licencjat na kierunku humanistycznym`,
		translation2: `licencjat sztuk pieknych`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `MA`,
		word2: `Masters of Arts`,
		translation: `magister nauk humanistycznych`, 
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `BSc`,
		word2: `Bachelor of Science`,
		translation: `licencjat w dziedzinie nauk ścisłych lub przyrodniczych`,
		translation2: `licencjat nauk ścisłych`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `certificate`,
		translation: `świadectwo`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `distinction`,
		translation: `wyróżnienie`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `GCSEs`,
		translation: `egzamin gimnazjalny`,
		translation2: `brytyjski odpowiednik egzaminu gimnazjalnego`, 
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `get a degree`,
		translation: `otrzymać stopień naukowy`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `graduate`,
		translation: `absolwent`,
		translation2: `zmęczony`, 
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `graduate from`,
		translation: `ukończyć (studia wyższe)`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `International Baccalaureate`,
		translation: `matura międzynarodowa`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `pass with flying colours`,
		translation: `zdać celująco`,
		translation2: `zdać śpiewająco`, 
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `scrape through`,
		translation: `z trudem przebrnąć (np. przez egzamin)`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	},
	{
		word:  `win a scholarship`,
		translation: `zdobyć stypendium`,
		level: `basic`,
		type: `oceny i wymagania`,
		image: `url`,
	}
]

export default words2_GradesAndCourseRequirements