const words3_SchoolLive = [
	{
		word:  `absent`,
		translation: `nieobecny`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `bell`,
		translation: `dzwonek`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `break`,
		translation: `przerwa`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `bully`,
		translation: `dręczyć`,
		translation2: `prześladować`, 
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `check your work`,
		translation: `sprawdzić swoją pracę`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `concentrate`,
		translation: `skupić się`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `coursebook`,
		translation: `podręcznik`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `coursework`,
		translation: `praca okresowa`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `curriculum`,
		translation: `program nauczania`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `deadline`,
		translation: `termin do wykonania pracy`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `dictation`,
		translation: `dyktando`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `do your homework`,
		translation: `odrabiać lekcje`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `do research`,
		translation: `poszukiwać informacji`,
		translation2: `prowadzić badania`, 
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `do an assignment`,
		translation: `wykonać zadaną pracę`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `write an assignment`,
		translation: `napisać zadaną pracę`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `do an essay`,
		word2: `write an essay`,
		translation: `napisać wypracowanie`,
		translation2: `napisać esej`, 
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `get suspended`,
		translation: `zostać zawieszonym`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `give a presentation`,
		translation: `przedstawiać prezentację`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `give a talk on`,
		translation: `wygłosić referat na temat`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `hand in homework`,
		translation: `oddać pracę domową`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `lunch break`,
		translation: `przerwa na lunch`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `learning style`,
		translation: `styl uczenia się`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `make mistakes`,
		translation: `robić błędy`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `miss lessons`,
		translation: `opuszczać lekcje`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `motivate`,
		translation: `motywować`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `motivating`,
		translation: `motywujący`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `notebook`,
		translation: `zeszyt`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `packed lunch`,
		translation: `drugie śniadanie`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `PE kit`,
		translation: `strój sportowy`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `play truant`,
		translation: `wagarować`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `present`,
		translation: `prezentować`,
		translation2: `obecny`, 
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `project work`,
		translation: `peas projektowa`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `report someone`,
		translation: `zgłosić kogoś`,
		translation2: `donieść na kogoś`, 
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `set homework`,
		translation: `zadawać pracę`,
		translation2: `zadawać pracę domową`, 
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `sick note`,
		translation: `zwolnienie z powodu choroby (np. z WF-u)`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `school bus`,
		translation: `autobus szkolny`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `school year`,
		translation: `rok szkolny`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `take a gap year`,
		translation: `zrobić sobie rok przerwy między szkołą średnią a studiami`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `take notes`,
		translation: `robić notatki`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `term`,
		translation: `semestr`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `timetable`,
		translation: `plan zajęć`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `work on a project`,
		translation: `pracować nad projektem`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `work in pairs`,
		translation: `pracować w parach`,
		level: `basic`,
		type: `życie szkolne`,
		image: `url`,
	},
	// // //
	{
		word:  `absentee`,
		translation: `osoba nieobecna`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `absenteeism`,
		translation: `absencja`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `assembly`,
		translation: `zgromadzenie`,
		translation2: `apel`, 
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `attendance`,
		translation: `obecność na zajęciach`,
		translation2: `frekwencja`, 
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `compulsory`,
		translation: `obowiązkowy`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `concentration span`,
		translation: `czas skupienia uwagi`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `cut classes`,
		translation: `urwać się z lekcji`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `detention`,
		translation: `kara polegająca na zatrzymywaniu ucznia w szkole po lekcjach`,
		translation2: `aresztowanie`, 
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `forge`,
		translation: `podrabiać`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `free period`,
		translation: `wolna lekcja`,
		translation2: `okienko`, 
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `obligatory`,
		translation: `obowiązkowy`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `old student`,
		translation: `były uczeń`,
		translation2: `była uczennica`, 
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `optional`,
		translation: `opcjonalny`,
		translation2: `dobrowolny`, 
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `prize-giving`,
		translation: `rozdanie nagród`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `punctuality`,
		translation: `punktualność`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `take the register`,
		translation: `sprawdzać`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `take time off`,
		translation: `wziąć wolne`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	{
		word:  `tutorial`,
		translation: `konsultacje`,
		level: `extended`,
		type: `życie szkolne`,
		image: `url`,
	},
	// // // // // -people
	{
		word:  `caretaker`,
		translation: `woźny`,
		translation2: `woźna`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word:  `classmate`,
		translation: `kolega z klasy`,
		translation2: `koleżanka z klasy`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word:  `classroom assistant`,
		translation: `asystent nauczyciela`,
		translation2: `asystentka nauczyciela`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word:  `form tutor`,
		translation: `wychowawca`,
		translation2: `wychowawczyni`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word:  `head teacher`,
		translation: `dyrektor szkoły`,
		translation2: `dyrektorka szkoły`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word:  `pupil`,
		translation: `uczeń`,
		translation2: `uczennica`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word:  `staff`,
		translation: `grono pedagogiczne`,
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word:  `student`,
		translation: `uczeń`,
		translation2: `uczennica`,
		translation3: `student`,
		translation4: `studentka`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word:  `teacher`,
		translation: `nauczyciel`,
		translation2: `nauczycielka`, 
		level: `basic`,
		type: `ludzie`,
		image: `url`,
	},
	// // // -e people
	{
		word:  `careers adviser`,
		translation: `doradca zawodowy`,
		level: `extended`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word:  `deputy head`,
		translation: `wicedyrektor`,
		translation2: `wicedyrektorka`, 
		level: `extended`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word:  `head girl`,
		word2: `head boy`, 
		translation: `przewodnicząca samorządu szkolnego`,
		translation2: `przewodniczący samorządu szkolnego`, 
		level: `extended`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word:  `lecturer`,
		translation: `wykładowca`,
		level: `extended`,
		type: `ludzie`,
		image: `url`,
	},
	{
		word:  `perfect`,
		translation: `gospodarz`,
		translation2: `przewodniczący klasy`, 
		level: `extended`,
		type: `ludzie`,
		image: `url`,
	},
	// // // // // -miejsca w szkole
	{
		word:  `canteen`,
		translation: `stołówka`,
		translation2: `bufet`, 
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word:  `classroom`,
		translation: `salsa lekcyjna`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word:  `common room`,
		translation: `świetlica`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word:  `corridor`,
		translation: `korytarz`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word:  `gymnasium`,
		translation: `sala gimnastyczna`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word:  `head teacher's office`,
		translation: `gabinet dyrektora szkoły`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word:  `laboratory`,
		translation: `pracownia (fizyczna lub chemiczna)`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word:  `library`,
		translation: `biblioteka`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word:  `playground`,
		translation: `boisko`,
		translation2: `plac zabaw`, 
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word:  `sports field`,
		translation: `boisko`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word:  `staffroom`,
		translation: `pokój nauczycielski`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	},
	{
		word:  `lecture theatre`,
		translation: `aula`,
		level: `basic`,
		type: `miejsca w szkole`,
		image: `url`,
	}
]

export default words3_SchoolLive