const words4_ExtracurricularActivities = [
	{
		word:  `attend a course`,
		translation: `uczęszczać na kurs`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `belong to`,
		translation: `należeć do`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `charity event`,
		translation: `impreza charytatywna`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `club`,
		translation: `klub`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `exchange trip`,
		translation: `wycieczka w w ramach wymiany międzyszkolnej`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `extracurricular activities`,
		translation: `zajęcia pozalekcyjne`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `fundraising event`,
		translation: `impreza zorganizowana w celu zbierania funduszy`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `take part in`,
		translation: `brać udział w`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `join a club`,
		word2: `join a society`,
		translation: `dołączyć do klubu`,
		translation2: `dołączyć do stowarzyszenia`, 
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `member`,
		translation: `członek`,
		translation2: `członkini`, 
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `pay attention`,
		translation: `uważać`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `school trip`,
		translation: `wycieczka szkolna`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `society`,
		translation: `kółko`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `summer camp`,
		translation: `obóz letni`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `training`,
		translation: `szkolenie`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	},
	{
		word:  `voluntary work`,
		translation: `wolontariat`,
		level: `basic`,
		type: `extracurricular activities`,
		image: `url`,
	}
]

export default words4_ExtracurricularActivities