const words4_ExtracurricularActivities = [
	{
		word1:  `attend a course`,
		translation1: `uczęszczać na kurs`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `belong to`,
		translation1: `należeć do`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `charity event`,
		translation1: `impreza charytatywna`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `club`,
		translation1: `klub`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `exchange trip`,
		translation1: `wycieczka w w ramach wymiany międzyszkolnej`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `zajęcia pozalekcyjne`,
		translation1: `zajęcia pozalekcyjne`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `fundraising event`,
		translation1: `impreza (zorganizowana w celu zbierania funduszy)`,
		translation2: `impreza do zbierania funduszy`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `take part in`,
		translation1: `brać udział w`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `join a club`,
		word2: `join a society`,
		translation1: `dołączyć do klubu`,
		translation2: `dołączyć do stowarzyszenia`, 
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `member`,
		translation1: `członek`,
		translation2: `członkini`, 
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `pay attention`,
		translation1: `uważać`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `school trip`,
		translation1: `wycieczka szkolna`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `society`,
		translation1: `kółko`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `summer camp`,
		translation1: `obóz letni`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `training`,
		translation1: `szkolenie`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	},
	{
		word1:  `voluntary work`,
		translation1: `wolontariat`,
		level: `basic`,
		type: `zajęcia pozalekcyjne`,
		image: `url`,
	}
]

export default words4_ExtracurricularActivities