const words5_EducationSystem = [
	{
		word1:  `academy`,
		translation1: `uczelnia`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `coeducational school`,
		translation1: `szkoła koedukacyjna`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `college`,
		translation1: `kolegium`,
		translation2: `szkoła pomaturalna`, 
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `comprehensive school`,
		translation1: `szkoła ogólnokształcąca (przyjmująca wszystkich uczniów, niezależnie od ich wyników w nauce)`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `do vocational training`,
		translation1: `uczyć się zawodu`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `elementary school`,
		word2:  `primary school`,
		translation1: `szkoła podstawowa`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `grammar school`,
		translation1: `szkoła średnia (przyjmująca uczniów, którzy zdali egzamin wstępny)`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `high school`,
		translation1: `szkoła średnia`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `independent school`,
		translation1: `szkoła prywatna`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `junior high school`,
		translation1: `gimnazjum (w USA szkoła średnia dla uczniów 13-15 lat)`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `kindergarten`,
		translation1: `przedszkole`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `nursery`,
		translation1: `żłobek`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `private school`,
		translation1: `szkoła prywatna`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `secondary school`,
		translation1: `szkoła średnia`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `single-sex school`,
		translation1: `szkoła żeńska`,
		translation2: `szkoła męska`, 
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `state school`,
		translation1: `szkoła państwowa`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `university`,
		translation1: `uniwersytet`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	// // // -extended
	{
		word1:  `boarding school`,
		translation1: `szkoła z internatem`,
		level: `extended`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `public school system`,
		translation1: `sieć szkół prywatnych`,
		level: `extended`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `school fees`,
		translation1: `czesne`,
		level: `extended`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `serve an apprenticeship`,
		translation1: `odbyć praktyki`,
		level: `extended`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `steam`,
		translation1: `dzielić uczniów na grupy (ze względu na umiejętności)`,
		level: `extended`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word1:  `workshop`,
		translation1: `warsztat`,
		level: `extended`,
		type: `system oświaty`,
		image: `url`,
	}
]

export default words5_EducationSystem