const words5_EducationSystem = [
	{
		word:  `academy`,
		translation: `uczelnia`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `coeducational school`,
		translation: `szkoła koedukacyjna`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `college`,
		translation: `kolegium`,
		translation2: `szkoła pomaturalną`, 
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `comprehensive school`,
		translation: `szkoła ogólnokształcąca (przyjmująca wszystkich uczniów, niezależnie od ich wyników w nauce)`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `do vocational training`,
		translation: `uczyć się zawodu`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `elementary school`,
		translation: `szkoła podstawowa`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `grammar school`,
		translation: `szkoła średnia (przyjmująca uczniów, którzy zdali egzamin wstępny)`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `high school`,
		translation: `szkoła średnia`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `independent school`,
		translation: `szkoła prywatna`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `junior high school`,
		translation: `gimnazjum (w USA szkoła średnia dla uczniów 13-15 lat)`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `kindergarten`,
		translation: `przedszkole`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `nursery`,
		translation: `żłobek`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `primary school`,
		translation: `szkoła podstawowa`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `private school`,
		translation: `szkoła prywatna`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `secondary school`,
		translation: `szkoła średnia`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `single-sex school`,
		translation: `szkoła żeńska`,
		translation2: `szkoła męska`, 
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `state school`,
		translation: `szkoła państwowa`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `university`,
		translation: `uniwersytet`,
		level: `basic`,
		type: `system oświaty`,
		image: `url`,
	},
	// // // -extended
	{
		word:  `boarding school`,
		translation: `szkoła z internatem`,
		level: `extended`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `public school system`,
		translation: `sieć szkół prywatnych`,
		level: `extended`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `school fees`,
		translation: `czesne`,
		level: `extended`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `serve an apprenticeship`,
		translation: `odbyć praktyki`,
		level: `extended`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `steam`,
		translation: `dzielić uczniów na grupy (ze względu na umiejętności)`,
		level: `extended`,
		type: `system oświaty`,
		image: `url`,
	},
	{
		word:  `workshop`,
		translation: `warsztat`,
		level: `extended`,
		type: `system oświaty`,
		image: `url`,
	}
]

export default words5_EducationSystem