const words6_Orther = [
	{
		word: `concerned`,
		translation: `zaniepokojony`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `confused`,
		translation: `zdezorientowany`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `disappointed`,
		translation: `rozczarowany`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `elicit`,
		translation: `wydobyć`,
		translation2: `uzyskać`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `emphasise`,
		translation: `podkreślić`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `enforce`,
		translation: `narzucić`,
		translation2: `wymusić`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `ensure`,
		translation: `zapewnić`,
		translation2: `upewnić się`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `fimiliar`,
		translation: `znajomy`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `frightened`,
		translation: `przerażony`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `impressed`,
		translation: `pod wrażeniem`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `in favour of`,
		translation: `na korzyść (czegoś)`,
		translation2: `za (czymś)`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `let loose`,
		translation: `uwolnić`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `live up to expectations`,
		translation: `spełnić oczekiwania`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `lose count of`,
		translation: `stracić rachubę (czegoś)`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `maniac`,
		translation: `szaleniec`,
		translation2: `maniak`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `put a plain into action`,
		translation: `wprowadzić plan w życie`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `rates`,
		translation: `ceny`,
		translation2: `stawki`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `stuffy`,
		translation: `duszny`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `the far end`,
		translation: `przeciwległy koniec`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `way too`,
		translation: `o wiele za`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `work surface`,
		translation: `powierzchnia robocza`,
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	// // // -e orther
	{
		word: `be in two mins (about)`,
		translation: `nie móc się zdecydować`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `cater for`,
		translation: `zaspokajać`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `crave`,
		translation: `pragnąć`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `deserted`,
		translation: `opustoszały`,
		translation2: `bezludny`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `draw up`,
		translation: `podjechać`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `end up`,
		translation: `skoczyć (jesteś, jako ktoś)`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `face-to-face communication`,
		translation: `bezpośrednia komunikacja (twarzą w twarz)`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `in anticipation of`,
		translation: `oczekując (na coś)`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `maintain`,
		translation: `utrzymywać`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `memory aid`,
		translation: `technika ułatwiająca zapamiętywanie`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `motivational speech`,
		translation: `przemówienie mające na celu zmotywowanie kadry zawodników do większego wysiłku`,
		translation2: `mowa motywacjna`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `opt for`,
		translation: `optować  za`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `outperform`,
		translation: `prześcignąć`,
		translation2: `pozostawić w tyle`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `panel`,
		translation: `zespół`,
		translation2: `ława`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `struggle`,
		translation: `wysilać się`,
		translation2: `usiłować`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `subdivide`,
		translation: `dzielić się na mniejsze grupy`,
		translation2: `grupować się`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `treasured`,
		translation: `cenny`,
		translation2: `ceniony`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word: `vote with your feet`,
		translation: `wyrazić niezadowolenie poprzez ostentacyjnie wyjście lub odejście / wystąpienie (np. z kina teatru, organizacji)`,
		translation2: `"głosować nogami"`,
		level: `extended`,
		type: `inne`,
		image: `url`,
	}
]

export default words6_Orther