const words6_Orther = [
	{
		word: `concerned`,
		translation: `zaniepokojony`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `confused`,
		translation: `zdezorientowany`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `disappointed`,
		translation: `rozczarowany`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `elicit`,
		translation: `wydobyć`,
		translation2: `uzyskać`, 
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `emphasise`,
		translation: `podkreślić`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `enforce`,
		translation: `narzucić`,
		translation2: `wymusić`, 
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `ensure`,
		translation: `zapewnić`,
		translation2: `upewnić się`, 
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `fimiliar`,
		translation: `znajomy`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `frightened`,
		translation: `przerażony`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `impressed`,
		translation: `pod wrażeniem`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `in favour of`,
		translation: `na korzyść (czegoś)`,
		translation2: `za (czymś)`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `let loose`,
		translation: `uwolnić`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `live up to expectations`,
		translation: `spełnić oczekiwania`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `lose count of`,
		translation: `stracić rachubę (czegoś)`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `maniac`,
		translation: `szaleniec`,
		translation2: `maniak`, 
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `basic`,
		type: `orther`,
		image: `url`,
	},
	// // // -e orther
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	{
		word: `słowo`,
		translation: `tłumaczenie`,
		level: `extended`,
		type: `orther`,
		image: `url`,
	},
	
];

export default words6_Orther