const words1_JobsAndResponsibilities = [
	{
		word: `accountant`,
		translation: `księgowy`,
		translation2: `księgowa`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `actor`,
		translation: `aktor`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `architect`,
		translation: `architekt`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `beautician`,
		translation: `kosmetyczka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `boss`,
		translation: `szef`,
		translation2: `szefowa`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `bus driver`,
		translation: `kierowca autobusu`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `cashier`,
		translation: `kasjer w banku`,
		translation2: `kasjerka w banku`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `chef`,
		translation: `szef kuchni`,
		translation2: `szefowa kuchni`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `computer programmer`,
		translation: `programista`,
		translation2: `programistka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `dentist`,
		translation: `dentysta`,
		translation2: `dentystka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `doctor`,
		translation: `lekarz`,
		translation2: `lekarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `economist`,
		translation: `ekonomista`,
		translation2: `ekonomistka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `electrician`,
		translation: `elektryk`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `farmer`,
		translation: `rolnik`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `fashion designer`,
		translation: `projektant mody`,
		translation2: `projektantka mody`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `film director`,
		translation: `reżyser`,
		translation2: `reżyserka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `firefighter`,
		translation: `strażak`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `flight attendant`,
		translation: `steward`,
		translation2: `stewardessa`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `hairdresser`,
		translation: `fryzjer`,
		translation2: `fryzjerka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `instructor`,
		translation: `instruktor`,
		translation2: `instruktorka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `journalist`,
		translation: `dziennikarz`,
		translation2: `dziennikarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `judge`,
		translation: `sędzia`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `lawyer`,
		translation: `prawnik`,
		translation2: `prawniczka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `lecturer`,
		translation: `wykładowca`,
		translation2: `wykładowczyni`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `librarian`,
		translation: `bibliotekarz`,
		translation2: `bibliotekarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `manager`,
		translation: `kierownik`,
		translation2: `kierowniczka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `mechanic`,
		translation: `mechanik`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `miner`,
		translation: `górnik`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `model`,
		translation: `model`,
		translation2: `modelka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `musician`,
		translation: `muzyk`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `nurse`,
		translation: `pielęgniarz`,
		translation2: `pielęgniarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `office assistant`,
		translation: `asystent biura`,
		translation2: `asystentka biura`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `painter`,
		translation: `malarz`,
		translation2: `malarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `paramedic`,
		translation: `ratownik medyczny`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `pharmacist`,
		translation: `aptekarz`,
		translation2: `aptekarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `photographer`,
		translation: `fotograf`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `pilot`,
		translation: `pilot`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `plumber`,
		translation: `hudraulik`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `police officer`,
		translation: `policjant`,
		translation2: `policjantka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `politician`,
		translation: `polityk`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `postman`,
		translation: `listonosz`,
		translation2: `listonoszka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `receptionist`,
		translation: `recepcjonista`,
		translation2: `recepcjonistka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `sales assistant`,
		translation: `sprzedawca`,
		translation2: `sprzedawczyni`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `sales representative`,
		translation: `reprezentant handlowy`,
		translation2: `reprezentantka handlowa`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `scientist`,
		translation: `naukowiec`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `secretary`,
		translation: `sekretarz`,
		translation2: `sekretarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `shop assistant`,
		translation: `sprzedawca`,
		translation2: `sprzedawczyni`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `solider`,
		translation: `żołnież`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `surgeon`,
		translation: `chirurg`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `teacher`,
		translation: `nauczyciel`,
		translation2: `nauczycielka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `travel agent`,
		translation: `pracownik biura podróży`,
		translation2: `pracownica biura podróży`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `TV presenter`,
		translation: `prezenter telewizyjny`,
		translation2: `prezenterka telewizyjna`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `vet`,
		translation: `lekarz weterynarii`,
		translation2: `lekarka weterynarii`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `waiter`,
		translation: `kelner`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `waitress`,
		translation: `kelnerka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `writer`,
		translation: `pisarz`,
		translation2: `pisarka`,
		level: `basic`,
		type: `jobs`,
		image: `url`,
	},
	// // // -extended
	{
		word: `carpenter`,
		translation: `stolarz`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `chief executive`,
		translation: `dyrektor generalny`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `comedian`,
		translation: `komik`,
		translation2: `aktor komediowy`,
		translation3: `aktorka komediowa`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `counsellor`,
		translation: `doradca`,
		translation2: `doradczyni`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `doorman`,
		translation: `portier`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `editor`,
		translation: `redaktor`,
		translation2: `redaktorka`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `graphic designer`,
		translation: `grafik`,
		translation2: `graficzka`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `handyman`,
		translation: `majster`,
		translation2: `złota rączka`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `nutritionist`,
		translation: `dietetyk`,
		translation2: `dietetyczka`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	{
		word: `psychiatrist`,
		translation: `psychiatra`,
		level: `extended`,
		type: `jobs`,
		image: `url`,
	},
	// // // // // -job expressions
	{
		word: `at work`,
		translation: `w pracy`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `be in charge of`,
		translation: `zarządzać`,
		translation2: `odpowiadać za`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `do something for a living`,
		translation: `utrzymywać się z czegoś`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `look for`,
		translation: `szukać`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `profession`,
		translation: `zawód (wymagający klasyfikacji i doświadczenia)`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `take responsibility for`,
		translation: `wziąć odpowiedzialność za`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `work`,
		translation: `praca (fizyczna lub umysłowa)`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `work as`,
		translation: `pracować jako`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `work for a company`,
		translation: `pracowac w firmie`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `work in (a hospital)`,
		translation: `pracować w (szpitalu)`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `work in an office`,
		translation: `pracować w biurze`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `work in sales`,
		translation: `pracować w dziale sprzedaży`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `work in a team`,
		translation: `pracować w zespole`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `work on`,
		translation: `pracować nad (czymś)`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `work under pressure`,
		translation: `pracować pod presją`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	{
		word: `work with`,
		translation: `pracować z (kimś)`,
		level: `basic`,
		type: `job expressions`,
		image: `url`,
	},
	// // // // // -job adjectives
	{
		word: `dangerous`,
		translation: `niebezpieczny`,
		level: `basic`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word: `manual`,
		translation: `fizyczny`,
		level: `basic`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word: `satisfying`,
		translation: `satycfakcjonujący`,
		level: `basic`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word: `skilled`,
		translation: `wymagający kwalifikacji`,
		level: `basic`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word: `stressful`,
		translation: `stresujący`,
		level: `basic`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word: `tiring`,
		translation: `męczący`,
		level: `basic`,
		type: `job adjectives`,
		image: `url`,
	},
	// // // -extended
	{
		word: `challenging`,
		translation: `ambitny`,
		translation2: `stanowiący wyzwanie`,
		level: `extended`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word: `dead-end`,
		translation: `bez perspektyw`,
		level: `extended`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word: `monotonous`,
		translation: `monotonny`,
		level: `extended`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word: `motivating`,
		translation: `motywujący`,
		level: `extended`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word: `rewarding`,
		translation: `satysfakcjonujący`,
		level: `extended`,
		type: `job adjectives`,
		image: `url`,
	},
	{
		word: `undemanding`,
		translation: `niewymagający`,
		translation2: `łatwy`,
		level: `extended`,
		type: `job adjectives`,
		image: `url`,
	}
]

export default words1_JobsAndResponsibilities