const words2_EmploymentAndWorkConditions = [
	{
		word: `badly-paid`,
		translation: `słabo płatny`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `bonus`,
		translation: `premia`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `career prospects`,
		translation: `perspektywy zawodowe`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `chance of promotion`,
		translation: `szansa na awans`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `change job`,
		translation: `zmienić pracę`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `colleagues`,
		translation: `koleżanki z pracy`,
		translation2: `koledzy z pracy`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `contact`,
		translation: `umowa`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `do overtime`,
		word2: `work overtime`,
		translation: `pracować w nadgodzinach`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `do shifts`,
		word2: `work shifts`,
		translation: `pracować na zmiany`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `duties`,
		translation: `obowiązki`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `earn money`,
		translation: `zarabiać pieniądze`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `earnings`,
		translation: `zarobki`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `full-time`,
		translation: `na pełen etat`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `get a job`,
		translation: `znaleźć pracę`,
		translation2: `dostać pracę`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `get a promotion`,
		word2: `get a promote`,
		translation: `dostać awans`,
		translation2: `dać awans`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `income`,
		translation: `dochód`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `leave your job`,
		translation: `odejść z pracy`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `paid leave`,
		translation: `płatny urlop`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `part-time`,
		translation: `na część etatu`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `pension`,
		translation: `emerytura`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `get a pension`,
		translation: `dostać emeryturę`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `per hour`,
		translation: `na godzinę`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `per week`,
		translation: `tygodniowo`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `per month`,
		translation: `miesięcznie`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `permanent`,
		translation: `stały (o pracy)`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `retire`,
		translation: `przejść na emeryturę`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `retirement`,
		translation: `emerytura`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `salary`,
		translation: `pensja`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `sick leave`,
		translation: `zwolnienie lekarskie`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `sick pay`,
		translation: `zasiłek chorobowy`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `tax`,
		translation: `podatek`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `teamwork`,
		translation: `praca zespołowa`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `temporary`,
		translation: `tymczasowy`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `tips`,
		translation: `napiwki`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `unpaid`,
		translation: `bezpłatny`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `well-paid`,
		translation: `dobrze płatny`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `work long hours`,
		translation: `pracować do późna`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `workplace`,
		translation: `miejsce pracy`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	// // //
	{
		word: `business trip`,
		translation: `podróż służbowa`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `do the graveyard shift`,
		translation: `pracować na nocną zmianę`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `expenses`,
		translation: `wydatki`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `get regular feedback`,
		translation: `regularnie otrzymywać informacje zwrotne (np. o swojej pracy)`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `have an appraisal`,
		translation: `odbyć rozmowę z szefem na temat osiągnięć i wyników pracy (o pracowniku)`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `hourly rate`,
		translation: `stawka godzinowa`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `job description`,
		translation: `zakres obowiązków`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `minimum wage`,
		translation: `płaca minimalna`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `pay into a pension scheme`,
		translation: `płacić na fundusz emerytalny`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `post rise (increase)`,
		translation: `podwyżka pensji`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `probation`,
		word2: `trial period`,
		translation: `okres próbny`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `productivity`,
		translation: `wydajność`,
		translation2: `efektywność`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `public holiday`,
		translation: `dzień ustawowo wolny od pracy`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `quit a job`,
		translation: `odejść z pracy`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `serve an apperticeship`,
		translation: `odbyć praktyki`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `sign a contract`,
		translation: `podpisać umowę`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `staff morale`,
		translation: `morale w zespole`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `take early retirement`,
		translation: `przejść na wcześniejszą emeryturę`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `take unpaid leave`,
		translation: `wziąć urlop bezpłatny`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `yearly appraisal`,
		translation: `roczna ocena pracownika`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word: `working conditions`,
		translation: `warunki pracy`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	}
]

export default words2_EmploymentAndWorkConditions