const words2_EmploymentAndWorkConditions = [
	{
		word1: `badly-paid`,
		translation1: `słabo płatny`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `bonus`,
		translation1: `premia`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `career prospects`,
		translation1: `perspektywy zawodowe`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `chance of promotion`,
		translation1: `szansa na awans`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `change job`,
		translation1: `zmienić pracę`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `colleagues`,
		translation1: `koleżanki z pracy`,
		translation2: `koledzy z pracy`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `contact`,
		translation1: `umowa`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `do overtime`,
		word2: `work overtime`,
		translation1: `pracować w nadgodzinach`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `do shifts`,
		word2: `work shifts`,
		translation1: `pracować na zmiany`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `duties`,
		translation1: `obowiązki`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `earn money`,
		translation1: `zarabiać pieniądze`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `earnings`,
		translation1: `zarobki`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `full-time`,
		translation1: `na pełen etat`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `get a job`,
		translation1: `znaleźć pracę`,
		translation2: `dostać pracę`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `get a promotion`,
		word2: `get a promote`,
		translation1: `dostać awans`,
		translation2: `dać awans`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `income`,
		translation1: `dochód`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `leave your job`,
		translation1: `odejść z pracy`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `paid leave`,
		translation1: `płatny urlop`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `part-time`,
		translation1: `na część etatu`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `pension`,
		translation1: `emerytura`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `get a pension`,
		translation1: `dostać emeryturę`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `per hour`,
		translation1: `na godzinę`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `per week`,
		translation1: `tygodniowo`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `per month`,
		translation1: `miesięcznie`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `permanent`,
		translation1: `stały (o pracy)`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `retire`,
		translation1: `przejść na emeryturę`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `retirement`,
		translation1: `emerytura`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `salary`,
		translation1: `pensja`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `sick leave`,
		translation1: `zwolnienie lekarskie`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `sick pay`,
		translation1: `zasiłek chorobowy`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `tax`,
		translation1: `podatek`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `teamwork`,
		translation1: `praca zespołowa`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `temporary`,
		translation1: `tymczasowy`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `tips`,
		translation1: `napiwki`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `unpaid`,
		translation1: `bezpłatny`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `well-paid`,
		translation1: `dobrze płatny`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `work long hours`,
		translation1: `pracować do późna`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `workplace`,
		translation1: `miejsce pracy`,
		level: `basic`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	// // //
	{
		word1: `business trip`,
		translation1: `podróż służbowa`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `do the graveyard shift`,
		translation1: `pracować na nocną zmianę`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `expenses`,
		translation1: `wydatki`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `get regular feedback`,
		translation1: `regularnie otrzymywać informacje zwrotne (np. o swojej pracy)`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `have an appraisal`,
		translation1: `odbyć rozmowę z szefem na temat osiągnięć i wyników pracy (o pracowniku)`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `hourly rate`,
		translation1: `stawka godzinowa`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `job description`,
		translation1: `zakres obowiązków`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `minimum wage`,
		translation1: `płaca minimalna`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `pay into a pension scheme`,
		translation1: `płacić na fundusz emerytalny`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `post rise (increase)`,
		translation1: `podwyżka pensji`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `probation`,
		word2: `trial period`,
		translation1: `okres próbny`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `productivity`,
		translation1: `wydajność`,
		translation2: `efektywność`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `public holiday`,
		translation1: `dzień ustawowo wolny od pracy`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `quit a job`,
		translation1: `odejść z pracy`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `serve an apperticeship`,
		translation1: `odbyć praktyki`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `sign a contract`,
		translation1: `podpisać umowę`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `staff morale`,
		translation1: `morale w zespole`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `take early retirement`,
		translation1: `przejść na wcześniejszą emeryturę`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `take unpaid leave`,
		translation1: `wziąć urlop bezpłatny`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `yearly appraisal`,
		translation1: `roczna ocena pracownika`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	},
	{
		word1: `working conditions`,
		translation1: `warunki pracy`,
		level: `extended`,
		type: `emloyment and work conditions`,
		image: `url`,
	}
]

export default words2_EmploymentAndWorkConditions