const words3_TemporaryWork = [
	{
		word: `au pair`,
		translation: `au pair`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `babysitter`,
		translation: `opiekun do dzieci`,
		translation: `opiekunka do dzieci`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `charity worker`,
		translation: `wolontariusz`,
		translation: `wolontariuszka`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `checkout assistant`,
		translation: `kasjer w supermarkecie`,
		translation: `kasjerka w supermarkecie`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `delivery boy`,
		translation: `roznosiciel gazet`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `delivery girl`,
		translation: `roznosicielka gazet`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `friut picking`,
		translation: `zbieranie owoców`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `holiday job`,
		translation: `praca wakacyjna`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `lifeguard`,
		translation: `ratownik`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `seasonal work`,
		translation: `praca sezonowa`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `summer camp supervisor`,
		translation: `opiekun na obozie`,
		translation: `opiekunka na obozie`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `summer job`,
		translation: `praca na lato`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `tour guide`,
		translation: `przewodnik`,
		translation: `przewodniczka`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `voluntary work`,
		translation: `wolontariat`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `wages`,
		translation: `płaca`,
		translation: `dniówka`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	},
	{
		word: `weekend job`,
		translation: `praca weekendowa`,
		level: `basic`,
		type: `temporary work`,
		image: `url`,
	}
]

export default words3_TemporaryWork