const words4_JobMarket = [
	{
		word: `advertise`,
		translation: `ogłaszać`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `applicant`,
		translation: `kandydat (do pracy)`,
		translation2: `kandydatka (do pracy)`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `application form`,
		translation: `formularz aplikacyjny`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `apply for a job`,
		translation: `ubiegać się o pracę`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `be fired`,
		translation: `zostać zwolnionym`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `be made redundant`,
		translation: `zostać zwolnionym w ramach rekrucji etatów`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `become employed`,
		translation: `zostać zatrudnionym`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `candidate`,
		translation: `kandydat`,
		translation2: `kandydatka`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `covering letter`,
		translation: `list motywacyjny`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `deadline`,
		translation: `termin wykonania pracy`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `do well`,
		translation: `dobrze sobie poradzić`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `employee`,
		translation: `pracownik`,
		translation2: `pracownica`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `employer`,
		translation: `pracodawca`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `enclose`,
		translation: `załączyć`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `entrepreneur`,
		translation: `przedsiębiorca`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `fill in`,
		translation: `wypełnić`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `find work`,
		translation: `znaleźć pracę`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `get careers edvice`,
		translation: `skorzystać z doradztwa zawodowego`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `go bankrupt`,
		translation: `zbankrutować`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `go freelance`,
		word2: `go freelancer`,
		translation: `zacząć pracować na własny rachunek`,
		translation2: `wolny strzelec`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `have an interview`,
		translation: `odbyć rozmowę kwalifikacyjną`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `have experience`,
		translation: `mieć doświadczenie`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `hire`,
		translation: `zatrudniać`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `human resources`,
		translation: `dział personalny`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `job offer`,
		translation: `oferta pracy`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `job satisfaction`,
		translation: `zadowolenie z wykonywanej pracy`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `Jobcentre`,
		translation: `biuro pośrednictwa pracy`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `keep a record`,
		translation: `prowadzić rejestr`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `lack of (experience)`,
		translation: `brak (doświadczenia)`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `lose your job`,
		translation: `stracić pracę`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `offer a job`,
		translation: `zaproponować pracę`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `out of work`,
		translation: `bez pracy`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `position`,
		translation: `praca`,
		translation2: `stanowisko`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `post`,
		translation: `stanowisko`,
		translation2: `posada`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `qualifications`,
		translation: `kwalifikacje`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `recruitment`,
		translation: `rekrutacja`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `reference`,
		translation: `referencje`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `reject`,
		translation: `odrzucić`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `resign`,
		translation: `złożyć rezygnację`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `run your own business`,
		translation: `prowadzić własną firmę`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `self-employed`,
		translation: `samozatrudniony`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `short list`,
		translation: `lista najpoważniejszych kandydatów`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `situations vacant`,
		translation: `oferty pracy (rubryka w gazecie)`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `staff`,
		translation: `personel`,
		translation2: `kadra`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `take up a job`,
		translation: `podjąć pracę`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `unemployed`,
		translation: `bezrobotny`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `up-to-date`,
		translation: `aktualny`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `vacancy`,
		translation: `wakat`,
		translation2: `wolne stanowisko`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `work from home`,
		translation: `pracować w domu`,
		level: `basic`,
		type: `job market`,
		image: `url`,
	},
	// // // -extended
	{
		word: `attach a CV`,
		translation: `załączyć CV`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `check out a company`,
		translation: `sprawdzić informacje o firmie`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `get in-house training`,
		translation: `przejść wewnętrzne szkolenie`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `get sacked`,
		translation: `zostać zwolnionym z pracy`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `go on strike`,
		translation: `strajkować`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `hand in your notice`,
		translation: `wręczyć wymówienie`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `hand over information`,
		translation: `przekazać informacje`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `have a complaints procedure`,
		translation: `mieć procedurę składania reklamacji`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `join a union`,
		translation: `zapisać się do związku zawodowego`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `sing on (the dole)`,
		translation: `zarejestrować się (jako bezrobotny)`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `start up a business`,
		translation: `założyć firmę`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `take on`,
		translation: `przyjąć`,
		translation2: `zatrudnić`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `take over from someone`,
		translation: `przejąć od kogoś obowiązki`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `take time off`,
		translation: `wziąć wolne`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `take up a position`,
		translation: `objąć stanowisko`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `take up a reference`,
		translation: `sprawdzić referencje kandydata`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	},
	{
		word: `work flextime`,
		translation: `mieć elastyczne godziny pracy`,
		level: `extended`,
		type: `job market`,
		image: `url`,
	}
]

export default words4_JobMarket