const words5_Orther = [
	{
		word: `ability`,
		translation: `zdolność`,
		translation2: `umiejętność`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `at some point`,
		translation: `w którymś momencie`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `consult`,
		translation: `konsultować (się)`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `drop out of`,
		translation: `rzucić`,
		translation2: `przerwać`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `fashionable`,
		translation: `modny`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `grumpy`,
		translation: `zrzędliwy`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `inheritance`,
		translation: `spadek`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `launch`,
		translation: `wprowadzić produkt na rynek`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `money-making`,
		translation: `dochodowy (o zawodzie)`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `routine`,
		translation: `rutyna`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `summarise`,
		translation: `podsumować`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `trendy`,
		translation: `trendy`,
		translation2: `modny`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `well-being`,
		translation: `dobre samopoczucie`,
		translation2: `dobrostan`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `wonder`,
		translation: `zastanawiać się`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	// // //
	{
		word: `body language`,
		translation: `język ciała`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `computer-generated`,
		translation: `zaprojektowany za pomocą komputera`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `contagious`,
		translation: `zaraźliwy`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `content`,
		translation: `zadowolony`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `devote oneself to`,
		translation: `poświęcić się (czemuś)`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `do something workwise`,
		translation: `robić coś w kwestiach zawodowych`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `emerge`,
		translation: `pojawić się`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `focus on`,
		translation: `skupić się na`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `go together`,
		translation: `pasować do siebie`,
		translation2: `iść ze sobą w parze`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `have no clue`,
		translation: `nie mieć pojęcia`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `last long`,
		translation: `przetrwać`,
		translation2: `utrzymać się`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `make the headlines`,
		translation: `trafić na czołówki gazet`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `money-minded`,
		translation: `dbający tylko o pieniądze`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `on top of`,
		translation: `poza`,
		translation2: `oprócz`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `positive thinking`,
		translation: `pozytywne myślenie`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `put something into practice`,
		translation: `zastosować coś w praktyce`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word: `technology-oriented`,
		translation: `zainteresowany techniką`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	}
]

export default words5_Orther