const words2_FromApp = [
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	},
	{
		firstForm: `pierwsza`,
		twiceForm: `druga`,
		thirdForm: `trzenia`,
		translation1: `tłumaczenie`,
		level: `rozszerzenie (z aplikacji)`,
		type: `extended`,
		image: `url`,
	}
]

export default words2_FromApp