const words3_Clothes = [
	{
		word1: `blouse`,
		translation1: `bluzka`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/0f/5d/stylish_beautiful_young_studio_shop_pants_posture_modern-558021.jpg!s`,
	},
	{
		word1: `boots`,
		translation1: `wysokie buty`,
		translation2: `kozaki`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/a4/64/boots_travel_track_architecture_shoe_see_love_friends-1416592.jpg!s`,
	},
	{
		word1: `bra`,
		translation1: `biustonosz`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/88/0d/female_woman_girl_lady_person_human_she_her-712103.jpg!s`,
	},
	{
		word1: `casual`,
		translation1: `codzienny`,
		translation2: `swobodny`,
		female: `yes`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/c4/a0/jeans_fashion_ruptured_modern_style_knee_comfy_pullover-712492.jpg!s`,
	},
	{
		word1: `coat`,
		translation1: `płaszcz`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/16/c1/waiting_taxi_cab_yellow_girl_woman_people_standing-698780.jpg!s`,
	},
	{
		word1: `dress`,
		translation1: `sukienka`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/2c/4f/sundress_summer_dress_girl_woman_legs_forest_nature_environment-971002.jpg!s`,
	},
	{
		word1: `fashionable`,
		translation1: `trendy`,
		translation2: `modny`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/d6/9d/shopping_mall_shop_windows_fashionable_clothes_feminine_weakness_the_temptation_slender_women_mannequin_lifestyle-1044785.jpg!s`,
	},
	{
		word1: `fleece`,
		translation1: `bluza polarowa`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/96/65/hitchhiker_thumb_hoodie_backpack_knapsack_guy_man_people-892425.jpg!s`,
	},
	{
		word1: `gloves`,
		translation1: `rękawiczki`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/2f/4a/cold_snow_fashion_woman_girl_winter_model_clothes-812312.jpg!s`,
	},
	{
		word1: `hat`,
		translation1: `kapelusz`,
		translation2: `czapka`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/images/e3/07/a6efd7df950c1f010ed92b21911f-1417790.jpg!s`,
	},
	{
		word1: `jacket`,
		translation1: `kurtka`,
		translation2: `marynarka`,
		translation3: `żakiet`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/dc/01/fashion_jacket_elegant_style_male_person_clothing_man-759722.jpg!s`,
	},
	{
		word1: `jumper`,
		translation1: `sweter`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/05/a5/sweater_jumper_knitwear_camera_nikon-185874.jpg!s`,
	},
	{
		word1: `old-fashioned`,
		translation1: `staromodny`,
		translation2: `staroświecki`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/b6/9a/females_pin_up_girl_fashion_people_image_glamour_elegance-606491.jpg!s`,
	},
	{
		word1: `pyjamas`,
		translation1: `piżama`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/c6/c0/christmas_kids_cookies_and_milk_christmas_xmas_cookies_pyjamas-839328.jpg!s`,
	},
	{
		word1: `sandals`,
		translation1: `sandały`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/08/e6/sandals_feet_red_nails_dress_floor_foot_woman_shoes-689599.jpg!s`,
	},
	{
		word1: `shirt`,
		translation1: `koszula`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/38/b5/man_male_person_business_businessman_shirt_necktie_clothing-880168.jpg!s`,
	},
	{
		word1: `shoes`,
		translation1: `buty`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/94/22/legs_window_car_dirt_road_relax_woman_nature_outdoor-939345.jpg!s`,
	},
	{
		word1: `shorts`,
		translation1: `szorty`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/8e/7c/cuba_havana_girl_legs_shorts_session_cafe_chair-591461.jpg!s`,
	},
	{
		word1: `skirt`,
		translation1: `spódnica`,
		translation2: `spódniczka`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/2c/08/fashion_skirt_boot_bag_handbag-1409074.jpg!s`,
	},
	{
		word1: `smart`,
		translation1: `elegancki`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/db/63/business_man_smartphone_phone_mobile_phone_busy_marketing_corporate-1187266.jpg!s`,
	},
	{
		word1: `socks`,
		translation1: `skarpety`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/a2/87/socks_hole_toe_hoax_greeting_card_smiley_assertive_force_good_mood-635803.jpg!s`,
	},
	{
		word1: `suit`,
		translation1: `garnitur`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/ff/7c/suit_tie_person_man_elegance-102798.jpg!s`,
	},
	{
		word1: `sweatshirt`,
		translation1: `bluza sportowa`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/d6/9d/woman_person_girl_hoodie_sweatshirt-140736.jpg!s`,
	},
	{
		word1: `tracksuit`,
		translation1: `dres`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/f2/c8/athlete_body_cinder_track_exercise_fitness_health_healthy_hobby-923537.jpg!s`,
	},
	{
		word1: `trainers`,
		translation1: `obuwie sportowe`,
		translation2: `trampki`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/21/07/legs_woman_girl_rest_chair_trainers_nike_footwear-1076123.jpg!s`,
	},
	{
		word1: `throusers`,
		translation1: `spodnie`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/23/e7/bonding_break_casual_chilling_college_colorful_connection_diversity-1373621.jpg!s`,
	},
	{
		word1: `underwear`,
		translation1: `bielizna`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/c8/6b/decollete_dekoltee_ipad_pad_tablet_x_ray_bosom_bra-487333.jpg!s`,
	},
	{
		word1: `waistcoat`,
		translation1: `kamizelka`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/49/00/street_city_people_man_blur_color_standing_train-368386.jpg!s`,
	},
	{
		word1: `wear`,
		translation1: `nosić`,
		translation2: `mieć na sobie`,
		level: `basic`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/49/69/person_female_back_outdoor_forest_fashion_wear_clothing-1226514.jpg!s`,
	},
	// // // -extended
	{
		word1: `ballgown`,
		translation1: `suknia balowa`,
		level: `extended`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/dd/34/baby_girl_ballerina_feathers_portrait_person_blue_eyes_skirt-732575.jpg!s`,
	},
	{
		word1: `boat-necked`,
		translation1: `z szerokim dekoltem (bluzka,sweter)`,
		level: `extended`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/a3/bd/taste_bodice_reinheitsgebot_section_bavaria_beer_pretzels_brunette-1281994.jpg!s`,
	},
	{
		word1: `cardigan`,
		translation1: `rozpinany sweter`,
		level: `extended`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/74/38/sparkler_holding_hands_firework_sparkles_fire_light_bright-1081678.jpg!s`,
	},
	{
		word1: `collar`,
		translation1: `kołnież`,
		translation2: `kołnieżyk`,
		level: `extended`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/0b/60/tie_fashion_elegant_style_elegance_accessory_male_bow_tie-755376.jpg!s`,
	},
	{
		word1: `cuffs`,
		translation1: `mankiety`,
		level: `extended`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/58/35/hand_watch_cuff_cufflink_businessman-1396609.jpg!s`,
	},
	{
		word1: `dressing gown`,
		translation1: `szlafrok`,
		level: `extended`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/02/7d/bed_woman_sleep_time_of_work_attractive_stand_up_rested-1374298.jpg!s`,
	},
	{
		word1: `hight heels`,
		translation1: `wysokie obcasy`,
		level: `extended`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/3e/79/fashion_shoes_high_heels_style_footwear_female_woman-759718.jpg!s`,
	},
	{
		word1: `hoodie`,
		translation1: `bluza z kapturem`,
		level: `extended`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/7f/34/person_hoodie_coat_snow_street-1390125.jpg!s`,
	},
	{
		word1: `long-sleeved (shirt)`,
		translation1: `z długim rękawem (koszula)`,
		level: `extended`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/54/e5/writing_pen_man_boy_male_ink_paper_pencils-655321.jpg!s`,
	},
	{
		word1: `short-sleeved`,
		translation1: `z krótkim rękawem (koszula)`,
		level: `extended`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/11/6b/waiting_appointment_schedule_time_hurry_urgent_timetable_watch-948348.jpg!s`,
	},
	{
		word1: `strapless top`,
		translation1: `bluzka bez ramiączek`,
		level: `extended`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/95/5c/portrait_woman_sunlight_girl_sunshine_sunglasses_female_table-104872.jpg!s`,
	},
	{
		word1: `V-neck`,
		translation1: `dekolt w szpic`,
		level: `extended`,
		type: `ubrania`,
		image: `https://c.pxhere.com/photos/e6/7f/woman_portrait_face_model_canon_studio_beauty_shot-748765.jpg!s`,
	},
	// // // // // -dodatki
	{
		word1: `belt`,
		translation1: `pasek`,
		level: `basic`,
		type: `dodatki`,
		image: `https://c.pxhere.com/photos/5f/ad/fashion_woman_lady_female_belt-1389951.jpg!s`,
	},
	{
		word1: `button`,
		translation1: `guzik`,
		level: `basic`,
		type: `dodatki`,
		image: `https://c.pxhere.com/photos/f2/c0/men's_shirt_shirt_attire_clothing_smart_apparel_cuff_sleeve-924749.jpg!s`,
	},
	{
		word1: `cap`,
		translation1: `czapka z daszkiem`,
		level: `basic`,
		type: `dodatki`,
		image: `https://c.pxhere.com/images/ce/88/12f59815de6322f12bf3fa9fe40e-1418659.jpg!s`,
	},
	{
		word1: `earrings`,
		translation1: `kolczyki`,
		level: `basic`,
		type: `dodatki`,
		image: `https://c.pxhere.com/photos/63/8b/portrait_woman_girl_beautiful_woman_blond_blond_woman_red_head_eyes-603665.jpg!s`,
	},
	{
		word1: `glasses`,
		translation1: `okulary`,
		level: `basic`,
		type: `dodatki`,
		image: `https://c.pxhere.com/images/de/51/ad47f3e541af916b466f7e97a3cc-1424065.jpg!s`,
	},
	{
		word1: `handbag`,
		word2: `bag`,
		translation1: `torebka`,
		level: `basic`,
		type: `dodatki`,
		image: `https://c.pxhere.com/photos/68/dd/purse_woman_pattern_leather_bag_fashion_handbag-835543.jpg!s`,
	},
	{
		word1: `jewellery`,
		translation1: `biżuteria`,
		level: `basic`,
		type: `dodatki`,
		image: `https://c.pxhere.com/photos/bd/a0/woman_girl_blonde_long_hair_shawl_white_dress_summer_jewellery-1050857.jpg!s`,
	},
	{
		word1: `necklace`,
		translation1: `naszyjnik`,
		level: `basic`,
		type: `dodatki`,
		image: `https://c.pxhere.com/photos/59/5b/accessories_style_girl_glamour_styling_accessory_hair_necklace-774637.jpg!s`,
	},
	{
		word1: `ring`,
		translation1: `pierścionek`,
		level: `basic`,
		type: `dodatki`,
		image: `https://c.pxhere.com/images/04/05/d4cc227e553189c57745bed22a46-1445491.jpg!s`,
	},
	{
		word1: `scarf`,
		translation1: `szalik`,
		level: `basic`,
		type: `dodatki`,
		image: `https://c.pxhere.com/images/0a/db/b96b1a250ca7c154063c65f001a9-1448349.jpg!s`,
	},
	{
		word1: `tie`,
		translation1: `krawat`,
		level: `basic`,
		type: `dodatki`,
		image: `https://c.pxhere.com/images/c5/92/ef66f34182d77fc8f258b07260f4-1445999.jpg!s`,
	},
	// // // -extended
	{
		word1: `bracelet`,
		translation1: `bransoletka`,
		level: `extended`,
		type: `dodatki`,
		image: `https://c.pxhere.com/photos/9f/30/art_bangles_blur_bracelet_fashion_fingers_girl_hands-1553733.jpg!s`,
	},
	{
		word1: `brooch`,
		translation1: `broszka`,
		level: `extended`,
		type: `dodatki`,
		image: `https://c.pxhere.com/photos/e9/2e/beard_bow_tie_brooch_fashion_formal_formal_coat_groom_guy-1175903.jpg!s`,
	},
	{
		word1: `shoe laces`,
		translation1: `sznurówki`,
		level: `extended`,
		type: `dodatki`,
		image: 'https://c.pxhere.com/photos/5a/db/leg_foot_body_female_standing_shoe_sneakers_fashion-538381.jpg!s',
	},
	{
		word1: `slippers`,
		translation1: `kapcie`,
		level: `extended`,
		type: `dodatki`,
		image: `https://c.pxhere.com/photos/29/c2/feet_toes_slippers_kids_children_pajamas_pjs_boy-988467.jpg!s`,
	},
	{
		word1: `zip-up`,
		translation1: `na zamek`,
		level: `extended`,
		type: `dodatki`,
		image: `https://c.pxhere.com/photos/27/32/shoe_leather_shoe_chic_zip_pusher_shoelace_brown_winter_boot-478703.jpg!s`,
	},
	// // // // // -wzory i materiały
	{
		word1: `checked`,
		translation1: `w kratę`,
		level: `basic`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/83/eb/girl_teen_tartan_student_hoodie_smoothie_city_day-1065451.jpg!s`,
	},
	{
		word1: `cotton`,
		translation1: `bawełna`,
		level: `basic`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/e6/fb/thread_spool_needle_sew_white_yarn_sewing_textile-1349196.jpg!s`,
	},
	{
		word1: `gold`,
		translation1: `złoto`,
		level: `basic`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/62/13/st_patrick's_day_irish_gold_st_patrick_st_patrick's_day_background_celebration_patrick_day-1368929.jpg!s`,
	},
	{
		word1: `leather`,
		translation1: `skóra`,
		translation2: `skórzany`,
		female: `yes`,
		t1: false,
		level: `basic`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/18/55/handbag_purse_bag_country_lane_landscape_nature_summer_vintage-1096263.jpg!s`,
	},
	{
		word1: `plain`,
		translation1: `gładki`,
		female: `yes`,
		level: `basic`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/a3/8a/mason_concrete_float_smooth_cement_worker_labor_builder-893282.jpg!s`,
	},
	{
		word1: `silk`,
		translation1: `jedwab`,
		level: `basic`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/d6/c5/fabric_silk_gold_bright_cloth_tissue_substances_color-771260.jpg!s`,
	},
	{
		word1: `silver`,
		translation1: `srebro`,
		translation2: `srebrny`,
		female: `yes`,
		t1: false,
		level: `basic`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/ad/8d/celebration_christmas_decoration_dining_dinner_dish_event_festive-1250733.jpg!s`,
	},
	{
		word1: `spotted`,
		translation1: `w kropki`,
		level: `basic`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/d6/2f/ladybug_beetle_insect_lucky_charm_red_points_beaded_dew-843762.jpg!s`,
	},
	{
		word1: `striped`,
		translation1: `w paski`,
		level: `basic`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/d4/9b/strip_bug_bug_macro_insect_red_insect_photo_close_striped-717078.jpg!s`,
	},
	{
		word1: `tartan`,
		translation1: `w kratę`,
		translation2: `w szkodzką kratę`,
		level: `basic`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/35/4d/kilts_scotland_scottish_menswear_raditional_clothing_skirt-1041647.jpg!s`,
	},
	{
		word1: `wool`,
		translation1: `wełna`,
		level: `basic`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/9c/9f/blanket_throw_sweater_warm_wool-1397261.jpg!s`,
	},
	// // // -extended
	{
		word1: `elactic`,
		translation1: `elastyczny`,
		female: `yes`,
		level: `extended`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/94/43/rubber_bands_colour_ball_elastic_green_accessory_blue_color-1323382.jpg!s`,
	},
	{
		word1: `fur`,
		translation1: `futro`,
		translation2: `futrzany`,
		female: `yes`,
		t1: false,
		level: `extended`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/6f/1e/snow_fox_fur_tail_mammal-63749.jpg!s`,
	},
	{
		word1: `lacy`,
		translation1: `koronkowy`,
		female: `yes`,
		level: `extended`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/a7/82/lace_shadows_legs_girl_model_young_woman_fashion-657834.jpg!s`,
	},
	{
		word1: `lined`,
		translation1: `na podszewce`,
		translation2: `ocieplany`,
		female: `yes`,
		t1: false,
		level: `extended`,
		type: `wzory i materiały`,
		image: `https://c.pxhere.com/photos/dc/f8/winter_jacket_scarf_wool_scarf_woman_girl_modern_young_woman_female-1186579.jpg!s`,
	}
]

export default words3_Clothes