const words5_FeelingsAndEmotions = [
	{
		word1: `angry`,
		translation1: `zły`,
		translation2: `rozgniewany`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `annoyed`,
		translation1: `zirytowany`,
		translation2: `rozdrażniony`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `be in a good mood`,
		translation1: `być w dobrym humorze`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `be in a bad mood`,
		translation1: `być w złym humorze`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `bored`,
		translation1: `znudzony`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `cross`,
		translation1: `zły`,
		translation2: `rozgniewany`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `depressed`,
		translation1: `załamany`,
		translation2: `przygnębiony`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `disappointed`,
		translation1: `zawstydzony`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `excited`,
		translation1: `podekscytowany`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `exhausted`,
		translation1: `wyczerpany`,
		translation2: `zmęczony`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `frightened`,
		translation1: `przerażony`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `nervous`,
		translation1: `zdenerwowany`,
		translation2: `spięty`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `pleased`,
		translation1: `zadowolony`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `relaxed`,
		translation1: `zrelaksowany`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `scared`,
		translation1: `wystraszony`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `shocked`,
		translation1: `zszokowany`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `stressed`,
		translation1: `zestresowany`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `surprised`,
		translation1: `zdziwiony`,
		translation2: `zaskoczony`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `tired`,
		translation1: `zmęczony`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `upset`,
		translation1: `przygnębiony`,
		translation2: `zaniepokojony`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `worried`,
		translation1: `zmartwiony`,
		female: `yes`,
		level: `basic`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	// // // -extended
	{
		word1: `amazed`,
		translation1: `zdumiony`,
		translation2: `zdziwiony`,
		female: `yes`,
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `delighted`,
		translation1: `zachwycony`,
		female: `yes`,
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `nagging feeling`,
		translation1: `dręczące uczucie`,
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `petrified`,
		translation1: `przerażony`,
		female: `yes`,
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `shattered`,
		translation1: `zdruzgotany`,
		translation2: `wykończony`,
		female: `yes`,
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `stunned`,
		translation1: `oniemiały`,
		translation2: `osłupiały`,
		female: `yes`,
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
	{
		word1: `worn out`,
		translation1: `wycieńczony`,
		translation2: `wyczerpany`,
		female: `yes`,
		level: `extended`,
		type: `uczucia i emocje`,
		image: `url`,
	},
];

export default words5_FeelingsAndEmotions