const words6_Interests = [
	{
		word1: `adore`,
		translation1: `uwielbiać`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word1: `be a fan of sb (somebody)`,
		translation1: `być fanem kogoś`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word1: `be a fan of sth (something)`,
		translation1: `być fanem czegoś`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word1: `be hopeless at`,
		translation1: `być beznadziejnym w`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word1: `be into sth (something)`,
		translation1: `zajmować się czyimś`, 
		translation2: `interesować się czymś`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word1: `be keen on sth (something)`,
		translation1: `interesować się czymś`, 
		translation2: `lubić coś robić`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word1: `be mad about sb (somebody)`,
		translation1: `szaleć na kimś`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word1: `be mad about sth (something)`,
		translation1: `szaleć za czymś`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word1: `can't stand`,
		translation1: `nie znosić`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word1: `play games`,
		translation1: `grać w gry`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word1: `play board games`,
		translation1: `grać w gry planszowe`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
	{
		word1: `work out`,
		translation1: `trenować`, 
		translation2: `ćwiczyć`, 
		level: `basic`,
		type: `zainteresowania`,
		image: `url`,
	},
];

export default words6_Interests