const words8_Orther = [
	{
		word1: `brief`,
		translation1: `krótki`, 
		translation2: `krótkotrwały`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `come across`,
		translation1: `wpaść na`, 
		translation2: `natknąć się na`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `complete`,
		translation1: `całkowity`, 
		translation2: `kompletny`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `develop into`,
		translation1: `rozwinąć się w`, 
		translation2: `stawać się (kimś)`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `eco-freak`,
		translation1: `fanatyk ekologii`, 
		translation2: `fanatyczka ekologii`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `fitness maniac`,
		translation1: `fanatyk ćwiczeń fizycznych`, 
		translation2: `fanatyczka ćwiczeń fizycznych`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `focus on`,
		translation1: `skupiać się na`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `grow up`,
		translation1: `rosnąć`, 
		translation2: `dorastać`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `have a lot in common`,
		translation1: `mieć dużo wspólnego`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `have a little in common`,
		translation1: `mieć niewiele wspólnego`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `health nut`,
		translation1: `osoba mająca obsesję na punkcie zdrowia`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `huge`,
		translation1: `ogromny`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `identify`,
		translation1: `zidentyfikować`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `look up to`,
		translation1: `podziwiać`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `realise`,
		translation1: `zdać sobie sprawę`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `recognise`,
		translation1: `rozpoznać`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `remember`,
		translation1: `pamiętać`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `remind someone to do something`,
		translation1: `przypomnieć komuś, by coś zrobił`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `spend money on`,
		translation1: `wydawać pieniądze na`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `spot`,
		translation1: `dostrzec`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `the complete opposite`,
		translation1: `całkowite przeciwieństwo`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `typical of`,
		translation1: `typowy dla`, 
		level: `basic`,
		type: `inne`,
		image: `url`,
	},
	// // //
	{
		word1: `be part of someone's nature`,
		translation1: `leżeć w czyjejś naturze`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `befriend`,
		translation1: `zaprzyjaźnić się z`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `bizarre`,
		translation1: `dziwny`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `can\`t believe your ears`,
		translation1: `nie móc uwierzyć własnym uszom`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `common experience`,
		translation1: `częste doznanie`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `find common ground`,
		translation1: `znaleźć wspólną płaszczyznę`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `have the time of your life`,
		translation1: `doskonale się bawić`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `place`,
		translation1: `rozpoznać`, 
		translation2: `zidentyfikować`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `pluck up the courage (to do something)`,
		translation1: `zdobyć się na odwagę (aby coś zrobić)`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `raise questions`,
		translation1: `nasuwać pytania`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `scan`,
		translation1: `przeskanować (np. mózg)`, 
		translation2: `przebiec wzrokiem (np. tekst)`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `sophisticated`,
		translation1: `skomplikowany`, 
		translation2: `zaawansowany`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
	{
		word1: `strike up (a conversation)`,
		translation1: `nawiązać (rozmowę)`, 
		level: `extended`,
		type: `inne`,
		image: `url`,
	},
];

export default words8_Orther