const words2_ProhibitionSigns = [
	{
		word1: `B-1`,
		translation1: `zakaz ruchu w obu kierunkach`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Znak_B-1.svg/800px-Znak_B-1.svg.png`,
	},
	{
		word1: `B-2`,
		translation1: `zakaz wjazdu`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Znak_B-2.svg/800px-Znak_B-2.svg.png`,
	},
	{
		word1: `B-3`,
		translation1: `zakaz wjazdu pojazdów silnikowych z wyjątkiem motocykli jednośladowych`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Znak_B-3.svg/800px-Znak_B-3.svg.png`,
	},
	{
		word1: `B-3a`,
		translation1: `zakaz wjazdu autobusów`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Znak_B-3a.svg/800px-Znak_B-3a.svg.png`,
	},
	{
		word1: `B-4`,
		translation1: `zakaz wjazdu motocykli`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Znak_B-4.svg/800px-Znak_B-4.svg.png`,
	},
	{
		word1: `B-5`,
		translation1: `zakaz wjazdu samochodów ciężarowych`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Znak_B-5.svg/800px-Znak_B-5.svg.png`,
		image2: `https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Znak_B-5_6ton.svg/800px-Znak_B-5_6ton.svg.png`,
	},
	{
		word1: `B-6`,
		translation1: `zakaz wjazdu ciągników rolniczych i pojazdów wolnobieżnych`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Znak_B-6.svg/800px-Znak_B-6.svg.png`,
	},
	{
		word1: `B-7`,
		translation1: `zakaz wjazdu pojazdów silnikowych z przyczepą`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Znak_B-7.svg/800px-Znak_B-7.svg.png`,
		image2: `https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Znak_B-7_5ton.svg/800px-Znak_B-7_5ton.svg.png`,
	},
	{
		word1: `B-8`,
		translation1: `zakaz wjazdu pojazdów zaprzęgowych`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Znak_B-8.svg/800px-Znak_B-8.svg.png`,
	},
	{
		word1: `B-9`,
		translation1: `zakaz wjazdu rowerów`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Znak_B-9.svg/800px-Znak_B-9.svg.png`,
	},
	{
		word1: `B-10`,
		translation1: `zakaz wjazdu motorowerów`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Znak_B-10.svg/800px-Znak_B-10.svg.png`,
	},
	{
		word1: `B-11`,
		translation1: `zakaz wjazdu wózków rowerowych`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Znak_B-11.svg/800px-Znak_B-11.svg.png`,
	},
	{
		word1: `B-12`,
		translation1: `zakaz wjazdu wózków ręcznych`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Znak_B-12.svg/800px-Znak_B-12.svg.png`,
	},
	{
		word1: `B-13`,
		translation1: `zakaz wjazdu pojazdów z towarami wybuchowymi lub łatwo zapalnymi`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Znak_B-13.svg/800px-Znak_B-13.svg.png`,
	},
	{
		word1: `B-13a`,
		translation1: `zakaz wjazdu pojazdów z towarami niebezpiecznymi`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Znak_B-13a.svg/800px-Znak_B-13a.svg.png`,
	},
	{
		word1: `B-14`,
		translation1: `zakaz wjazdu pojazdów z towarami, które mogą skazić wodę`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Znak_B-14.svg/800px-Znak_B-14.svg.png`,
	},
	{
		word1: `B-15`,
		translation1: `zakaz wjazdu pojazdów o szerokości ponad ...m`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Znak_B-15.svg/800px-Znak_B-15.svg.png`,
	},
	{
		word1: `B-16`,
		translation1: `zakaz wjazdu pojazdów o wysokości ponad ...m`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Znak_B-16.svg/800px-Znak_B-16.svg.png`,
	},
	{
		word1: `B-17`,
		translation1: `zakaz wjazdu pojazdów o długości ponad ...m`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Znak_B-17.svg/800px-Znak_B-17.svg.png`,
	},
	{
		word1: `B-18`,
		translation1: `zakaz wjazdu pojazdów o rzeczywistej masie całkowitej ponad ...t`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Znak_B-18.svg/800px-Znak_B-18.svg.png`,
	},
	{
		word1: `B-19`,
		translation1: `zakaz wjazdu pojazdów o nacisku osi większym niż ...t`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Znak_B-19.svg/800px-Znak_B-19.svg.png`,
	},
	{
		word1: `B-20`,
		translation1: `stop`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Poland_road_sign_B-20.svg/800px-Poland_road_sign_B-20.svg.png`,
	},
	{
		word1: `B-21`,
		translation1: `zakaz skręcania w lewo`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Znak_B-21.svg/800px-Znak_B-21.svg.png`,
	},
	{
		word1: `B-22`,
		translation1: `zakaz skręcania w prawo`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Znak_B-22.svg/800px-Znak_B-22.svg.png`,
	},
	{
		word1: `B-23`,
		translation1: `zakaz zawracania`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Znak_B-23.svg/800px-Znak_B-23.svg.png`,
	},
	{
		word1: `B-24`,
		translation1: `koniec zakazu zawracania`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Znak_B-24.svg/800px-Znak_B-24.svg.png`,
	},
	{
		word1: `B-25`,
		translation1: `zakaz wyprzedzania`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Znak_B-25.svg/800px-Znak_B-25.svg.png`,
	},
	{
		word1: `B-26`,
		translation1: `zakaz wyprzedzania przez samochody ciężarowe`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Znak_B-26.svg/800px-Znak_B-26.svg.png`,
	},
	{
		word1: `B-27`,
		translation1: `koniec zakazu wyprzedzania`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Znak_B-27.svg/800px-Znak_B-27.svg.png`,
	},
	{
		word1: `B-28`,
		translation1: `koniec zakazu wyprzedzania przez samochody ciężarowe`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Znak_B-28.svg/800px-Znak_B-28.svg.png`,
	},
	{
		word1: `B-29`,
		translation1: `zakaz używania sygnałów dźwiękowych`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Znak_B-29.svg/800px-Znak_B-29.svg.png`,
	},
	{
		word1: `B-30`,
		translation1: `koniec zakazu używania sygnałów dźwiękowych`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Znak_B-30.svg/800px-Znak_B-30.svg.png`,
	},
	{
		word1: `B-31`,
		translation1: `pierwszeństwo dla nadjeżdżających z przeciwka`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Znak_B-31.svg/800px-Znak_B-31.svg.png`,
	},
	{
		word1: `B-32`,
		translation1: `stój — kontrola celna`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Znak_B-32.svg/800px-Znak_B-32.svg.png`,
	},
	{
		word1: `B-32a`,
		translation1: `kontrola graniczna`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Znak_B-32a.svg/800px-Znak_B-32a.svg.png`,
	},
	{
		word1: `B-32b`,
		translation1: `rogatka uszkodzona`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Znak_B-32b.svg/800px-Znak_B-32b.svg.png`,
	},
	{
		word1: `B-32c`,
		translation1: `sygnalizacja uszkodzona`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Znak_B-32c.svg/800px-Znak_B-32c.svg.png`,
	},
	{
		word1: `B-32d`,
		translation1: `wjazd na prom`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Znak_B-32d.svg/800px-Znak_B-32d.svg.png`,
	},
	{
		word1: `B-32e`,
		translation1: `kontrola drogowa`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Znak_B-32e.svg/800px-Znak_B-32e.svg.png`,
	},
	{
		word1: `B-32f`,
		translation1: `pobór opłat`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Znak_B-32f.svg/800px-Znak_B-32f.svg.png`,
	},
	{
		word1: `B-33`,
		translation1: `ograniczenie prędkości`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Znak_B-33.svg/800px-Znak_B-33.svg.png`,
	},
	{
		word1: `B-34`,
		translation1: `koniec ograniczenia prędkości`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Znak_B-34.svg/800px-Znak_B-34.svg.png`,
	},
	{
		word1: `B-35`,
		translation1: `zakaz postoju`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Znak_B-35.svg/800px-Znak_B-35.svg.png`,
	},
	{
		word1: `B-36`,
		translation1: `zakaz zatrzymywania się`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Znak_B-36.svg/800px-Znak_B-36.svg.png`,
	},
	{
		word1: `B-37`,
		translation1: `zakaz postoju w dni nieparzyste`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Znak_B-37.svg/800px-Znak_B-37.svg.png`,
	},
	{
		word1: `B-38`,
		translation1: `zakaz postoju w dni parzyste`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Znak_B-38.svg/800px-Znak_B-38.svg.png`,
	},
	{
		word1: `B-39`,
		translation1: `strefa ograniczonego postoju`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Znak_B-39.svg/800px-Znak_B-39.svg.png`,
	},
	{
		word1: `B-40`,
		translation1: `koniec strefy ograniczonego postoju`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Znak_B-40.svg/800px-Znak_B-40.svg.png`,
	},
	{
		word1: `B-41`,
		translation1: `zakaz ruchu pieszych`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Znak_B-41.svg/800px-Znak_B-41.svg.png`,
	},
	{
		word1: `B-42`,
		translation1: `koniec zakazów`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Znak_B-42.svg/800px-Znak_B-42.svg.png`,
	},
	{
		word1: `B-43`,
		translation1: `strefa ograniczonej prędkości`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Znak_B-43.svg/800px-Znak_B-43.svg.png`,
	},
	{
		word1: `B-44`,
		translation1: `koniec strefy ograniczonej prędkości`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Znak_B-44.svg/800px-Znak_B-44.svg.png`,
	},
	{
		word1: `B-3/4`,
		translation1: `zakaz wjazdu pojazdów silnikowych`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Znak_B-3-4.svg/800px-Znak_B-3-4.svg.png`,
	},
	{
		word1: `B-6/8`,
		translation1: `zakaz wjazdu ciągników rolniczych i pojazdów zaprzęgowych`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Znak_B-6-8.svg/800px-Znak_B-6-8.svg.png`,
	},
	{
		word1: `B-9/12`,
		translation1: `zakaz wjazdu rowerów i wózków ręcznych`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Znak_B-9-12.svg/800px-Znak_B-9-12.svg.png`,
	},
	{
		word1: `B-13/14`,
		translation1: `zakaz wjazdu pojazdów z towarami wybuchowymi lub łatwo zapalnymi oraz towarami mogącymi skazić wodę`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Znak_B-13-14.svg/800px-Znak_B-13-14.svg.png`,
	},
	{
		word1: `B-3/4/10`,
		translation1: `zakaz wjazdu pojazdów silnikowych`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Znak_B-3-4-10.svg/800px-Znak_B-3-4-10.svg.png`,
	},
	{
		word1: `B-6/8/9`,
		translation1: `zakaz wjazdu pojazdów innych niż samochodowe`,
		type: `znaki zakazu`,
		image: `https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Znak_B-6-8-9.svg/800px-Znak_B-6-8-9.svg.png`,
	}
]

export default words2_ProhibitionSigns