const words2_ProhibitionSigns = [
	{
		word1: `D-1`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-2`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-3`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-4a`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-4b`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-5`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-6`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-6a`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-6b`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-7`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-8`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-9`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-10`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-11`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-12`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-13`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-14`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-15`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-16`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-17`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-18`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-18a`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-18b`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-19`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-20`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-21`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-21a`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-22`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-23`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-23a`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-24`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-25`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-26`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-26a`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-26b`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-26c`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-26d`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-27`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-28`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-29`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	},
	{
		word1: `D-30`,
		translation: `znaDzenie`,
		type: `znaki nakazu`,
		image: `url`,
	}
]

export default words2_ProhibitionSigns