const words1_FromBook = [
	{
		firstForm: `be`,
		secondForm: `was`,
		secondForm2: `were`,
		thirdForm: `been`,
		translation1: `być`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `become`,
		secondForm: `became`,
		thirdForm: `become`,
		translation1: `stawać się`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `begin`,
		secondForm: `began`,
		thirdForm: `begun`,
		translation1: `zaczynać (się)`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `bend`,
		secondForm: `bent`,
		thirdForm: `bent`,
		translation1: `zginać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `bite`,
		secondForm: `bit`,
		thirdForm: `bitten`,
		translation1: `gryźć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `blow`,
		secondForm: `blew`,
		thirdForm: `blown`,
		translation1: `dmuchać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `break`,
		secondForm: `broke`,
		thirdForm: `broken`,
		translation1: `łamać`,
		translation2: `rozbić`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `bring`,
		secondForm: `brought`,
		thirdForm: `brought`,
		translation1: `przynosić`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `build`,
		secondForm: `built`,
		thirdForm: `built`,
		translation1: `budować`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `burn`,
		secondForm: `burned`,
		secondForm2: `burnt`,
		thirdForm: `burned`,
		thirdForm2: `burnt`,
		translation1: `palić (się)`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `buy`,
		secondForm: `bought`,
		thirdForm: `bought`,
		translation1: `kupować`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `can`,
		secondForm: `could`,
		thirdForm: `been able to`,
		translation1: `móc`,
		translation2: `potrafić`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `catch`,
		secondForm: `caught`,
		thirdForm: `caught`,
		translation1: `łapać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `choose`,
		secondForm: `chose`,
		thirdForm: `chosen`,
		translation1: `wybierać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `come`,
		secondForm: `came`,
		thirdForm: `come`,
		translation1: `przychodzić`,
		translation2: `przybywać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `cost`,
		secondForm: `cost`,
		thirdForm: `cost`,
		translation1: `kosztować`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `cut`,
		secondForm: `cut`,
		thirdForm: `cut`,
		translation1: `ciąć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `do`,
		secondForm: `did`,
		thirdForm: `done`,
		translation1: `robić`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `draw`,
		secondForm: `drew`,
		thirdForm: `drawn`,
		translation1: `rysować`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `drink`,
		secondForm: `drank`,
		thirdForm: `drunk`,
		translation1: `pić`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `drive`,
		secondForm: `drove`,
		thirdForm: `driven`,
		translation1: `jechać`,
		translation2: `prowadzić samochód`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `eat`,
		secondForm: `ate`,
		thirdForm: `eaten`,
		translation1: `jeść`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `fall`,
		secondForm: `fell`,
		thirdForm: `fallen`,
		translation1: `upadać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `feel`,
		secondForm: `felt`,
		thirdForm: `felt`,
		translation1: `czuć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `fight`,
		secondForm: `fought`,
		thirdForm: `fought`,
		translation1: `walczyć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `find`,
		secondForm: `found`,
		thirdForm: `found`,
		translation1: `znaleźć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `fly`,
		secondForm: `flew`,
		thirdForm: `flown`,
		translation1: `latać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `forget`,
		secondForm: `forgot`,
		thirdForm: `forgotten`,
		translation1: `zapomnieć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `get`,
		secondForm: `got`,
		thirdForm: `got`,
		translation1: `dostawać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `go`,
		secondForm: `went`,
		thirdForm: `gone`,
		translation1: `iść`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `grow`,
		secondForm: `grew`,
		thirdForm: `grown`,
		translation1: `rosnąć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `hang`,
		secondForm: `hung`,
		thirdForm: `hung`,
		translation1: `wieszać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `have`,
		secondForm: `had`,
		thirdForm: `had`,
		translation1: `mieć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `hear`,
		secondForm: `heard`,
		thirdForm: `heard`,
		translation1: `słyszeć`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `hide`,
		secondForm: `hid`,
		thirdForm: `hidden`,
		translation1: `ukrywać (się)`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `hit`,
		secondForm: `hit`,
		thirdForm: `hit`,
		translation1: `uderzać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `keep`,
		secondForm: `kept`,
		thirdForm: `kept`,
		translation1: `trzymać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `know`,
		secondForm: `knew`,
		thirdForm: `known`,
		translation1: `wiedzieć`,
		translation2: `znać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `lay`,
		secondForm: `laid`,
		thirdForm: `laid`,
		translation1: `kłaść`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `lead`,
		secondForm: `led`,
		thirdForm: `led`,
		translation1: `prowadzić`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `learn`,
		secondForm: `learned`,
		secondForm2: `learnt`,
		thirdForm: `learned`,
		thirdForm2: `learnt`,
		translation1: `uczyć się`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
		firstForm: `leave`,
		secondForm: `left;`,
		thirdForm: `left;`,
		translation1: `opuszczać`,
		translation2: `wyjeżdżać`,
		level: `podstawa (z podręcznika)`,
		type: `basic`,
		image: `url`,
	},
	{
        firstForm: `lend`,
        secondForm: `lent`,
        thirdForm: `lent`,
        translation1: `pożyczyć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `lose`,
        secondForm: `lost`,
        thirdForm: `lost`,
        translation1: `gubić`,
        translation2: `zgubić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `make`,
        secondForm: `made`,
        thirdForm: `made`,
        translation1: `robić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `mean`,
        secondForm: `meant`,
        thirdForm: `meant`,
        translation1: `znaczyć`,
        translation2: `mieć na myśli`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `meet`,
        secondForm: `met`,
        thirdForm: `met`,
        translation1: `spotykać`,
        translation2: `poznawać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `overcome`,
        secondForm: `overcame`,
        thirdForm: `overcome`,
        translation1: `przezwyciężać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `pay`,
        secondForm: `paid`,
        thirdForm: `paid`,
        translation1: `płacić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `put`,
        secondForm: `put`,
        thirdForm: `put`,
        translation1: `kłaść`,
        translation2: `położyć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `read`,
        secondForm: `read`,
        thirdForm: `read`,
        translation1: `czytać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `ride`,
        secondForm: `rode`,
        thirdForm: `ridden`,
        translation1: `jeździć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `ring`,
        secondForm: `rang`,
        thirdForm: `rung`,
        translation1: `dzwonić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `run`,
        secondForm: `ran`,
        thirdForm: `run`,
        translation1: `biec`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `say`,
        secondForm: `said`,
        thirdForm: `said`,
        translation1: `mówić`,
        translation2: `powiedzieć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `see`,
        secondForm: `saw`,
        thirdForm: `seen`,
        translation1: `widzieć`,
        translation2: `zobaczyć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `sell`,
        secondForm: `sold`,
        thirdForm: `sold`,
        translation1: `sprzedać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `send`,
        secondForm: `sent`,
        thirdForm: `sent`,
        translation1: `wysyłać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `set`,
        secondForm: `set`,
        thirdForm: `set`,
        translation1: `umieszczać`,
        translation2: `zachodzić (coś)`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `shake`,
        secondForm: `shook`,
        thirdForm: `shook`,
        translation1: `potrząsnąć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `shine`,
        secondForm: `shone`,
        thirdForm: `shone`,
        translation1: `świecić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `shoot`,
        secondForm: `shot`,
        thirdForm: `shot`,
        translation1: `strzelać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `show`,
        secondForm: `showed`,
        thirdForm: `shown`,
        translation1: `pokazać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `shut`,
        secondForm: `shut`,
        thirdForm: `shut`,
        translation1: `zamykać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `sing`,
        secondForm: `sang`,
        thirdForm: `sung`,
        translation1: `śpiewać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `sink`,
        secondForm: `sank`,
        thirdForm: `sunk`,
        translation1: `tonąć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `sit`,
        secondForm: `sat`,
        thirdForm: `sat`,
        translation1: `siedzieć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `sleep`,
        secondForm: `slept`,
        thirdForm: `slept`,
        translation1: `spać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `smell`,
        secondForm: `smelled`,
        secondForm2: `smelt`,
        thirdForm: `smelled`,
        thirdForm2: `smelt`,
        translation1: `wąchać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `speak`,
        secondForm: `spoke`,
        thirdForm: `spoken`,
        translation1: `mówić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `spell`,
        secondForm: `spelled`,
        secondForm2: `spelt`,
        thirdForm: `spelled`,
        thirdForm2: `spelt`,
        translation1: `literować`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `spend`,
        secondForm: `spent`,
        thirdForm: `spent`,
        translation1: `spędzać`,
        translation2: `wydawać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `spill`,
        secondForm: `spilled`,
        secondForm2: `spilt`,
        thirdForm: `spilled`,
        thirdForm2: `spilt`,
        translation1: `rozlewać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `stand`,
        secondForm: `stood`,
        thirdForm: `stood`,
        translation1: `stać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `steal`,
        secondForm: `stole`,
        thirdForm: `stolen`,
        translation1: `kraść`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `swim`,
        secondForm: `swam`,
        thirdForm: `swum`,
        translation1: `pływać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `take`,
        secondForm: `took`,
        thirdForm: `taken`,
        translation1: `brać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `teach`,
        secondForm: `taught`,
        thirdForm: `taught`,
        translation1: `uczyć (kogoś)`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `tell`,
        secondForm: `told`,
        thirdForm: `told`,
        translation1: `powiedzieć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `think`,
        secondForm: `thought`,
        thirdForm: `thought`,
        translation1: `sądzić`,
        translation2: `myśleć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `throw`,
        secondForm: `threw`,
        thirdForm: `thrown`,
        translation1: `rzucać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `understand`,
        secondForm: `understood`,
        thirdForm: `understood`,
        translation1: `rozumieć`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `wake`,
        secondForm: `woke`,
        thirdForm: `woken`,
        translation1: `budzić`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `wear`,
        secondForm: `wore`,
        thirdForm: `worn`,
        translation1: `nosić (na sobie)`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `win`,
        secondForm: `won`,
        thirdForm: `won`,
        translation1: `wygrywać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
    {
        firstForm: `write`,
        secondForm: `wrote`,
        thirdForm: `written`,
        translation1: `pisać`,
        level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    },
	{
        firstForm: `test`,
        secondForm: `test2`,
        thirdForm: `test3`,
        translation1: `tłumaczenie`,
	    level: `podstawa (z podręcznika)`,
        type: `basic`,
        image: `url`,
    }
]

export default words1_FromBook
