const words1_WarningSigns = [
    {
        word: `A-1`,
        translation: `niebezpieczny zakręt w prawo`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-2`,
        translation: `niebezpieczny zakręt w lewo`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-3`,
        translation: `niebezpieczne zakręty — pierwszy w prawo`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-4`,
        translation: `niebezpieczne zakręty — pierwszy w lewo`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-5`,
        translation: `skrzyżowanie dróg`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-6a`,
        translation: `skrzyżowanie z drogą podporządkowaną występującą po obu stronach`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-6b`,
        translation: `skrzyżowanie z drogą podporządkowaną występującą po prawej stronie`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-6c`,
        translation: `skrzyżowanie z drogą podporządkowaną występującą po lewej stronie`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-6d`,
        translation: `wlot drogi jednokierunkowej z prawej strony`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-6e`,
        translation: `wlot drogi jednokierunkowej z lewej strony`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-7`,
        translation: `ustąp pierwszeństwa`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-8`,
        translation: `skrzyżowanie o ruchu okrężnym`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-9`,
        translation: `przejazd kolejowy z zaporami`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-10`,
        translation: `przejazd kolejowy bez zapór`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-11`,
        translation: `nierówna droga`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-11a`,
        translation: `próg zwalniający`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-12a`,
        translation: `zwężenie jezdni — dwustronne`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-12b`,
        translation: `zwężenie jezdni — prawostronne`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-12c`,
        translation: `zwężenie jezdni — lewostronne`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-13`,
        translation: `ruchomy most`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-14`,
        translation: `roboty na drodze`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-15`,
        translation: `śliska jezdnia`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-16`,
        translation: `przejście dla pieszych`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-17`,
        translation: `dzieci`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-18a`,
        translation: `zwierzęta gospodarskie`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-18b`,
        translation: `zwierzęta dzikie`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-19`,
        translation: `boczny wiatr`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-20`,
        translation: `odcinek jezdni o ruchu dwukierunkowym`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-21`,
        translation: `tramwaj`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-22`,
        translation: `niebezpieczny zjazd`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-23`,
        translation: `stromy podjazd`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-24`,
        translation: `rowerzyści`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-25`,
        translation: `spadające odłamki skalne`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-26`,
        translation: `lotnisko`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-27`,
        translation: `nabrzeże lub brzeg rzeki`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-28`,
        translation: `sypki żwir`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-29`,
        translation: `sygnały świetlne`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-30`,
        translation: `inne niebezpieczeństwo`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-31`,
        translation: `niebezpieczne pobocze`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-32`,
        translation: `oszronienie jezdni`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-33`,
        translation: `zator drogowy`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    },
    {
        word: `A-34`,
        translation: `wypadek drogowy`,
        type: `znaki ostrzegawcze`,
        image: `url`,
    }
]

export default words1_WarningSigns