const words7_EthnicalProblems = [
	{
		word1: `abortion`,
		translation1: `aborcja`, 
		level: `basic`,
		type: `problemy etyczne`,
		image: `url`,
	},
	{
		word1: `charity`,
		translation1: `dobroczynność`, 
		translation2: `ogranizacja charytatywna`, 
		level: `basic`,
		type: `problemy etyczne`,
		image: `url`,
	},
	{
		word1: `drug abuse`,
		translation1: `zażywanie narkotyków`, 
		level: `basic`,
		type: `problemy etyczne`,
		image: `url`,
	},
	{
		word1: `fair trade`,
		translation1: `sprawiedliwy handel`, 
		level: `basic`,
		type: `problemy etyczne`,
		image: `url`,
	},
	{
		word1: `homelessness`,
		translation1: `bezdomność`, 
		level: `basic`,
		type: `problemy etyczne`,
		image: `url`,
	},
	{
		word1: `unemployment`,
		translation1: `bezrobocie`, 
		level: `basic`,
		type: `problemy etyczne`,
		image: `url`,
	},
	{
		word1: `corruption`,
		translation1: `korupcja`, 
		level: `basic`,
		type: `problemy etyczne`,
		image: `url`,
	},
	{
		word1: `racism`,
		translation1: `rasizm`, 
		level: `basic`,
		type: `problemy etyczne`,
		image: `url`,
	},
	// // // -extended
	{
		word1: `dealth penatly`,
		translation1: `kara śmierci`, 
		level: `extended`,
		type: `problemy etyczne`,
		image: `url`,
	},
	{
		word1: `eutanasia`,
		translation1: `eutanazja`, 
		level: `extended`,
		type: `problemy etyczne`,
		image: `url`,
	},
	{
		word1: `freedom of speech`,
		translation1: `wolność słowa`, 
		level: `extended`,
		type: `problemy etyczne`,
		image: `url`,
	},
	{
		word1: `gambling`,
		translation1: `hazard`, 
		level: `extended`,
		type: `problemy etyczne`,
		image: `url`,
	},
	{
		word1: `genetic engineering`,
		translation1: `inżynieria genetyczna`, 
		level: `extended`,
		type: `problemy etyczne`,
		image: `url`,
	},
	{
		word1: `privacy`,
		translation1: `prywatność`, 
		level: `extended`,
		type: `problemy etyczne`,
		image: `url`,
	},
];

export default words7_EthnicalProblems