const words5_Orther = [
	{
		word1: `ability`,
		translation1: `zdolność`,
		translation2: `umiejętność`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `at some point`,
		translation1: `w którymś momencie`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `consult`,
		translation1: `konsultować (się)`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `drop out of`,
		translation1: `rzucić`,
		translation2: `przerwać`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `fashionable`,
		translation1: `modny`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `grumpy`,
		translation1: `zrzędliwy`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `inheritance`,
		translation1: `spadek`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `launch`,
		translation1: `wprowadzić produkt na rynek`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `money-making`,
		translation1: `dochodowy (o zawodzie)`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `routine`,
		translation1: `rutyna`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `summarise`,
		translation1: `podsumować`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `trendy`,
		translation1: `trendy`,
		translation2: `modny`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `well-being`,
		translation1: `dobre samopoczucie`,
		translation2: `dobrostan`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `wonder`,
		translation1: `zastanawiać się`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	// // //
	{
		word1: `body language`,
		translation1: `język ciała`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `computer-generated`,
		translation1: `zaprojektowany za pomocą komputera`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `contagious`,
		translation1: `zaraźliwy`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `content`,
		translation1: `zadowolony`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `devote oneself to`,
		translation1: `poświęcić się (czemuś)`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `do something workwise`,
		translation1: `robić coś w kwestiach zawodowych`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `emerge`,
		translation1: `pojawić się`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `focus on`,
		translation1: `skupić się na`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `go together`,
		translation1: `pasować do siebie`,
		translation2: `iść ze sobą w parze`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `have no clue`,
		translation1: `nie mieć pojęcia`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `last long`,
		translation1: `przetrwać`,
		translation2: `utrzymać się`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `make the headlines`,
		translation1: `trafić na czołówki gazet`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `money-minded`,
		translation1: `dbający tylko o pieniądze`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `on top of`,
		translation1: `poza`,
		translation2: `oprócz`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `positive thinking`,
		translation1: `pozytywne myślenie`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `put something into practice`,
		translation1: `zastosować coś w praktyce`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	},
	{
		word1: `technology-oriented`,
		translation1: `zainteresowany techniką`,
		level: `basic`,
		type: `extended`,
		image: `url`,
	}
]

export default words5_Orther