const words1_TypesOfHouses = [
	{
		word1: `block of flats`,
		translation1: `blok mieszkalny`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/4e/64/live_apartments_building_home_residential_development_facade_city_blocks_of_flats-1069156.jpg!d`,
	},
	{
		word1: `building`,
		translation1: `budynek`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/images/2c/43/4cf903987b65a94cf951d5dd6305-1582335.jpg!d`,
	},
	{
		word1: `bungalow`,
		translation1: `dom parterowy`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/7e/38/bungalow_house_door_windows_roof_lawn-1153492.jpg!d`,
	},
	{
		word1: `castle`,
		translation1: `zamek`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/e7/43/castle_hohenzollern_sunrise_fortress_morgenstimmung_hohenzollern_castle_germany_baden_w_rttemberg-852079.jpg!d`,
	},
	{
		word1: `cottage`,
		translation1: `domek wiejski`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/b2/22/winter_cabin_house_mountain_snow_cold_season_nature-681326.jpg!d`,

	},
	{
		word1: `detasched house`,
		translation1: `wolno stojący dom jednorodzinny`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/images/37/79/871eb4be9d5d30a94c9885f2584a-1423199.jpg!d`,

	},
	{
		word1: `family home`,
		translation1: `dom rodzinny`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/b1/e9/family_home_residence_contemporary_property_modern_suburban_real_estate_home-1091237.jpg!d`,
	},
	{
		word1: `farmhouse`,
		translation1: `dom w gospodarstwie`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/images/d4/10/f6abfd94fa51f357e077f6552936-1435055.jpg!d`,
	},
	{
		word1: `flat`,
		translation1: `mieszkanie`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/77/3e/urban_appartments_building_city_architecture_estate_exterior_block-837866.jpg!d`,
	},
	{
		word1: `house`,
		translation1: `dom`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/images/76/69/1c987528d63da871c49267a1f826-1426965.jpg!d`,
	},
	{
		word1: `mansion`,
		translation1: `pałac`,
		translation2: `rezydencja`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/20/5c/chateau_palace_architecture_mansion_old-135.jpg!d`,
	},
	{
		word1: `nursing home`,
		translation1: `dom spokojnej starości`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/92/4e/grandmother_mother_old_face_people_portrait_female_woman-423688.jpg!d`,
	},
	{
		word1: `semi-detasched house`,
		translation1: `bliźniak`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://images.pexels.com/photos/259957/pexels-photo-259957.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500`
	},
	{
		word1: `studio flat`,
		translation1: `kawalerka`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/ff/da/studying_exams_preparation_knowledge_teenage_male_room_study-858304.jpg!d`,
	},
	{
		word1: `terraced house`,
		translation1: `dom szeregowy`,
		translation2: `segment`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/c0/20/semi_detached_house_villa_rendering_visualization_architecture_visualization_3d_architectural_visualization_landscape-1059741.jpg!d`,
	},
	{
		word1: `tower block`,
		translation1: `wieżowiec`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/images/58/67/64a5540b50e2f715bc5d99d76deb-1418850.jpg!d`,
	},
	{
		word1: `villa`,
		translation1: `willa`,
		level: `basic`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/images/36/f8/6dcde69b9762f858de9b0b81f28e-1426975.jpg!d`,
	},
	// // // -extended
	{
		word1: `affortable housing`,
		translation1: `domy w przystępnej cenie`,
		translation2: `mieszkania w przystępnej cenie`,
		level: `extended`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/images/63/2f/cec8bb5e697a97307ff7f89597ee-1432881.jpg!d`,
	},
	{
		word1: `all mod cons`,
		translation1: `wszystkie wygody`,
		level: `extended`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/d2/ff/home_office_notebook_home_couch_sofa_canap_computer_laptop-1087294.jpg!d`,
	},
	{
		word1: `auction`,
		translation1: `aukcja`,
		translation2: `licytacja`,
		level: `extended`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/7e/75/hammer_money_euro_currency_dollar_bill_bills_paper_money_finance-758111.jpg!d`,
	},
	{
		word1: `bedsit`,
		translation1: `kawalerka do wynajęcia`,
		level: `extended`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/89/aa/staircase_block_of_flats_building_apartment_architecture_urban_housing_stairs-854788.jpg!d`,
	},
	{
		word1: `bid`,
		translation1: `oferta w licytacji`,
		level: `extended`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/41/bc/flea_market_junk_antiques_sale_used_commercially_antique_second_hand_used-932372.jpg!d`,
	},
	{
		word1: `dilapidated`,
		translation1: `zniszczony`,
		translation2: `walacy się`,
		level: `extended`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/94/11/lost_places_old_decay_ruin_railway_depot_train_train_hall_goods_station-499998.jpg!d`,
	},
	{
		word1: `housing estate`,
		translation1: `osiedle mieszkaniowe`,
		level: `extended`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/6b/e5/condominium_condo_architecture_apartment_residential_property_home_real_estate-893012.jpg!d`,
	},
	{
		word1: `in need of renovation`,
		translation1: `do remontu`,
		level: `extended`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/92/d0/dilapidated_room_house_disrepair_decay_aged_broken_rundown-681263.jpg!d`,
	},
	{
		word1: `mobile home`,
		translation1: `przyczepa mieszkalna`,
		level: `extended`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/be/19/mobile_home_camping_holiday_vehicle_abendstimmung_sea_travel_evening-945046.jpg!d`,
	},
	{
		word1: `retirement flat`,
		translation1: `mieszkanie dla emeryta`,
		level: `extended`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/54/19/woman_old_senior_female_elderly_retired_grandmother_smiling-671672.jpg!d`,
	},
	{
		word1: `sheltered accomodation`,
		translation1: `mieszkanie dla osób wymagających opieki (np. osób starszych)`,
		level: `extended`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/7e/86/hospital_assistance_care_for_caretaker_talk_citizen_clinic_disability-1179849.jpg!d`,
	},
	{
		word1: `under construction`,
		translation1: `w budowie`,
		level: `extended`,
		type: `rodzaje domów`,
		image: `https://c.pxhere.com/photos/20/de/construction_crane_building_construction_architecture_building_heavy_equipment_metal_sky-1342889.jpg!d`,
	},
	// // // // // -location
	{
		word1: `away from`,
		translation1: `z dala od`,
		level: `extended`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/9c/94/foggy_olive_tree_sun_sun_stripes_nature_landscape_tree_countryside-1057043.jpg!d`,
	},
	{
		word1: `city`,
		translation1: `miasto`,
		level: `extended`,
		type: `położenie`,
		image: `https://c.pxhere.com/images/72/23/d0dc3acd5f109e8e612f736cf5ca-1437609.jpg!d`,
	},
	{
		word1: `commute`,
		translation1: `dojeżdżać (do pracy lub szkoły)`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/31/bc/abstract_blur_britain_british_business_cargo_carriage_commute-819289.jpg!d`,
	},
	{
		word1: `district`,
		translation1: `dzielnica`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/a5/4c/amsterdam_canal_city_district_dutch_holland_light_night-1159252.jpg!d`,
	},
	{
		word1: `in a rual area`,
		translation1: `w wiejskiej okolicy`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/images/e8/c5/964bfd8b2ab632960be5751c7e65-1440391.jpg!d`,
	},
	{
		word1: `in a centre`,
		translation1: `w centrum`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/d2/ca/london_underground_train_station_people_traffic_busy_crowded_stairs-892254.jpg!d`,
	},
	{
		word1: `in the countryside`,
		translation1: `na wsi`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/ec/36/guitar_country_girl_music_guitarist_countryside_acoustic_guitar_boots-1323639.jpg!d`,
	},
	{
		word1: `in the suburbs`,
		translation1: `na przedmieściach`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/46/f0/auckland_onetreehill_volcanio_sheep_landscape_newzealand_cityscape_sheepfarming-175455.jpg!d`,
	},
	{
		word1: `inhabitant`,
		translation1: `mieszkaniec`,
		translation2: `mieszkanka`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/images/5a/62/7406a1d813b931ebaff0de00ed00-1428499.jpg!d`,
	},
	{
		word1: `lacated`,
		translation1: `położony`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/images/6d/d7/3d8ad8aabcfcab83a4d127ec5679-1430493.jpg!d`,
	},
	{
		word1: `neighbour`,
		translation1: `sąsiad`,
		translation2: `sąsiadka`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/6a/9a/picket_fences_fence_fencing_neighbor_neighbour_neighborhood-965238.jpg!d`,
	},
	{
		word1: `neighbourhood`,
		translation1: `sąsiedztwo`,
		translation2: `okolica`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/images/31/32/a20208a2fb8e22865a7110f61774-1424313.jpg!d`,
	},
	{
		word1: `Old Town`,
		translation1: `stare miasto`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/bc/91/town_black_and_white_old_village-98980.jpg!d`,
	},
	{
		word1: `on the edge of`,
		translation1: `na skraju (czegoś)`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/c9/20/living_on_the_edge_home_house_teeter_teetering_edge_cliff_residence-872828.jpg!d`,
	},
	{
		word1: `overlook`,
		translation1: `wychodzić na`,
		translation2: `mieć widok na`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/ab/ea/woman_lady_female_blonde_overlook-1388962.jpg!d`,
	},
	{
		word1: `public transport`,
		translation1: `transport publiczny`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/ed/d6/bus_seat_public_transportation_bus_ride_transportation-7528.jpg!d`,
	},
	{
		word1: `residents`,
		translation1: `mieszkańcy`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/14/35/park_chicago_water_fountain_canon_children_illinois_eau-535173.jpg!d`,
	},
	{
		word1: `view`,
		translation1: `widok`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/images/83/d7/a1079f9f415a0e7736befeb1318e-1568435.jpg!d`,
	},
	{
		word1: `village`,
		translation1: `wioska`,
		level: `basic`,
		type: `położenie`,
		image: `https://c.pxhere.com/images/39/7a/c231641ffa2e8f5c7faedf2a6dbb-1447687.jpg!d`,
	},
	// // // -extended
	{
		word1: `a stone's throw from`,
		translation1: `rzut kamieniem od`,
		level: `extended`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/42/00/balance_beach_blue_coastline_heap_ocean_peace_pebble-1260584.jpg!d`,
	},
	{
		word1: `across the road from`,
		translation1: `po drugiej stronie ulicy`,
		level: `extended`,
		type: `położenie`,
		image: `https://c.pxhere.com/images/d4/ac/449725f029ba24f1c132e540b906-1542243.jpg!d`,
	},
	{
		word1: `amenities`,
		translation1: `udogodnienia`,
		level: `extended`,
		type: `położenie`,
		image: `https://c.pxhere.com/images/38/d5/8b3a71df32d6aab68617d17473f0-1434861.jpg!d`,
	},
	{
		word1: `central location`,
		translation1: `centralne położenie`,
		level: `extended`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/4f/02/architecture_skyscraper_urban_city_office_construction_building_downtown-877703.jpg!d`,
	},
	{
		word1: `hustle and bustle`,
		translation1: `zgiełk`,
		level: `extended`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/c5/0e/carousel_turn_speed_folk_festival_fair_year_market_lights_rides-708199.jpg!d`,
	},
	{
		word1: `in the heart of the countrysite`,
		translation1: `na głębokiej wsi`,
		level: `extended`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/65/cf/barn_lightning_bolt_storm_thunderstorm_clouds_night_shack-804994.jpg!d`,
	},
	{
		word1: `in the middle of nowhere`,
		translation1: `na odludziu`,
		translation2: `w szczerym polu`,
		level: `extended`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/85/4d/street_road_desert_dry_drought_lonely_alone_asphalt-1337531.jpg!d`,
	},
	{
		word1: `lane`,
		translation1: `dróżka`,
		level: `extended`,
		type: `położenie`,
		image: `https://c.pxhere.com/images/c7/21/7a517f4919870761ff6e2f255bce-1519865.jpg!d`,
	},
	{
		word1: `off the beaten track`,
		translation1: `na uboczu`,
		level: `extended`,
		type: `położenie`,
		image: `https://c.pxhere.com/photos/d2/96/road_forest_tree_lined_avenue_nature_asphalt_landscape_forest_road_loneliness-1403748.jpg!d`,
	},
	{
		word1: `within walking distanse of`,
		translation1: `w bliskiej odległości (możliwej do pokonania pieszo)`,
		level: `extended`,
		type: `położenie`,
		image: `https://c.pxhere.com/images/17/2e/588a7993c643e3c0c31d06d66cab-1418478.jpg!d`,
	},
];

export default words1_TypesOfHouses